### ISSUE TITLE
Edit adaptive Metropolis algorithm to allow it to sample non-negative parameters

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#102]
At the moment, the sampler, I think, is only set to work on unbounded parameter spaces. I think we can change this by sampling the log transform of bounded parameters (and adding a Jacobian term  to account for change of variables).

**Comment by MichaelClerx** [comment]
What's the advantage over setting a zero prior (which can also do upper bounds) ?

**Comment by ben18785** [comment]
Suppose you want to set a prior for a standard deviation parameter. I would
always encourage the use of non-uniform 'weakly informative' priors for
such parameters. These act to avoid issues with slow convergence of MCMC
algorithms and typically make much better intuitive sense (do we believe
that p(sigma=1) = a > 0, and p(sigma=1.000001) = 0, for example?). In these
situations, I would say (and very much reflects the view of Gelman etc.),
it's better to use a half-normal prior with a large standard deviation than
to use a uniform distribution. When we use half-normal priors, as well as
any other weakly informative priors, there is no natural way to set a lower
bound on a parameter, and so we need to modify our sampler to account for
this. This is why Metropolis-Hastings was created (over just the Metropolis
algorithm). An alternative to Metropolis-Hastings, is to log transform all
variables and sample from that space.

**Comment by MichaelClerx** [comment]
Same should also be applied to #116 once that's ready

**Comment by ben18785** [comment]
Yes, I think this is actually quite essential. I'm moving it to priority.

**Comment by MichaelClerx** [comment]
Still two things:

1. If you want to just do a parameter transform, that can be handled differently! See @martinjrobins example in examples/optimisation-transformed-parameters.ipynb
2. Would at least some of the problem be solved by combining two priors (one with a hard boundary and one with a soft boundary) ?

I'm a big fan of point 1: No need to code it up in each and every inference method when it's only a few lines to transparently transform your parameters before passing it in!
