### ISSUE TITLE
Add Hamiltonian MC (HMC) to Pints

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#104]
I think we should try to include this. It would require a user to specify another part to process, a function that accepts a parameter as an input and outputs a gradient of the log posterior (in other words, the sensitivity).

**Comment by MichaelClerx** [comment]
hmc?

**Comment by MichaelClerx** [comment]
See #101

**Comment by ben18785** [comment]
Sorry, Hamiltonian Monte Carlo. This requires sensitivities, unlike #101.

**Comment by ben18785** [comment]
@MichaelClerx @sanmitraghosh @martinjrobins I've started to code up HMC in a branch as think we really need it for our paper. The following things occur to me though about the implementation and wanted to get your view on this before getting too deep into the code,

- To allow a SingleSeriesProblem to be optionally endowed with a method (I suggest 'logDerivative' or 'derivative_log' or something to that tune -- standing for the derivative of the log posterior), can I just add such a method to core.py's SingleSeriesProblem that returns this? This method only ever being called by those methods which need sensitivities.
- I think we want MultiSeriesProblems to allow this? If so, can I just do the same as the above?
- Does it make sense to have a subclass of _mcmc methods that work with the sensitivity? There are other methods, like MALA, which also use this information.
- I want us to be mindful that we will probably use HMC in a bunch of other methods, like SMC and populationMCMC, to update individual chains. How can I ensure that this is done in the most effective way?
- Are we assuming that we don't parallelise any aspect of ask? Just thinking if we are running many chains in parallel here, it may be expensive to do the numerical integration (which is required in HMC to solve for the particle's path) this may be slow.

**Comment by ben18785** [comment]
Note to self: be sure to search for divergent iterations, like Stan does. See page 401 in the 2.17.0 Stan manual [here](https://github.com/stan-dev/stan/releases).

**Comment by martinjrobins** [comment]
- The derivative of the log posterior would no doubt depend on the particular likelihood and prior chose. So the likelihood, model and prior all need to implement a derivative function?
- I don't see why we can't parallelise the numerical integration in the chains

**Comment by ben18785** [comment]
Yes, I think you’re right. This would mean that log priors need derivatives. Shouldn’t be too tricky though seeing as the likelihoods are all simple.

**Comment by martinjrobins** [comment]
#298 now implements sensitivities for two of the models, which should be enough to get started on this

**Comment by sanmitraghosh** [comment]
@MichaelClerx @ben18785 assign the partial derivative of logPosterior to me as I would use this for MALA, smMALA.

**Comment by ben18785** [comment]
@sanmitraghosh Ok, although are you going to work on this, this week? I am planning on writing HMC code (that takes the derivative of the log posterior) over the next few days...

**Comment by sanmitraghosh** [comment]
@ben18785  I am planning to do this during or post Easter weekend.

**Comment by ben18785** [comment]
Great stuff.

**Comment by MichaelClerx** [comment]
PR in #323
