### ISSUE TITLE
Add two German credit score toy problems

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#1049]
As used in the NUTS publication [here](http://jmlr.org/papers/volume15/hoffman14a/hoffman14a.pdf) and is a standard benchmark dataset/model for comparing MCMC algorithms.

This toy problem isn't a time series and requires a dataset of 1000 individuals' data (the dataset is small -- only 0.4Mb). My question is, how should we do this? It's worth discussing as I think, increasingly, we are going to want to use toy models with real data to benchmark algorithms as these tend to be preferred. Should the data be in a separate repo or, can we just download it every time we want to use it from a website (assuming it's hosted)?

**Comment by MichaelClerx** [comment]
Can it be a LogPDF ?

**Comment by MichaelClerx** [comment]
Storage wise I'd say separate repo?

**Comment by martinjrobins** [comment]
I don't think we need to store this data at all since its a standard dataset (https://archive.ics.uci.edu/ml/datasets/statlog+(german+credit+data)). I would say the LogPDF should dynamically download the data into memory when it is created.

**Comment by MichaelClerx** [comment]
I _realllllly_ don't like software that automatically gets stuff from the internet :-|
You know, unless it's a browser or messenger application or something

**Comment by martinjrobins** [comment]
like `pip`??? ;)

**Comment by MichaelClerx** [comment]
:D :D :D Things I don't expect to download stuff shouldn't, that's my general feeling. Too old-fashioned?

**Comment by martinjrobins** [comment]
no, in general I do agree with you. But unfortunately I don't think we can have a decent set of toy problems without having some of the standard machine learning datasets. So we either need to bundle with pints, or assume the user has internet connectivity. We could always allow the user to input a filename to the LogPDF in case they want to use a local copy?

**Comment by MichaelClerx** [comment]
That could work!
Looking at the link you stuck in, it looks like very little data that should be very zippable? We can store a zipped version (and without the doc and index) and then unzip from python before use (it's a one-liner)?

**Comment by martinjrobins** [comment]
yea, its easy enough to zip and unzip, happy to do this (mind you, presumably git compresses everything when you clone a repo anyway?)

**Comment by MichaelClerx** [comment]
I'm sure it does, hope pip does that too, but not sure?

**Comment by ben18785** [comment]
The PINTS repo is about 200Mb at the moment so, as long as the dataset is small, can't we package this in PINTS? The German credit data is about 80Kb when zipped, so how about we create a pints/toy/datasets folder for these small ones? If the folder became larger than a few Mbs, then I'd suggest we need to think of something else...

**Comment by ben18785** [comment]
An alternative idea is to have another repo: pints-datasets? Then, whenever we need something, we just import from there.

**Comment by MichaelClerx** [comment]
I don't think I'd mind packaging this data, as long as we don't have to go through hoops for the licensing?

As far as size is concerned though... Although the git repo is bigger, the PINTS files users will eventually install on their system are just 1.1mb at the moment (almost half of which is test).

That's quite impressive, that we typed that many characters :D

**Comment by ben18785** [comment]
This was closed by 7ad29c1cbee52d5e97b4ad55901ee673a1202d52
