### ISSUE TITLE
C++ vs Python for sampling functions

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#105]
Reading a few of the papers on various MCMC routines, it seems that the majority of them are written in C++, for speed reasons. I am quite naive as to how easy it is to connect a C++ function with a Python one. My question is this, for speed reasons, would it make sense to write the MCMC samplers in C++? Or would the overhead in repeatedly calling the model class in Python mean this wasn't worthwhile?

Forgive the naivety of this!

**Comment by MichaelClerx** [comment]
From what I've seen, the samplers themselves are tiny (10 lines?) and do very little. Will be completely dwarfed by the overhead of solving a system of ODEs!

So we _could_ write the samplers in C or C++, but I don't think it'd help at all (and it would mean you'd have to compile pints before using, which is a can of worms I'm happy to avoid)

**Comment by ben18785** [comment]
Ok, that's good to know. I suspected that this would be the case but wanted to check!

**Comment by mirams** [comment]
Yep - Ross has been using python for samplers/MCMC. The ODE solving is by far the largest part of anything we do.
