### ISSUE TITLE
MCMC initialisation functions

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#1050]
At the moment, we either do one of the following:

1. Initialise all chains at non-random points
2. Randomly sample a starting value from some distribution, then pass these values to the MCMC samplers

Point 1. would make most Bayesian practitioners balk since it isn't best practice: by setting starting points _a priori_ you essentially bias samplers towards areas in parameter space that you know.

Point 2. is fine theoretically but causes practical problems: if the values sampled correspond to non-finite values of the log-posterior, then sampling doesn't execute.

To get around both of these issues, I'd suggest we consider the following (which I suspect is what Stan does):

- An MCMC sampler/controller can either accept an initial value set (as it currently does) or a function that will (randomly) sample initialisation points.
- When sampling starts, the function executes and passes this parameter set to the MCMC sampler: if the log-posterior is finite, all's hunky dory; if it's not, then the function resamples parameter values and tries these; and so on.
- If a given number of tries do not result in finite initial log-posteriors, then sampling does not execute. This number of tries would have sensible defaults (say 100 such sets are trialled) but could also be set by the user.

The reason for needing some leeway in terms of allowing quite a few tries before success is that, for more complex models, a more narrow region of parameter space typically has (effectively) non-zero probability density.

What do people think of this? As I say, I am a bit concerned at the moment that the way we initialise our chains isn't best practice (especially in the notebooks where we are quite slapdash about it). 

If people think this is reasonable, how would I go about doing this? I'd need to pass a function to the MCMCController, I suppose (not something I've done before in Python but looks straightforward enough).

**Comment by martinjrobins** [comment]
In general I like this @ben18785. Although perhaps rather than passing in a function we should pass in a `pints.LogPrior`, or at least give the option of doing the latter.

**Comment by MichaelClerx** [comment]
I'm happy for us to make changes here! Agreed with martin that passing in a LogPrior would make more sense (it's already a `callable`, just like functions are, so essentially it acts like a function-with-some-restrictions-and-extras, which is exactly what we need)

Also this should be tackled together with https://github.com/pints-team/pints/issues/615

**Comment by ben18785** [comment]
Ok, great -- thanks both. I agree using a `LogPrior` is a good idea. I am going to try and make some headway with this.

**Comment by MichaelClerx** [comment]
Closed in #1322
