### ISSUE TITLE
Data with error bars

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1059]
@matthiaskoenig has an optimisation problem where there are (vertical) error bars on the time series.

We haven't thought about this one yet, might be good to consider!
Also the extended use cases with horizontal+vertical bars, or a time series of distributions of (time, values) ?
(And the case where the simulation as well as the experiment have uncertainty)

At the moment, as long as you can define an `ErrorMeasure` that does what you need you'll be able to perform optimisation on this sort of problem with PINTS.
But it'd be good if we thought about this a bit more so in the future we could have predefined error measures, problem classes, and model types for this sort of thing

**Comment by ben18785** [comment]
Think we discussed this on the call: to do inference here, you would need the raw data (not an error bar measure). Would people mind if I closed this?
