### ISSUE TITLE
Stan interface

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#1071]
Should be easy to do and worthwhile

**Comment by MichaelClerx** [comment]
Might be worth sticking in a separate project, if only for the unit testing etc.

**Comment by martinjrobins** [comment]
This would be really valuable to have. If you could use stan for your model and pints for the sampling, that is a killer combination. Allows you suddenly to easily do sampling of hierarchical models in pints, more exotic probability distributions etc. Stops us re-inventing the wheel on all these things.

might be work doing this in mainline pints? I always think that getting different software packages to work together is a good way to go. Adds the dependency of pystan, but we could make this an optional one. That is, only import the interface / run the tests, if pystan is already installed?

**Comment by MichaelClerx** [comment]
Fair enough, happy with optional extras :-)

**Comment by MichaelClerx** [comment]
Would require slight updates to unit testing #1073

**Comment by MichaelClerx** [comment]
And someone needs to figure out how to install stan on travis. If this means our unit tests start taking more than 10-15 minutes I don't think we should do it in the main repo.
