### ISSUE TITLE
Switch from AppVeyor + Travis to GitHub Actions

### ISSUE THREAD

**Issue by fcooper8472** [pints-team/pints#1074]
Just for discussion at this stage.

Currently we use two services for CI, but GitHub actions looks to be the future.  It would allow us to do testing on macOS Linux and Windows in one service.

The biggest win though in my opinion is that all CI scripts are different files in a `.github` directory, so each type (coverage, unit, etc) is a simple standalone script, reducing the logic necessary in the CI script.

See an example for a different project that I've set up:
https://github.com/QuEST-Kit/QuEST/tree/master/.github/workflows

Not a priority, certainly, but thoughts?

**Comment by MichaelClerx** [comment]
Happy to have it all in one place, but would probably prefer to be lazy instead of hopping on board too early :D 

That said, I'm still waiting for travis to pick up windows testing...

Hadn't heard of github actions, and the first thing I find when googling is this: https://github.com/marketplace?type=actions
which doesn't fill me with confidence

**Comment by MichaelClerx** [comment]
Example looks good though!

Is this a sustainable model for github? It must cost them a lot of money building and hosting all this stuff

**Comment by fcooper8472** [comment]
> Hadn't heard of github actions, and the first thing I find when googling is this:

I think the link you're looking for is https://github.com/features/actions

When it's configured you get a top-level tab in the homepage of the repo for viewing output of runs.

> Is this a sustainable model for github? It must cost them a lot of money building and hosting all this stuff

GitHub is owned by Microsoft, and GitHub actions is essentially Azure Pipelines wrapped up to look like GitHub.  So it's run on Microsoft's cloud and I'm sure they have the resources to keep it running.

They are very generous with machines: each run has 2 cores, 7 Gb RAM and a runtime capped at 6(!) hours.

**Comment by MichaelClerx** [comment]
Sounds alright actually. Appveyor is holding a lot of things up at the moment.

As long as we don't use any fancy features so we can always easily change to another platform & avoid the inevitable monetising vendor lock-in schemes :D

**Comment by fcooper8472** [comment]
See also #848

**Comment by fcooper8472** [comment]
Unit tests now (also) run on GitHub actions, see [results](https://github.com/pints-team/pints/actions/runs/68581233).

This currently runs 20 configurations (`[ubuntu-16.04, ubuntu-latest, macos-latest, windows-latest] x [2.7, 3.5, 3.6, 3.7, 3.8]`) which are pleasingly all passing, although I think this is overkill!

My suggestion would be to break this into two runners, one for OS coverage where we test a range of operating systems with the newest python, and one for Python coverage where we test every python version on the latest Ubuntu.

I think this latter approach would be more in line with what we're currently doing.

**Comment by fcooper8472** [comment]
the actions script is here:

https://github.com/pints-team/pints/blob/i1074-gh-actions/.github/workflows/unit-tests.yml

**Comment by MichaelClerx** [comment]
Cool!

> My suggestion would be to break this into two runners, one for OS coverage where we test a range of operating systems with the newest python, and one for Python coverage where we test every python version on the latest Ubuntu.

Sounds sensible to me

**Comment by fcooper8472** [comment]
There still seems to be an active appveyor integration (@MichaelClerx)

https://ci.appveyor.com/project/MichaelClerx/pints/builds/31936837

This can be closed when that's fixed, I think?

**Comment by fcooper8472** [comment]
> One final thing is we need to update the branch rules for `master` so that all the new checks need to pass before you can merge. Needs some attention as the list shows everything that's been active in the last week, so need to filter out the ones that no longer exist :D

I think that is now done! We currently require the python and OS coverage unit tests, style, copyright, doctest and report from codecov.

**Comment by fcooper8472** [comment]
> I guess also delete .slow-books, and maybe make .error-books just a list inside `run-tests.py` ?

Something does't look right with the notebook tests.  While it ran on schedule last night, it took 0 seconds to run all the notebooks:

https://github.com/pints-team/pints/runs/559838073?check_suite_focus=true

The run command was `python run-tests.py --allbooks`

**Comment by fcooper8472** [comment]
Urr... @MichaelClerx not sure exactly what's going on here, but [this commit](https://github.com/pints-team/pints/commit/15e8ec5e610edd453315d3c0db71d3f5354550d5#diff-b873b3ab5a7fcbdf9c691a62c7628153R352) seems to have introduced a non-configurable `debug=true` flag that interacts with a codeblock

```
if debug:
    print(notebook)
else:
    ok &= test_notebook(notebook)
```

As far as I can see it's currently impossible to actually run the notebooks?

**Comment by MichaelClerx** [comment]
Oh dear, did we leave it in debug mode :man_facepalming: 
That's probably my fault

**Comment by MichaelClerx** [comment]
Yeah that was just to test that the directory scanning and filtering etc. was all working. Maybe remove the whole debug flag just to be safe!

**Comment by fcooper8472** [comment]
@MichaelClerx tried running locally, and it falls over because `autograd` isn't installed.  Unless I'm missing something this isn't in either the regular or the dev requirements?

**Comment by fcooper8472** [comment]
(it's used in, unsurprisingly, `examples/toy/automatic-differentiation-using-autograd.ipynb` which is a slow book currently, so perhaps unsurprising as these aren't usually run!).

If it's in an example that ships with pints though, it should presumably be a dependency...

**Comment by fcooper8472** [comment]
```
Collecting autograd
  Downloading autograd-1.3.tar.gz (38 kB)
```
It seems to be really small and fast to install, so I'll just add it in for now!

**Comment by MichaelClerx** [comment]
Uhm, no, should not be a dependency!
If we have an example that uses it, but no pints code that uses it, it shouldn't live in this repo but in some other repo somewhere!

**Comment by MichaelClerx** [comment]
@ben18785 @martinjrobins what do you think?
It's my opinion stuff like this should live in its own repo, under pints-team somewhere, just like https://github.com/pints-team/electrochem_pde_model and https://github.com/pints-team/myokit-pints-examples already live in their own repo. This lets them use dependencies that are not required for pints (or even pints-extras). We should probably list them on the examples index, under e.g. "Examples of using pints with other software packages"

**Comment by martinjrobins** [comment]
I'm happy with it living in its own repo, but this does create extra work, since we have to setup ci + testing on each of these repos.... Easier to just create a new ci build on the main repo?

**Comment by MichaelClerx** [comment]
I don't mind if the external examples are not tested automatically

**Comment by ben18785** [comment]
I think it's easier for users if it's all in one repo, so vote for that.

**Comment by MichaelClerx** [comment]
Fair enough, but note that if they get it from this repo it won't actually work, because they'll be missing the dependency
