### ISSUE TITLE
Move autograd notebook to separate repo

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1099]
What I'd like to do:

- move the autograd into its own repo
- update the link on examples/README.md
- Create a section "Using PINTS with external tools" on the examples page, and link the autograd example there, along with https://github.com/pints-team/electrochem_pde_model and https://github.com/pints-team/myokit-pints-examples

Reasoning:

- none of the PINTS code uses autograd, so it doesn't make sense to add it as a dependency (even an extra dependency)
- without autograd installed, the notebook can't run, causing the notebook tests to fail
- we already have two examples of using external tools (see above), both in separate repos

Original discussion started in https://github.com/pints-team/pints/issues/1074#issuecomment-609423509 before moving to https://github.com/pints-team/pints/issues/848#issuecomment-609450100

**Comment by MichaelClerx** [comment]
Thoughts @martinjrobins and @ben18785 ?

**Comment by martinjrobins** [comment]
In terms of "using pints with external tools", It would be nice if these things get tested as part of our CI, so we can be sure we are not breaking interfaces. Can we have a set of "interface" notebooks, that are tested separately by a separate build. I.e, have an "autgrad" ci build, and an "stan" ci build, etc.

Saying that, I guess we can just set these things up on a separate repo, and set a cron to test them, eg. every night. So I'm saying if you are keen for them to be in  a separate repo then that is fine with me! :)

**Comment by MichaelClerx** [comment]
It feels a bit odd to me to "polute" our `setup.py` with stuff that's for examples only, that's all! Especially since we'll be using it for the `pip install` soon too (which I'm guessing won't include the examples, because they'd end up somewhere in `/usr/whatever` where users won't be looking for them)

**Comment by martinjrobins** [comment]
autograd doesn't need to be in `setup.py` does it? Just whatever ci build is running this notebook needs to make sure that autograd is installed....

**Comment by MichaelClerx** [comment]
Let's move it to "interfaces", now that that is a thing! #1270
