### ISSUE TITLE
Intro for notebook for ARMA errors

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1102]
Currently starts by saying "this notebook shows you how to do diff ev mcmc", which is not what it's (mainly) about

**Comment by MichaelClerx** [comment]
@rcw5890 can you pick this one up? And maybe look at the other AR error notebooks as well?

**Comment by rcw5890** [comment]
Sure, I'll take a look

**Comment by MichaelClerx** [comment]
Thanks!

**Comment by rcw5890** [comment]
Closed in #1110
