### ISSUE TITLE
Option for MCMCController to output simple plot as it runs

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#1113]
@ben18785, @rcw5890 and I all thought it may be helpful to have an otpion in MCMC runs to output some simple plots (maybe even just the trace plot) as it runs. I am imagining this as a similar option as the save chains as csv as it runs.

Justification: There's no (clear) way to determining how long a chain should be, and it's really difficult to restart the run. So a easy way to go with this is to set the run as long as possible, then look/monitor the chain as it runs. When it 'looks' converged/OK and we are happy, we terminate it or do something else. (Both me and Richard ran into the same problem, and Ben thought it's a 'common' issue.)

Might have mentioned it before (but couldn't find the issue!), so I open one for this.

**Comment by MichaelClerx** [comment]
Perfect use-case for doing it yourself with ask-and-tell!

**Comment by MichaelClerx** [comment]
Someone could do a notebook on this :-)
