### ISSUE TITLE
Figure plotting bug

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#1116]
I've noticed that Pints plots don't seem to be showing of late... when I do the following, for example:

`pints.plot.trace(chains)
plt.show()`

I just get the following (not a plot):

> Figure size 1200x600 with 6 Axes

**Comment by MichaelClerx** [comment]
Do you mean inside notebooks?

**Comment by ben18785** [comment]
Yep.

**Comment by MichaelClerx** [comment]
That's a known thing, but not a PINTS issue :-)

https://github.com/jupyter/notebook/issues/3670

**Comment by ben18785** [comment]
Cool -- ta
