### ISSUE TITLE
Fix simulateS1 method in ConstantModel

### ISSUE THREAD

**Issue by DavAug** [pints-team/pints#1122]
The `ConstantModel` is defined as 

$ f(t) = (p_1, 2 p_2, 3 p_3, ..., n p_n) $.

The partial derivatives in `pints.ForwardModel.simulateS1` are currently computed as

$\frac{f_i}{partial p_k} = \delta _{ik}$,

when they really should be
 
$\frac{f_i}{partial p_k} =k  \delta _{ik}$.

**Comment by DavAug** [comment]
PR #1123

**Comment by MichaelClerx** [comment]
Good shout!

**Comment by MichaelClerx** [comment]
Usually we tag the issue in a commit somewhere, e.g. "fixes #1122". Then when the PR gets merged the issue gets closed automatically (so it stays open until the fix is on master)

**Comment by DavAug** [comment]
Ah cool! I didn't know that is possible. Would you like me to reopen and take it in the next commit?

**Comment by MichaelClerx** [comment]
Nah just for future issues!
