### ISSUE TITLE
Improve docstrings of rhat and rhat_all_params

### ISSUE THREAD

**Issue by DavAug** [pints-team/pints#1144]
Currently the docstrings are as follows:

- pints.rhat(samples)
Calculates 𝑅̂ =𝑠𝑞𝑟𝑡(((𝑛−1)/𝑛∗𝑊+(1/𝑛)∗𝐵)/𝑊) as per [1] for a single parameter. It does this after splitting each chain into two.

- pints.rhat_all_params(chains)
Calculates 𝑅̂ =𝑠𝑞𝑟𝑡(((𝑛−1)/𝑛∗𝑊+(1/𝑛)∗𝐵)/𝑊) as per [1] for all parameters. It does this after splitting each chain into two.

Maybe it is expected to know what W and B are in those cases, but would it not be nicer to at least say that W is the within chain variance and B the between chain variance, and maybe even define those quantities more explicitly?

**Comment by chonlei** [comment]
Agreed -- it's a duplicated issue #1101
