### ISSUE TITLE
rhat computation warm up and split into sub chains

### ISSUE THREAD

**Issue by DavAug** [pints-team/pints#1158]
Currently Rhat is not computed according to the provided reference, where it is suggested to ignore the first half of each chain to reduce the bias of the initial conditions. Then the truncated chains are split into two so the stationarity of each chain can be assessed. 

Neither of those steps are currently performed in the pints.rhat method. Is this on purpose, so these manipulation are expected to be done by the user, or should we integrate them into the rhat computation.

I personally was confused that these operations were not automatically performed and other users might be too.

**Comment by ben18785** [comment]
So, yes, this is currently done for rhat_all_params (which is what the
results table calls to make its summary) but not for rhat. I think that
perhaps it's worth discussing this first though -- there are new versions
of rhat that we probably should be using now, so we may just want to use
these instead.

**Comment by MichaelClerx** [comment]
How does this relate to the general question of how much warm up and/or thinning we need? E.g. #291 #1140 

(And if we have great methods to estimate these, then why not automate, e.g. allow these things to be used as stopping criteria in e.g. the MCMCController #290 )
