### ISSUE TITLE
Add Particle MC (SMC)

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#117]

**Comment by MichaelClerx** [comment]
@ben18785 is this different from #120 ?

**Comment by martinjrobins** [comment]
@ben18785 @sanmitraghosh: I have been thinking of trying out particle filtering on an electrochemistry model (have experimental data where one of the parameters varies over time, we currently fit a polynomial to it for optimisation). Will the SMC implementation planned for pints help me here?

**Comment by ben18785** [comment]
Yep, possibly. But you would need a modelled process for the parameter rather than just fitting it with a spline.

So, for example,

theta_t = rho theta_t-1 + e_t

where e_t ~ N(0,sigma).

**Comment by MichaelClerx** [comment]
Closing this as duplicate of #120
