### ISSUE TITLE
Multiple initial values for OptimisationController

### ISSUE THREAD

**Issue by DavAug** [pints-team/pints#1178]
Similar to the MCMCController I think it would be neat if we could simply pass multiple sets of initial values to the OptimisationController and run multiple optimisations. This would be useful for quick identifiability checks.

It is possible to just loop multiple times through the OptimisationController.run() method, but I personally think it would be nice if the controller could handle that.

**Comment by MichaelClerx** [comment]
The controller has way too many responsibilities already, I think! Plus, there's an obvious way to handle parallelisation for chains, but for optimisation it's not so clear cut...

**Comment by MichaelClerx** [comment]
See [here](https://github.com/pints-team/myokit-pints-tutorial/blob/main/ion-currents-tutorial/big-fitting.ipynb) for an example of running multiple optimisations

**Comment by DavAug** [comment]
Ok. Thank for the notebook. It's very helpful!

**Comment by chonlei** [comment]
Agree with Michael that this can be done outside Pints. And user can do their own parallelisation (on top of the parallelisation for each optimisation)...
