### ISSUE TITLE
Matplotlib update breaks test_surface

### ISSUE THREAD

**Issue by rcw5890** [pints-team/pints#1184]
It looks to me that as of matplotlib-3.3.0, test_surface in test_plot.py is failing. The test passes with matplotlib-3.2.2 (previous release) but starts failing when you update matplotlib.

```
ERROR: test_surface (test_plot.TestPlot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pints/pints/pints/tests/test_plot.py", line 555, in test_surface
    pints.plot.surface(points, values)
  File "/home/runner/work/pints/pints/pints/plot/_surface.py", line 96, in surface
    c = PolyCollection(
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/matplotlib/collections.py", line 1125, in __init__
    self.set_verts(verts, closed)
  File "/opt/hostedtoolcache/Python/3.8.3/x64/lib/python3.8/site-packages/matplotlib/collections.py", line 1153, in set_verts
    verts_pad = np.concatenate((verts, verts[:, :1]), axis=1)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by rcw5890** [comment]
I think the problem comes from this [matplotlib 3.3.0 commit](https://github.com/matplotlib/matplotlib/pull/16689/commits/95977d6443a2430307f2379ea7450f15d21bcd57), which adds a fast method when vertices is a numpy array:

```
if isinstance(verts, np.ndarray):
    verts_pad = np.concatenate((verts, verts[:, :1]), axis=1)
    ...
```

In pints, `regions` as returned by `_voronoi_regions` is a numpy array and thus triggers this condition, however `regions` is a 1d object array which fails on the next line.

One fix might be to have `_voronoi_regions` return a list instead of the 1d numpy array. That should cause matplotlib to just iterate through the list in the previous way when we call `PolyCollection` in `surface`.

**Comment by MichaelClerx** [comment]
Good find! This is currently also causing the example notebook test to fail

**Comment by MichaelClerx** [comment]
Not sure what's needed exactly, but can't reproduce in Python3.7, only in 3.8!

**Comment by MichaelClerx** [comment]
I've created a bug report in matplotlib too, @rcw5890 !

https://github.com/matplotlib/matplotlib/issues/18017
