### ISSUE TITLE
check NUTS behaviour if a NaN gets returned

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#1198]
there has been some problems with the Nuts sampler for models returning nans, see #1112. There are some checks for this that have solved the immediate problems, but need to check this more thoroughly.

**Comment by MichaelClerx** [comment]
See #794 and #251

**Comment by ben18785** [comment]
Victor (whom Martin and I are supervising) has resolved this and is going to create a PR.

**Comment by ben18785** [comment]
Closed by #1264
