### ISSUE TITLE
Add sequential MC (SMC)

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#120]

**Comment by chonlei** [comment]
Maybe have a look at the pymc3 branch? I added their smc there already (as one of our MCMC classes). 

I can do a PR if you prefer that.

**Comment by MichaelClerx** [comment]
I guess we want to do one ourselves as well?
Otherwise we'll have to figure out what to do about the dependencies

**Comment by ben18785** [comment]
Note to self, mainly. This is the best paper on this: https://pdfs.semanticscholar.org/88d9/b46f7196499679338a01484461eb86d701fd.pdf

Unsurprisingly, by Chris Holmes!

**Comment by MichaelClerx** [comment]
New ref: Del Moral 2006 paper

**Comment by ben18785** [comment]
#465 addresses this.

**Comment by MichaelClerx** [comment]
See also:  #568

**Comment by MichaelClerx** [comment]
See also: #474

**Comment by MichaelClerx** [comment]
This could be good! https://twitter.com/uPicchini/status/1298216180545658880
A new book on smc, including python examples, and a repo of python code
@ben18785 do you know these guys?
