### ISSUE TITLE
Functional testing for transformed fitting

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#1200]
@MichaelClerx suggested that maybe good to have fittings that fail without a transformation (for functional testing?), see https://github.com/pints-team/pints/pull/1165#discussion_r466455711.

**Comment by MichaelClerx** [comment]
Not sure how much of a test for a _method_ this would be though, so un-suggesting it now :D

**Comment by ben18785** [comment]
I actually think this is a good idea. Or, rather to have functional tests where we use the transformation. That's because lots of things can potentially interact with transforms in quite unexpected ways. Ok to reopen?

**Comment by MichaelClerx** [comment]
Sure, but open a new issue in the functional testing repo then. Missed this one when I moved them all over!
