### ISSUE TITLE
Add some kind of change log file

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1202]
> Perhaps to facilitate the writing of release notes, every PR should add a line to a CHANGELOG.md file (divided into sections for features, bug fixes etc)?

Anyone have any ideas how best to structure this?

`##` For every release, with `###` for features/bug-fixes ?

Todo:
- [x] Decide on format
- [x] Retroactively fill in this file with all changes since 0.3.0
- [x] Update CONTRIBUTING.md, saying adding to this file is a requirement
- [ ] Once merged, bother all open PRs with a message telling them to do this

**Comment by MichaelClerx** [comment]
Is there a standard way of doing this @martinjrobins @fcooper8472 @iamleeg ?

**Comment by MichaelClerx** [comment]
Let me google that for me

https://keepachangelog.com/en/1.0.0/
https://changelog.md/

**Comment by iamleeg** [comment]
OK, I'm late to the party, but the GNU project also have a standard, and various tools to support that standard (e.g. generating changelogs from git logs, or emacs functions to generate changelog entries from edits you're making to source files). https://www.gnu.org/prep/standards/html_node/Change-Logs.html
