### ISSUE TITLE
LogPrior unit cube methods (convert_from_unit_cube convert_to_unit_cube)

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1214]
Just noticed the `convert_from_unit_cube` and `convert_to_unit_cube` methods, defined in `MultivariateGaussianLogPrior` but not actually part of the `LogPrior` interface.

Should they be?

**Comment by ben18785** [comment]
These are mainly just useful for Multinest. We may want to add these to more priors in the future but I'd say it's too early to tell whether this is worth it.

**Comment by MichaelClerx** [comment]
Cool. They only seem to be called in a notebook at the moment
```
[michael@laptop2 pints]$ grep "from_unit_cube" ./ -Ir
./examples/stats/log-priors.ipynb:    "    theta.append(log_prior.convert_from_unit_cube(u[i]))\n",
./pints/tests/test_log_priors.py:        icdfs1 = p.convert_from_unit_cube(qs)
./pints/tests/test_log_priors.py:        self.assertEqual(log_prior.convert_from_unit_cube([0.1])[0],
./pints/tests/test_log_priors.py:        icdfs1 = log_prior.convert_from_unit_cube(qs)
./pints/tests/test_log_priors.py:        icdfs2 = log_prior.convert_from_unit_cube(np.array(qs))
./pints/_log_pdfs.py:    def convert_from_unit_cube(self, u):
./pints/_log_priors.py:    def convert_from_unit_cube(self, u):
[michael@laptop2 pints]$ grep "to_unit_cube" ./ -Ir
./examples/stats/log-priors.ipynb:    "    u.append(log_prior.convert_to_unit_cube(samples[i]))\n",
./pints/tests/test_log_priors.py:        cdfs1 = p.convert_to_unit_cube(xs)
./pints/tests/test_log_priors.py:        self.assertEqual(log_prior.convert_to_unit_cube([-5])[0],
./pints/tests/test_log_priors.py:        cdfs1 = log_prior.convert_to_unit_cube(xs)
./pints/tests/test_log_priors.py:        cdfs2 = log_prior.convert_to_unit_cube(np.array(xs))
./pints/_log_pdfs.py:    def convert_to_unit_cube(self, x):
./pints/_log_priors.py:    def convert_to_unit_cube(self, x):
```

**Comment by ben18785** [comment]
Yep, that's because multinest isn't in yet (it's in a PR).

**Comment by MichaelClerx** [comment]
OK well that's an issue then:

https://github.com/pints-team/pints/pull/1034/files#diff-d50f63ab5851032d4912e5ae96cfe5fbfa53501af3127ee8a4008909b814295fR171

The code here assumes that log_prior has this method, even though it can be any LogPrior. So we need to add these methods to the interface, even if they're optional

**Comment by ben18785** [comment]
Yep, I'd leave these issues related to this for now as they will have to be
addressed as part of that PR.

**Comment by ben18785** [comment]
@MichaelClerx I'm just trying to understand this: when I look at `LogPrior`, I see it has `convert_from_unit_cube` and `convert_to_unit_cube` methods. Was your question whether these should be in the base class?

**Comment by MichaelClerx** [comment]
OK I see them now. Not sure what that was about :D

**Comment by ben18785** [comment]
Cool -- ta!
