### ISSUE TITLE
Should we use "normal" or "Gaussian"?

### ISSUE THREAD

**Issue by rcw5890** [pints-team/pints#1215]
As of #1213 , there is a small inconsistency within Pints, since we are using "TruncatedNormalLogPrior" for the [truncated normal distribution](https://en.wikipedia.org/wiki/Truncated_normal_distribution), but "GaussianLogPrior" for the [non-truncated version of the same distribution](https://en.wikipedia.org/wiki/Normal_distribution). 

I would be happy to flip "TruncatedNormalLogPrior" from the latest PR to "TruncatedGaussianLogPrior" to stay consistent within Pints. That would help users see how similar these distributions are, and how you might want to switch out one for the other as needed.

On the other hand, "truncated normal" seems to be the more common name for the truncated distribution, both in other libraries (Scipy, Tensorflow, R) and in the literature (5210 Google scholar hits for "truncated gaussian distribution" vs. 22800 for "truncated normal distribution").

**Comment by ben18785** [comment]
Can we use both?

**Comment by chonlei** [comment]
Maybe make an alias to it?

**Comment by MichaelClerx** [comment]
Technically definitely possible! Questions is whether we want to. In general I'm a big fan of everything having exactly one name. But this one is possibly an exception?

**Comment by rcw5890** [comment]
Agreed to go for "TruncatedGaussian" to avoid ambiguity and maintain consistency.

**Comment by rcw5890** [comment]
Fixed in #1216
