### ISSUE TITLE
Add email warning system if/when functional testing machine (skip?) goes down

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1235]
Is this something azure can do @fcooper8472 ?

Or were we aware of this, but lacking a hazmat suit?

**Comment by MichaelClerx** [comment]
Or actually, it seems to be online but just not running tests...

**Comment by fcooper8472** [comment]
Hmm. I'll look into it.  But not for the next couple of days, unfortunately, I'm pretty snowed under right now!

**Comment by MichaelClerx** [comment]
Thanks!

**Comment by MichaelClerx** [comment]
https://github.com/pints-team/functional-testing/issues/33
