### ISSUE TITLE
Look at Haario adaptive MCMC and find a better source?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1244]
[Haario 2001](https://doi.org/10.2307/3318737) seems to suggest C is based on all history, including from the non-adaptive phase (in which you use C0 but already calculate Ct) ?

![2001-1](https://user-images.githubusercontent.com/517644/102490569-ec494a00-4066-11eb-83f5-45435f7ef5f4.png)
![2001-2](https://user-images.githubusercontent.com/517644/102490577-ee130d80-4066-11eb-865e-09972c4d7d0e.png)
![2001-3](https://user-images.githubusercontent.com/517644/102490582-efdcd100-4066-11eb-87f8-972cb464d20f.png)

In time-honoured tradition, the algorithm for mu is omitted as "obvious" and hidden in the bar over the final Xs.

[Haario 1999](https://doi.org/10.1007%2Fs001800050022) does something different again, using the last H steps to calculate C

![1999-1](https://user-images.githubusercontent.com/517644/102490680-0f73f980-4067-11eb-964d-3d8f34617633.png)

**Comment by MichaelClerx** [comment]
[Ross' 2016 paper](https://doi.org/10.1016/j.yjmcc.2015.11.018) does seem to only adapt with history starting from the first adaptive point. And this matches what we currently do in PINTS

![ross-0](https://user-images.githubusercontent.com/517644/102491205-c8d2cf00-4067-11eb-91d1-e192dc076c15.png)
![ross-1](https://user-images.githubusercontent.com/517644/102491207-c96b6580-4067-11eb-9e55-2782754e9a2e.png)
![ross-2](https://user-images.githubusercontent.com/517644/102491211-ca03fc00-4067-11eb-8278-e6414ed1bfd9.png)

**Comment by MichaelClerx** [comment]
Scanning the proofs in Haario 2001, I don't see any Xt0 cropping up, which I expect it should if the proof covers the non-adaptive phase too. So the easiest resolution is that they mean Xt0 instead of X0 in Eq 1, and in fact anywhere outside that first line?

Confusing!

**Comment by MichaelClerx** [comment]
The [DRAM paper](https://link.springer.com/article/10.1007/s11222-006-9438-0) (Haario again) doesn't clear it up

**Comment by MichaelClerx** [comment]
Later work like this (Thanks @ben18785 !) seems to ignore the initial period altogether:

https://link.springer.com/article/10.1007%252Fs11222-008-9110-y

Note they define Haario's method the Ross way

**Comment by mirams** [comment]
Talked to Ross, he thinks thesis/code is consistent and we just used the pre-adaptive phase as 'burn in' and you might not want to use covariance of all of that as you'd mainly get the 'path to a mode' directions in the covariance rather than real useful covariance estimate. Depending on the problem I would think that is often still more useful than an uninformed diagonal covariance guess, but I guess that is up to each little tweaked variant of the algorithms!

**Comment by MichaelClerx** [comment]
Ross is the `[1]` citation in our code/documentation, so that's fine then, I think!
