### ISSUE TITLE
Look into "airspeed velocity" for functional testing

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1247]
Great find by @fcooper8472 
Used by numpy & scipy

https://asv.readthedocs.io/en/stable/

has some changepoint detection ("step detection"), which we can probably add to:

https://asv.readthedocs.io/en/stable/dev.html#module-asv.step_detect

**Comment by fcooper8472** [comment]
Full credit to Thibault for putting me onto it!

**Comment by MichaelClerx** [comment]
https://github.com/pints-team/functional-testing/issues/36
