### ISSUE TITLE
Can we get rid of "better code hub"?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1249]
It now marks every PR as broken and I can't even see why without giving it access to all my public repos.

**Comment by MichaelClerx** [comment]
Might have fixed it by setting the "webhook" to non-"active". I hope this means it still runs but we just don't get notified

**Comment by fcooper8472** [comment]
At the moment we're failing:

- Write Short Units of Code
- Write Simple Units of Code
- Write Code Once
- Keep Unit Interfaces Small

And BCH has pretty good reason for telling us off for those. There is a lot of duplicated code that ought to be refactored; there are functions with very large numbers of branch points (e.g. 78(!) in `MCMCController.run()`); etc.

It's not going to be glamorous work improving these metrics, but I think we ought to keep monitoring at the least because they are pretty sensible things to be warned about.

**Comment by MichaelClerx** [comment]
I'm fine with having some tool that analyses this. It just shouldn't start "failing" PRs because of this. They are guidelines rather than hard rules, after all

**Comment by fcooper8472** [comment]
Can you show me an example where it's "failing" a PR?

AFAIK it should only fail if a changeset causes a guideline to fail that was not previously failing.

**Comment by MichaelClerx** [comment]
Nope! It was failing this one: https://github.com/pints-team/pints/pull/1246
until I updated the webhook (unchecked its "active" box)

**Comment by fcooper8472** [comment]
Unfortunately it's impossible to investigate if the webhook is turned off, and that means it will never be updating the analysis, so all we have right now is a static snapshot.

Was it failing because that PR caused it to go from 6/10 -> 5/10?

**Comment by MichaelClerx** [comment]
Doubt it, but would have to re-enable to check... 

I have to say, I'm still not sold on the idea of checking "code quality" with an automated tool. It makes total sense to check consistency & stuff e.g. with flake8, and even there there's lots of exceptions. What this tool does is much more subjective, and there's no guarantee that code that passes these tests is any good

**Comment by MichaelClerx** [comment]
I've set up a project for the controller refactoring

**Comment by fcooper8472** [comment]
> I have to say, I'm still not sold on the idea of checking "code quality" with an automated tool. It makes total sense to check consistency & stuff e.g. with flake8, and even there there's lots of exceptions. What this tool does is much more subjective, and there's no guarantee that code that passes these tests is any good

This is true, to a certain extent.

But there's also no guarantee that code that passes a unit test is any good either. All of these types of checks and tests increase the likelihood that the code is good. The BCH guidelines certainly aren't infallible, but duplicate code, high complexity, and very large functions are things we probably ought to care about, and probably shouldn't just ignore.

I certainly wouldn't be in favour of turning these checks off unless we replace them with something similar.  But I'm a very small part of PINTS so obviously happy to be out-voted if the consensus is that BCH is causing more problems than it's highlighting.

**Comment by MichaelClerx** [comment]
Thanks Fergus!

>  obviously happy to be out-voted

same here! I think these are interesting discussions to have because I don't know what the right answer is or how we can easily find out!
