### ISSUE TITLE
Add HH AP model to toy models

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#126]
Solve with scipy

- [ ] Model
- [ ] Multiple protocols
- [ ] Test
- [ ] Example page

**Comment by chonlei** [comment]
@MichaelClerx What is this `Multiple protocols` on the list?

**Comment by MichaelClerx** [comment]
Can't remember! Either there's multiple problems in the paper that we need to implement, or it optimises to independent protocols (like you're doing with temperature now)

**Comment by chonlei** [comment]
Close this issue as it is replaced by #395.
