### ISSUE TITLE
Remove for-loop from `autocorrelate_negative`

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1272]
Can be done more efficiently using numpy. Maybe even a 1-liner?

**Comment by Ellmen** [comment]
I think this is closed by https://github.com/pints-team/pints/commit/ea9f921bec954ba7b5d95046b18d3146a3a58206 ?

**Comment by MichaelClerx** [comment]
Thanks @Ellmen . Closed in #1282
