### ISSUE TITLE
Can't see Transformation on readthedocs from link on repo main page

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#1274]
Seems to be a difference between https://pints.readthedocs.io/en/stable vs https://pints.readthedocs.io/en/latest

**Comment by MichaelClerx** [comment]
Yup!

The "stable" version is the newest release, so 0.3, while "latest" is the current state of the repository.
From here: https://github.com/pints-team/pints/blob/master/CHANGELOG.md you can see the transformations were merged after 0.3 was released

So when people pip install they don't get transformations, at the moment, and its those people that the main docs page is for

**Comment by ben18785** [comment]
Cool -- worth another release? Quite a bit has changed since the last one I
see...we now have NUTS and transformations for example...

**Comment by MichaelClerx** [comment]
Closing: resolution is to do a new release
