### ISSUE TITLE
Decorate methods within sampler classes

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#1293]
For every hyperparameter, we currently have to do the following:

1. create a setter set_specific_hyperparameter(...) method
2. create a getter specific_hyperparameter(...) method
3. add the hyperparameter to the set_hyperparameter() method
4. keep track of the number of hyperparameters in the n_hyperparameters method

I am wondering whether it'd be possible to create a decorator for set_specific_hyperparameter that would then do 2, 3 and 4 automatically. This would cut out a lot of code from our classes and more generally just tidy up things (I've noticed, for example, that some classes (e.g. differential evolution) didn't have getters for some hyperparameters).

Thoughts @MichaelClerx @fcooper8472 ?

**Comment by MichaelClerx** [comment]
Maybe, but

- set_x() methods often do valuable checking of x
- set_x() methods need a docstring that isn't just "Set hyperparameter 3" or something
- The more cool tricks we do in code the harder it becomes to understand what's going on

**Comment by ben18785** [comment]
Yeah, I'm not sure. I've been reading that properties are the recommended (i.e. Pythonic) way of handling setters and getters as per the below.

```
class P:
    def __init__(self,x):
        self.x = x

    @property
    def x(self):
        """ This is where you put the comment for the class. """
        return self.__x

    @x.setter
    def x(self, x):
        if x < 0:
            self.__x = 0
        elif x > 1000:
            self.__x = 1000
        else:
            self.__x = x
```

then it's just a case of:

p = P(100)
p.x -> returns value
p.x = 200 -> sets it

Then you could add a second decorator (say `@hyperparameter`) that increments the number of hyperparameters and also adds the setter to the `set_hyperparameters` method. But, I think you're probably right -- this would make things hard to read. So happy to close for now!
