### ISSUE TITLE
Green computing in PINTS unit testing

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#1296]
Been annoyed at myself recently as I sometimes push changes to an open PR when its preliminary: so, I know the tests will fail (and in many cases, the work may be so preliminary that I don't want to test anyway). This is a waste of server resources elsewhere and isn't really that ethical from a carbon perspective.

I do still, however, like using PRs to mark and keep track of progress on things. One thing we could do to still allow this would be to use "draft PRs" as work-in-progress areas and trigger a run of tests only if that PR gets converted into a real PR. I think we could do this just by adding `types: [review_requested, ready_for_review]` to the Github workflows.

Does anyone have any objections to this? @fcooper8472 @MichaelClerx @DavAug @rcw5890

**Comment by MichaelClerx** [comment]
Sounds like a great idea! Lets you share some exploratory work without getting lots of emails too :D

**Comment by DavAug** [comment]
Yep sounds great!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chonlei** [comment]
Sounds like a good idea to me too!

**Comment by ben18785** [comment]
Closed by #1298
