### ISSUE TITLE
PyStan interface not seeded?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1304]
Got a fail on one run that I didn't see before:

```
 ======================================================================
FAIL: test_calling (test_interfaces_stan.TestStanLogPDF)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pints/pints/pints/tests/test_interfaces_stan.py", line 110, in test_calling
    self.assertAlmostEqual(stanmodel(x), -0.8181471805599453)
AssertionError: -2.0 != -0.8181471805599453 within 7 places
```

**Comment by ben18785** [comment]
Mmm, there's nothing stochastic here, so not to do with seed. Do you know which of the Python versions failed this test? I wonder whether there's a bug in one Pystan version.

**Comment by MichaelClerx** [comment]
https://github.com/pints-team/pints/runs/2013404385?check_suite_focus=true

Re-running without changes to pystan interface fixed it. And it had already worked before too.

**Comment by MichaelClerx** [comment]
Looks like this line takes a seed:

```
            stanfit = sm.sampling(data=stan_data, iter=1, chains=1,
                                  verbose=False, refresh=0,
                                  control={'adapt_engaged': False})
```
and here
```
        stanfit = self._compiled_stan.sampling(
            data=stan_data, iter=1, chains=1,
            verbose=False, refresh=0,
            control={'adapt_engaged': False})
```

you could generate a random seed from numpy there and pass that in, that would let users seed the StanLogPdf by seeding numpy

**Comment by MichaelClerx** [comment]
It happened again:

https://github.com/pints-team/pints/runs/2014187440?check_suite_focus=true

**Comment by ben18785** [comment]
Bizarre. This seems like a bug in Pystan for this Python version...

**Comment by MichaelClerx** [comment]
Not sure how much we can read into the version it's happening in. It cancels the unit tests of other versions once 3.5 has errored, so it's possible that 3.5 (a) is faster than 2.7 and (b) gets started before 3.6, 7, etc.

**Comment by MichaelClerx** [comment]
I've run the test three times in Python 3.9, stored the output, and then got rid of some obvious differences by replacing generated hashes in the output with "[hash]"

You can diff the files to see that there is definitely some stochasticity in there, presumably something to do with choosing initial values

Starting at lines 4452 in 1.txt
```
# Test values and sensitivities

Gradient evaluation took 2e-06 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.02 seconds.
Adjust your expectations accordingly!



 Elapsed Time: 0 seconds (Warm-up)
               0.000129 seconds (Sampling)
               0.000129 seconds (Total)

Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception: normal_lpdf: Scale parameter is -3.11485, but must be > 0!  (in 'unknown file name' at line 13)

If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.

WARNING:pystan:n_eff / iter below 0.001 indicates that the effective sample size has likely been overestimated
WARNING:pystan:Rhat above 1.1 or below 0.9 indicates that the chains very likely have not mixed
WARNING:pystan:1 of 1 iterations ended with a divergence (100 %).
WARNING:pystan:Try running with adapt_delta larger than 0.8 to remove the divergences.
/home/michael/dev/pints/venv/lib64/python3.9/site-packages/pystan/diagnostics.py:217: RuntimeWarning: invalid value encountered in true_divide
  e_bfmi = numer / denom
# Test change of data

Gradient evaluation took 2e-06 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.02 seconds.
Adjust your expectations accordingly!



 Elapsed Time: 1e-06 seconds (Warm-up)
               1.3e-05 seconds (Sampling)
               1.4e-05 seconds (Total)

WARNING:pystan:n_eff / iter below 0.001 indicates that the effective sample size has likely been overestimated
WARNING:pystan:Rhat above 1.1 or below 0.9 indicates that the chains very likely have not mixed
WARNING:pystan:1 of 1 iterations ended with a divergence (100 %).
WARNING:pystan:Try running with adapt_delta larger than 0.8 to remove the divergences.
# Test negative inf is returned
```
and in 2.txt
```
# Test values and sensitivities
Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Scale parameter is -0.296462, but must be > 0!  (in 'unknown file name' at line 13)


Gradient evaluation took 3e-06 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.03 seconds.
Adjust your expectations accordingly!



 Elapsed Time: 0 seconds (Warm-up)
               2e-05 seconds (Sampling)
               2e-05 seconds (Total)

WARNING:pystan:n_eff / iter below 0.001 indicates that the effective sample size has likely been overestimated
WARNING:pystan:Rhat above 1.1 or below 0.9 indicates that the chains very likely have not mixed
WARNING:pystan:1 of 1 iterations ended with a divergence (100 %).
WARNING:pystan:Try running with adapt_delta larger than 0.8 to remove the divergences.
/home/michael/dev/pints/venv/lib64/python3.9/site-packages/pystan/diagnostics.py:217: RuntimeWarning: invalid value encountered in true_divide
  e_bfmi = numer / denom
# Test change of data
Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Scale parameter is -0.499589, but must be > 0!  (in 'unknown file name' at line 13)

Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Scale parameter is -1.89468, but must be > 0!  (in 'unknown file name' at line 13)

Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Scale parameter is -0.667683, but must be > 0!  (in 'unknown file name' at line 13)

Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Scale parameter is -1.66608, but must be > 0!  (in 'unknown file name' at line 13)


Gradient evaluation took 2e-06 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.02 seconds.
Adjust your expectations accordingly!



 Elapsed Time: 0 seconds (Warm-up)
               0.000597 seconds (Sampling)
               0.000597 seconds (Total)

WARNING:pystan:n_eff / iter below 0.001 indicates that the effective sample size has likely been overestimated
WARNING:pystan:Rhat above 1.1 or below 0.9 indicates that the chains very likely have not mixed
# Test negative inf is returned
```

[1.txt](https://github.com/pints-team/pints/files/6070001/1.txt)
[2.txt](https://github.com/pints-team/pints/files/6070002/2.txt)
[3.txt](https://github.com/pints-team/pints/files/6070004/3.txt)

**Comment by MichaelClerx** [comment]
Here's a windows fail on Python 3.8:

https://github.com/pints-team/pints/runs/2014741625?check_suite_focus=true

**Comment by MichaelClerx** [comment]
☝🏻 @ben18785 note that there's still stochasticity in the test, even with Python 3.9

Any chance that fixing this would make 3.5 act predictably?

**Comment by ben18785** [comment]
Yep, probs. I can give setting a seed a go.

**Comment by MichaelClerx** [comment]
Managed to recreate it locally with python 3.5, but only on the 27th repeat. So bit less sure it's python 3.5 again 😅 
Will try seeding with increasing ints now, see if that makes it replicable

**Comment by MichaelClerx** [comment]
Is it a dict order thing? Dicts are ordered in 3.6, not in 3.5 or earlier

**Comment by MichaelClerx** [comment]
@ben I'm not quite sure what all the dict / list transitions in the stan interface do, but it looks to me like the might rely on the dict preserving the order of its keys?

**Comment by ben18785** [comment]
Thanks Michael. Yes, that's interesting. I just tried the following:

stanmodel([1, 2]) = -0.8181471805599453 (as desired)
stanmodel([2, 1]) = -2 (as happens in the failed tests)

So I think you may be right about the order of parameters mattering. I
tried rerunning the model with Python 3.7 (which is what I have installed)
100 times and I didn't once get "-2". Any chance you could try to replicate
the error and, in that case, pickle the "stanmodel" so that we could
interrogate it?

**Comment by MichaelClerx** [comment]
Shall I just fix it instead?

**Comment by MichaelClerx** [comment]
I'm pretty convinced this is what's happening, given that we now know it can happen, and that we see what you'd expect if it does happen :D
(Even with seeding, I couldn't make it happen consistently, has to be some kind of accidental non-determinedness!)

**Comment by ben18785** [comment]
Happy for you to fix it. As you say, we need to do something more than just
seeding it...

**Comment by MichaelClerx** [comment]
I'm a bit puzzled at what the interface code does to the parameter vector

It starts off as a flat vector, then gets manipulated in several ways, then gets passed back to pints as a flat vector ?
So all of this is just reordering them?

**Comment by MichaelClerx** [comment]
OK as far as I can make out the code turns a flat vector into a nested vector, then flattens it again, to end up with what it started with

(I've also realised that in python 3.5 and 3.6 dicts do preserve order, but this is unofficial so you're not supposed to count on it. In 2.7 they certainly don't preserve order, and I think _prepare_values could fail here. Not sure why we get fails in 3.5 then...)

**Comment by MichaelClerx** [comment]
I can't find the API docs for the C++ base or the python implementation anywhere (there's a readthedocs, but for the upcoming 3 version, not the pypi 2.x version)

**Comment by MichaelClerx** [comment]
So this is the best ref I have on (presumed) parameter order: https://github.com/stan-dev/stan/blob/develop/src/stan/model/model_base.hpp#L93-L134

**Comment by MichaelClerx** [comment]
I'm not stanning stan right now

**Comment by ben18785** [comment]
So I've now had a relook at I think the dictionary stuff is actually
residual from when I had transformations in there! Sorry. I was sure I'd
removed it at some point. I need to remove them now, I think. Just running
the notebook to check that this is the case.

I don't think this will solve the issue with the order of the parameters
reordering. I think that a user will have to check the order that the
Pystan model returns these with .unconstrained_param_names(), then pass the
parameters in this order accordingly.

**Comment by MichaelClerx** [comment]
Yeah so it looks like all the dict stuff could just be removed at the moment?

**Comment by ben18785** [comment]
Let me check

**Comment by MichaelClerx** [comment]
I've done an annotated version here, I think it's this line that's causing trouble: https://github.com/pints-team/pints/pull/1310/files#diff-a4edf44c36231475fcb0ac1b584b55369aa9d3a21a25e4f873c22acc2507c831R353

**Comment by MichaelClerx** [comment]
```
        vals = dict.values()
        # Vals is now an arbitrarily ordered list of values from the dictionary
        b = []
        for ele in vals:
```

**Comment by ben18785** [comment]
Thanks. I've now removed the dictionary stuff altogether in this PR:
https://github.com/pints-team/pints/pull/1309

**Comment by ben18785** [comment]
Sorry for the trouble here by the way! I really swear I'd removed this
dictionary stuff.

**Comment by MichaelClerx** [comment]
That's ok I did some really shoddy PR reviewing  😅
