### ISSUE TITLE
PyStan interface test raises 9000 lines of warnings

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1305]
This makes the unit test output rather difficult to read

**Comment by MichaelClerx** [comment]
I can try and suppress these?

**Comment by ben18785** [comment]
Happy for you to suppress these: they're just compiler warnings I think.

**Comment by MichaelClerx** [comment]
OK, the easy method (capturing python's stdout stream) doesn't work. So back to you!

**Comment by MichaelClerx** [comment]
OK I'm trying a dirtier version of capturing now, seems to work

**Comment by MichaelClerx** [comment]
Closed in #1306
