### ISSUE TITLE
Optimise performance of NUTS

### ISSUE THREAD

**Issue by DavAug** [pints-team/pints#1314]
The current implementation of the `pints.NoUTurnMCMC` is at least 10 times slower than `pints.HamiltonianMCMC` on a problem I tried (5 dimensional parameter space, default settings), which probably renders this implementation not very practical for most problems. 

I believe we can speed up NUTS to almost c-like speed by compiling the internal updating methods (or even the entire helper class) of the sampler with numba. I am not sure whether this will allow us to still use the "yield" API, but maybe something worth sacrificing for significant speed ups?

**Comment by ben18785** [comment]
Hi David. Did you use parameter transforms for NUTS? We’ve found that NUTS runs much faster when using them (which is what Stan does)...

**Comment by DavAug** [comment]
> Hi David. Did you use parameter transforms for NUTS? We’ve found that NUTS runs much faster when using them (which is what Stan does)...
> […](#)

Hi Ben :) Yep I applied the usual log-transforms. Do you remember which transforms you used?

**Comment by ben18785** [comment]
Interesting. I’m not sure what your priors are but if they’re uniform you could try the boundary transformation? Do you know how many steps the NUTS algorithm is taking?

**Comment by DavAug** [comment]
I am using Gaussian priors truncated at 0. The boundary at zero should not be a problem because of the log-transforms no? I am able to infer the posteriors through with both, the HMC and NUTS, it's just that NUTS is quite slow. Do you think transformations could yield any speed up? I was thinking that this more because of the more involved proposal computation in NUTS? I mean even the example notebook with a 2d Gaussian, NUTS is almost 5 times slower: https://github.com/pints-team/pints/blob/master/examples/sampling/nuts-mcmc.ipynb.

**Comment by ben18785** [comment]
Yep, the boundary at zero should be fine. When you say “slower”, it’d be good to know if this was in terms of effective samples per second and/or ESS per unit time...?

**Comment by DavAug** [comment]
I'll try to run NUTS for a little while to give you a better estimate of the ESS but just to give you an idea:
Running 2000 iterations of HMC takes about the same time as running 20 iterations of NUTS:
![Screen Shot 2021-03-08 at 11 33 50 AM](https://user-images.githubusercontent.com/20031982/110315770-ffd2d400-8009-11eb-9aa4-6756e07f6f29.png)

**Comment by ben18785** [comment]
Ha, interesting! Yes, that may be fairly condemning. Your example may be a
good one for the paper as it illustrates how we can easily switch between
samplers in PINTS. Perhaps bring it up tomorrow in the meeting?

**Comment by DavAug** [comment]
Even if NUTS has a good ESS per iteration ratio, the adaption just takes too long (the minimal number of adaption steps are currently 150, which translates on 8 cores in parallel to roughly 20 minutes for just the warm-up). That's crazy for 5 dimensions :D

**Comment by DavAug** [comment]
> Ha, interesting! Yes, that may be fairly condemning. Your example may be a good one for the paper as it illustrates how we can easily switch between samplers in PINTS. Perhaps bring it up tomorrow in the meeting?
> […](#)

Exactly! The same problem with ACMC runs in 2 mins to full convergence!

**Comment by MichaelClerx** [comment]
@DavAug @ben18785 Do you feel this is an issue with PINTS that needs resolving, or can we close/move this discussion?

**Comment by DavAug** [comment]
Yes, happy to close this!
