### ISSUE TITLE
To dos: redux

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#1315]
1. Functional testing! Fergus and David?
2. Automatic MCMC initialisation: Ben
3. MultiNest: Ben
4. Sort bug in populationMCMC: Michael
5. Provide some way for model comparison: Rebecca, David and Richard?
6. Clean up the example notebooks / add some more detail in places: ALL
7. Sort a few other minor bugs: ALL
8. Try to merge some of the existing slice sampling PRs: Ben + others

Fergus' rule was "Anything that's done at the time of planned publication goes in" was agreed on.

**Comment by ben18785** [comment]
Haha. Not point 4?

**Comment by MichaelClerx** [comment]
As much as possible, but no method or bug is a deal breaker for me :-)
Thanks again for the overview earlier! Really made me think that we have enough to get started.

**Comment by MichaelClerx** [comment]
Then again, we can do a list of things we really want fixed/added so that we can present PINTS in public without shame 😄 😄 😄
So let's do a short list but agree once that's done it's set in stone, so nothing more can be added?

**Comment by ben18785** [comment]
Yep, that's fine with me. Shall we amend the current PINTS project then?

**Comment by MichaelClerx** [comment]
Yes please

**Comment by alisterde** [comment]
Thanks @MichaelClerx and @ben18785 I'd really like to get #1083 and #1160 done so that we have some 1st order sensitivity optimisers, but as you know I'm working on those at the moment!

**Comment by MichaelClerx** [comment]
@ben18785 can this one be closed? I don't think we've done all of these, but priorities have shifted perhaps?
