### ISSUE TITLE
Neal's Funnel derivative bug

### ISSUE THREAD

**Issue by phumtutum** [pints-team/pints#1316]
Neal's Funnel log pdf function has the derivative returned in evaluateS1 as a python list rather than a numpy array. This is a problem because when running NUTS on the log pdf, it cannot multiply a float by the list and gives an error. More specifically the error happens on the leapfrog step: r_new = r + 0.5 * epsilon * grad_L.

**Comment by ben18785** [comment]
Closed by #1317
