### ISSUE TITLE
Change Optimiser/MCMC objects to work with 'ask-and-tell' interface

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#132]
In that case, users could do something like this:

```
mcmc = ...
while True:
    result = mcmc.iterate()
    if result.is_finished():
        break
    if every 100th iteration:
        store to disk
    if every 10th iteration
        print diagnostics, current state etc.
```

This would allow users to set up arbitrarily complex search routines, including logging final results to disk, storing partial results on disk, stopping/restarting, showing as much output data as they like in whatever form they like, storing output data somewhere on a server in a way that websites or other clients can read it etc.

**Comment by MichaelClerx** [comment]
Copied from #185:

> I strongly believe all our methods should work like this:
> 
>    - We set up some object (MCMC class, Optimiser class)
>    - We set up a loop, from wherein
>        - we call an iterate() method, this advances us one step and then asks us to evaluate the model on some new points
>        - we do logging, debug output, talk to calling processes, check stopping criteria
>        - we evaluate the model (possibly parallelised on a CPU/GPU) and pass back the information

This would then have to be integrated with the result objects (#129 for MCMC/inference, #137 for optimisation)

**Comment by MichaelClerx** [comment]
Example for an optimiser:

    # Create optimiser object (with fresh internal state)
    opt = AReallyGoodOptimiser(function, boundaries, x0, sigma0)
    
    # Configure (this could be extensive)
    opt.set_setting1(0.5)
    opt.set_setting2(novell_heuristic(1,2,3))
    ...
    
    # Configure stopping criteria
    absolute_tolerance = 1e-6
    max_iterations_without_change = 50
    no_change_cutoff = 1e-12
    
    # Run optimisation
    halt = False
    while not halt:
        # Ask for point or points to evaluate
        x = opt.ask()
        
        # Evaluate points
        # This could be (GPU) parallelised
        fx = evaluate(x)
        
        # Perform the next iteration
        # This updates the optimiser's internal state
        opt.tell(x, fx)
        
        # Perform logging, debug output etc.
        print(x, fx)
        print(opt._some_internal_parameter_i_am_studying)
        file.write(x, fx, ...)
        network.send(x, fx, ...)
        progress_bar.update()
        
        # Check stopping criteria
        halt = halt or (criteria1)
        halt = halt or (criteria2)
        halt = halt or (criteria3)
        ...
    
    # Run a second optimisation
    # This resets the optimisers state, but doesn't affect the settings
    opt.reset(function, boundaries, x0, sigma0)
    
    # Run optimisation
    ...

This would be the "hard" interface, intended for people who want to use pints as a library inside some other project, who want to do some testing/debugging/benchmarking, etc.

We would then write a simpler method you would look like this:

    pints.minimise(pints.CMAES, function, boundaries, x0, sigma0)

or even

    pints.minimise(pints.CMAES, function, boundaries, x0, sigma0, very_important_param1, very_important_param2)

as long as we keep the number of very important parameters to an absolute minimum (I want to avoid the hideously long parameter lists you see e.g. in numpy's optimiser calls, or the difficult-to-document settings dictionaries in e.g. pycma)

Thoughts? @martinjrobins @ben18785 ? Would inference routines fit in a similar scheme?

**Comment by MichaelClerx** [comment]
It would also allow us to write cool wrapper functions e.g.

    p = pints.optimise_and_plot(pints.PSO, function, ...)

which could create plots of the particles travelling through (a low-dimensional representation of) the search space, and update them at each iteration

or things like a routine that stores in some particular format we like, or ones that send progress reports over a network, etc.

**Comment by martinjrobins** [comment]
Yup, love the flexibility of this. It would really help with the hierarchical sampling I'm doing. As long as this inteface would work with all the inference algorithms I'm for it.

**Comment by ben18785** [comment]
Sorry, being slow, what does "ask and tell" mean? Is the idea to have two
interfaces: one that is uncustomisable that runs samplers etc. in a default
manner, and another which can be much more easily customised/embedded in a
larger project? If so, think it's a good idea!

**Comment by MichaelClerx** [comment]
> Sorry, being slow, what does "ask and tell" mean?
It means that the optimiser stops after every iteration to ask you for the evaluation of your function (or logposterior) at selected points, and continues when you tell it.
CMA-ES uses it, for example, and some googling showed me scikit uses it too: https://scikit-optimize.github.io/notebooks/ask-and-tell.html

> Is the idea to have two interfaces: one that is uncustomisable that runs samplers etc. in a default manner, and another which can be much more easily customised/embedded in a larger project? If so, think it's a good idea!
Yes!

**Comment by ben18785** [comment]
Great! That ask and tell thing would be truly excellent for sampling! Could
it evaluate R-hat (convergence criterion) every X iterations? Then if
not-converged, continue?

**Comment by MichaelClerx** [comment]
That'd be something we could implement in the default method that used it, yes!

**Comment by ben18785** [comment]
Brilliant! That's one up on the other MCMC software.

**Comment by MichaelClerx** [comment]
Question: Examples I see floating around of similar interfaces use `ask()` to provide some set of points `x`, and then `tell(x, fx)` to update. Should we simplify this to `tell(fx)`? I can't imagine why you'd want to change the `x` values, or how you'd do that without messing up the optimiser's idea of the state space

**Comment by MichaelClerx** [comment]
Chatting to @sanmitraghosh and @martinjrobins I've decided to go to with `tell(fx)`

**Comment by ben18785** [comment]
Sounds good!

**Comment by MichaelClerx** [comment]
I'm trying to rewrite the adaptive MCMC algorithm so that it works roughly like this:

    class AdaptiveMethod:
        def ask() --> returns x
        deff tell(fx) --> called with f(x), return a new sample x* that is accepted for this iteration
    
    def run_mcmc():
        for i in range(4000):
            x = method.ask()
            fx = log_posterior(x)
            sample = method.tell(fx)

            if i > 2000:
                chain.append(sample)

The only issue is the current adaptive method performs X iterations without adaptation. Is this normal for adaptive methods? Or can they usually work without knowing which iteration they are on? @sanmitraghosh @ben18785 ?

**Comment by MichaelClerx** [comment]
- Differential evolution doesn't seem to have it.
- NestedEllipsoidSampler has `rejection_samples`, is that the same thing (sort of)?
- NestedRejectionSampler doesn't seem to have any

What I'm hoping is that we can define some interfaces so that most of the boring stuff (printing, storing samples, thinning etc.) is handled outside of the individual methods

**Comment by sanmitraghosh** [comment]
Theoretically we should start adapting from the start, however it is we start adapting after a discard period of 100-500 samples. Also I have seen (I do that some times) adapting every 10/20 samples. These are some hacks/ tricks people use. The initial discarding is widely used.

**Comment by sanmitraghosh** [comment]
I think your tell method should always return a sample irrespective of its acceptance, return the same x when rejected.
Also, I think the tell method is the MH step which is used in various samplers. Thus I believe its better to use  it as a separate class altogether. No point in repeating the same block of code everywhere.

**Comment by sanmitraghosh** [comment]
I think a general MCMC (not population or SMC) algo has 3 things 1) an adaptation 2) a proposal 3) a MH step. We can make a base class: Proposal (this is the ask) which combines 1) and 2) and is inherited by different samplers within the MCMC family. We also make another class: Stepper(this is the tell, MH step). Now we can combine these to create ask-tell. Just a suggestion.

**Comment by MichaelClerx** [comment]
> I think your tell method should always return a sample irrespective of its acceptance, return the same x when rejected.

Thanks! That's what I meant (but not what I wrote). Have updated my example

**Comment by MichaelClerx** [comment]
Got a bit further now. The adaptation uses a line

```
gamma = (i - self._adaptation + 2) ** -0.6
```

where `i` is the current iteration and `self._adaptation` is the number of iterations before adaptation should set in.
This seems to imply the method does need some notion of the iteration count :-/

**Comment by sanmitraghosh** [comment]
For an adaptive sampler the gamma acts as a learning rate/ step-size parameter. It should be set as a decreasing sequence for assuring ergodicity. Decreasing sequence as in when i--->inf, gamma--->0.

However, these sequences are generally designed/derived to give a certain rate of convergence. I suggest we can have a chat with Remi and tell him what we want to change.

**Comment by MichaelClerx** [comment]
Thanks! I'll just go with an internal counter for now so that we match the old algorithm closely

**Comment by mirams** [comment]
For people still wondering what is going on, I stumbled on this example today: https://github.com/beniz/libcmaes/wiki/Defining-a-custom-algorithm-based-on-libcmaes-primitives
