### ISSUE TITLE
Add set_hyperparameters method for PopulationMCMC

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#1327]
I think, to make things simple for running benchmarking / functional tests, we should:

1. Add another argument to `set_temperature_schedule` that allows setting of a schedule on the log scale. But would adding another option to an `set_hyperparameter_*` method complicate #1320 ?
2. Allow only an integer to be passed to set the number of gradations
3. Include the `initial_phase_iterations` and the `eta` parameters of the underlying adaptive covariance method as other hyperparameters (looking at adaptive covariance, however, `initial_phase_iterations` doesn't seem to be given as a hyperparameter, but perhaps it should be?)

**Comment by MichaelClerx** [comment]
For now, I've only used `set_temperature_schedule` as is.

1. I think point 1 is part of #409 . So whoever does that can have a look at this?
2. This is already possible
3. This should probably be handled whenever we allow different internal methods. Have made a ticket for that here: #1382

**Comment by ben18785** [comment]
Thanks @MichaelClerx -- agree with all your comments here.
