### ISSUE TITLE
Add evaluateS1 method for HighDimensionalGaussianLogPDF

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#1328]
Why? Because it'll be very useful for functionally testing gradient-based methods. I think this can just be copied straight over from that for `GaussianLogPDF`.

Whilst we're at it, it might be good to update the docstrings as they're not very informative.

**Comment by ben18785** [comment]
Also, the `sigma_inv` calculation in the method in `GaussianLogPDF` can be cached, which can be addressed in same PR, I reckon.

**Comment by ben18785** [comment]
Also, add note about result being from chapter 2 of matrix cookbook (plus maybe https://stats.stackexchange.com/questions/27436/how-to-take-derivative-of-multivariate-normal-density).

**Comment by MichaelClerx** [comment]
Fixed in #1329
