### ISSUE TITLE
Update stan interface to use pystan 3

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#1333]
Think this is because Pystan has [recently been updated](https://pystan.readthedocs.io/en/latest/upgrading.html) and now is imported with `import stan`.

I think it [may](https://pystan.readthedocs.io/en/latest/installation.html) also be installed via `python3 -m pip install pystan`.

**Comment by ben18785** [comment]
Also looks like this was a breaking release in terms of [how models are compiled](https://pystan.readthedocs.io/en/latest/upgrading.html#upgrading).

**Comment by ben18785** [comment]
It also looks like it only works on Python>=3.7... @MichaelClerx @martinjrobins what do you think is best here? Keep this in PINTS or move to a separate repo?

**Comment by MichaelClerx** [comment]
I'm happy to keep it in and only test on newer pythons (see nuts for an example)

The minimum Python 3 we can test on at the moment is Python 3.5. It probably won't be too long before that becomes 3.6...

**Comment by MichaelClerx** [comment]
No windows support either I see

**Comment by MichaelClerx** [comment]
@ben18785 We urgently need to update to pystan 3. The 2.x version is no longer supported (https://github.com/stan-dev/pystan/issues/339) meaning that we can't test PINTS on Python 3.10 at the moment. #1434

**Comment by MichaelClerx** [comment]
Full to-do:

- [ ] Change the testing so that 3.6 and older no longer run any pystan tests (because pystan 3.x is not available on python 3.6)
- [ ] Update the stan interface to use pystan 3.x

**Comment by ahartikainen** [comment]
Hey, just wanted to help the transition.

What interfaces do you need? 

Only sampling or also manual logp calculations?

**Comment by ben18785** [comment]
Thanks @ahartikainen -- that's a very kind offer.

In PINTS, we have used Pystan to allow models to be built using Stan code but sampled from using PINTS' sampling algorithms. To do so, we use the `log_prob` and `grad_log_prob` functions (in both cases with `adjust_transform=True`) from Pystan 2.

The code that implements this is [here](https://github.com/pints-team/pints/blob/master/pints/interfaces/stan/_stan.py). As you'll see, at the moment, we do the following:

- at instantiation of our `StanLogPDF` object, we pass the stan code and use this to compile a Pystan `StanModel` object
- we then can switch between datasets using the `update_data` method, which runs sampling for one iteration and returns a Pystan object
- this object is then used to calculate the log probability and the gradient in this through Pystan's convenience functions

Does that make sense?

Based on the [Pystan documentation](https://pystan.readthedocs.io/en/latest/upgrading.html#upgrading) comparing version 2 and 3, it looks like we would always have to compile a Stan model with a dataset?

**Comment by ahartikainen** [comment]
Ok, then you are better with PyStan approach (CmdStan does not support logp calculations yet).

You need to build posterior each time, but that model is cached in httpstan so we are talking about <1s.

If pystan interface is too slow (which is probably the case) you could build model with PyStan and then tap into httpstan interface bypassing pystan-httpstan communication.

Here is one example how to do it

https://discourse.mc-stan.org/t/speed-of-evaluating-gradients-of-log-probabilities-in-pystan-2-x-vs-3/22303/10

**Comment by ben18785** [comment]
Thanks very much @ahartikainen -- that all makes sense, I think.

**Comment by ahartikainen** [comment]
Hi, apparently we currently don't have that functionality.

Where do you need the number of parameters? (Using dims is the correct way to do this)

I think something similar as in https://github.com/arviz-devs/arviz/blob/5af74712950c99d486cc0f62db66537670e3bfcc/arviz/data/base.py#L444 should work for accessing parameter names defined in parameters block.

**Comment by MichaelClerx** [comment]
Thanks @ahartikainen ! We need to number of parameters when sampling, just to check that it's the same as the initial guesses etc. The parameter names are used when generating user output.

@ben18785 would something like this be enough, or do we need to support multiple indices (matrix variables?):
```
#!/usr/bin/env python3
import httpstan
import stan

data = {
    'J': 8,
    'y': [28, 8, -3, 7, -1, 1, 18, 12],
    'sigma': [15, 10, 16, 11, 9, 11, 10, 18],
}

code="""
data {
  int<lower=0> J;
  real y[J];
  real<lower=0> sigma[J];
}

parameters {
  real mu;
  real<lower=0> tau;
  real theta[J];
}

model {
  mu ~ normal(0, 5);
  tau ~ cauchy(0, 5);
  theta ~ normal(mu, tau);
  y ~ normal(theta, sigma);
}
"""

# Build stan model
posterior = stan.build(code, data=data)

# Use httpstan to get access to the compiled module
module = httpstan.models.import_services_extension_module(
    posterior.model_name)

print(dir(posterior))
print(dir(module))

names = []
for name, dims in zip(posterior.param_names, posterior.dims):
    if dims:
        assert len(dims) == 1
        names.extend(name + '_' + str(i) for i in range(dims[0]))
    else:
        names.append(name)

print(names)
```
(I'd prefer getting the info from stan's interpretation of the code, instead of interpreting it ourselves a 2nd time)

**Comment by MichaelClerx** [comment]
Thanks again @ahartikainen , with your help we have now managed to resolve these issues and upgrade to PyStan 3. If there is ever a drive within the stan dev community to add more compiled model introspection methods (like it seems you need in arviz too) please keep us in mind! We are happy to help by e.g. sharing our reasons for requiring this functionality
