### ISSUE TITLE
Check for bugs in relativistic MCMC

### ISSUE THREAD

**Issue by rcw5890** [pints-team/pints#1348]
While writing a functional testing notebook for this sampler, I noticed very poor performance on the correlated Gaussian even with a large number of iterations, indicating a possible bug.

- [x] Check equations for relativistic mass and kinetic energy.
- [x] Check the distribution for momentum. In the paper they show that it has a hyperbolic distribution, while we are using the multivariate normal from standard Hamiltonian.

**Comment by ben18785** [comment]
Thanks @rcw5890 -- that looks like a good spot with the proposal distribution, I must have missed it.
