### ISSUE TITLE
Stop numpy (and others) from using threads inside multiprocessing worker processes

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1356]
Ran into a weird issue yesterday, and took me absolutely forever too find it, but here it is:

Numpy sometimes uses multi-threading (in a C library, so not limited by the GIL), causing it to address several CPU cores at once. Usually we'd say this is a good (great?) thing, but if you're already trying to implement multiprocessing it can cause a serious slowdown.

The code below demonstrates the issue:
```
#!/usr/bin/env python3
# Numpy parallelisation
np_par = False
# Pints parallelisation
mc_par = False

if not np_par:
    # Disable numpy parallelisation (on by default) by setting some environment variables within this process
    import os
    os.environ["OMP_NUM_THREADS"] = '1'
    os.environ["OPENBLAS_NUM_THREADS"] = '1'
    os.environ["MKL_NUM_THREADS"] = '1'
    os.environ["VECLIB_MAXIMUM_THREADS"] = '1'
    os.environ["NUMEXPR_NUM_THREADS"] = '1'

import numpy as np
import pints

def essp(x):
    x = (x - np.mean(x)) / (np.std(x) * np.sqrt(len(x)))
    rho = np.correlate(x, x, mode='full')
    rho = rho[int(rho.size / 2):]
    return len(x) / (1 + 2 * np.sum(rho[0]))

def test(n_iterations=None):
    chains = np.random.random((1, 60000, 2))
    n_chains, n_samples, n_parameters = chains.shape
    ess = np.empty(shape=(n_chains, n_parameters))
    for chain_id, chain in enumerate(chains):
        ess[chain_id] = [essp(chain[:, i]) for i in range(0, n_parameters)]

def run():
    iterations = [30000]*10
    t = pints.Timer()
    pints.evaluate(test, iterations, mc_par)
    print(f'Completed in {t.format()}')

if __name__ == '__main__':
    run()
```

On my system, running this code fully sequentially takes 17.8s

Enabling only numpy parallelisation, this drops down to 8.5s (a speed-up of 2.09x)

Enabling only pints parallelisation, this drops down to 4.2s (a speed-up of 4.24x)

Enabling both types of parallelisation, the fans switch on, the lights go down, and after five minutes I get bored and hit Ctrl-C. This means it's _at least_ 17x slower than fully sequential, and possibly even deadlocked.

**Comment by MichaelClerx** [comment]
A second issue this causes it that the number of cores passed to our parallelisation routines becomes a lower bound. I think I've seen this issue in action last year when @chonlei 's code was using more cores than allocated, but we couldn't figure out why.

On shared systems you often want to limit the number of cores you use, so it's really necessary that the number of cores we tell pints to limit itself to is actually applied.

**Comment by MichaelClerx** [comment]
How to fix?

The script above fixes numpy's number of used cores by setting the environment variables with `os.environ` (as suggested [here](https://stackoverflow.com/questions/30791550/limit-number-of-threads-in-numpy)). This is nice, but has two drawbacks: 1. We need to know which variables (and keep the list up to date). 2. We need to set these for the worker processes only. See for example [here](https://stackoverflow.com/questions/2231227/python-subprocess-popen-with-a-modified-environment)

Some libraries numpy uses can be configured during runtime, but not all of them, and the exact libraries it uses vary from system to system, so that's not an option apparently.

There's a numpy [issue with a massive discussion](https://github.com/numpy/numpy/issues/11826) that ends in the resolution that the [`threadpoolctl`](https://github.com/joblib/threadpoolctl) package should be used to configure this.
I don't understand why hey didn't just include this in numpy, but seems the advised solution is to use `threadpoolctl`.

So what I suggest is:

- Add `threadpoolctl` as a dependency
- Add a `with threadpoolctl.threadpool_limits(1):` into our Worker class.
- Add some mechanism to disable this.

The mechanism to disable it could be something like `pints.RESTRICT_NUMPY_THREADING_WHEN_MULTIPROCESSING=False`, or it could be an argument we pass into the `evaluate()` method, the `ParallelEvaluator`, and maybe even all controllers.
Suggestions on that are very welcome! (See also related issue #1354 )

**Comment by MichaelClerx** [comment]
We could also _not_ have a mechanism to disable this, as most users won't know to do this, possibly won't want to know?

**Comment by MichaelClerx** [comment]
Thoughts very welcome on this from all @pints-team/devs , especially people who might have seen this before e.g. @fcooper8472 @martinjrobins

**Comment by MauriceHendrix** [comment]
> How to fix?
> 
> The script above fixes numpy's number of used cores by setting the environment variables with `os.environ` (as suggested [here](https://stackoverflow.com/questions/30791550/limit-number-of-threads-in-numpy)). This is nice, but has two drawbacks: 1. We need to know which variables (and keep the list up to date). 2. We need to set these for the worker processes only. See for example [here](https://stackoverflow.com/questions/2231227/python-subprocess-popen-with-a-modified-environment)
> 
> Some libraries numpy uses can be configured during runtime, but not all of them, and the exact libraries it uses vary from system to system, so that's not an option apparently.
> 
> There's a numpy [issue with a massive discussion](https://github.com/numpy/numpy/issues/11826) that ends in the resolution that the [`threadpoolctl`](https://github.com/joblib/threadpoolctl) package should be used to configure this.
> I don't understand why hey didn't just include this in numpy, but seems the advised solution is to use `threadpoolctl`.
> 
> So what I suggest is:
> 
> * Add `threadpoolctl` as a dependency
> * Add a `with threadpoolctl.threadpool_limits(1):` into our Worker class.
> * Add some mechanism to disable or tweak this PINTS default setting.
> 
> The mechanism to disable it could be something like `pints.RESTRICT_NUMPY_THREADING_WHEN_MULTIPROCESSING=False`, or it could be an argument we pass into the `evaluate()` method, the `ParallelEvaluator`, and maybe even all controllers.
> Suggestions on that are very welcome! (See also related issue #1354 )

`threadpoolctl` suggestion looks sensible .. I think. The solution using environment variables (`os.environ`) feels like it may not be very robust under the various library versions and OS environments etc.

I wonder if you'd want to provide an easy setting along the lines of your `np_par`  / `mc_par`  still though maybe with default numpy parallel off and pints on, rather than telling people to use `threadpoolctl` tgemselves?

**Comment by MichaelClerx** [comment]
Added difficulty: `threadpoolctl` is not available for Python 2.

Can work around it, but can also disable parallelisation on older Python 2's (like NUTS). Good incentive for people to upgrade maybe, @fcooper8472 ? Or even ditch Python 2 altogether now...

**Comment by fcooper8472** [comment]
I'm personally happy to ditch Python 2 altogether.  We're now 18 months past end-of-life and I've not yet met a cluster or supercomputer that didn't have Python 3.x.

We should definitely have a firm policy on this.  E.g. we support all versions currently "still maintained", plus the most recent that is no longer supported.  This would currently be 3.5+, and we would drop 3.5 after December, when 3.6 reaches end-of-life.  Just an initial thought.

Shall we put this on the agenda for the next pints meeting?

**Comment by mirams** [comment]
If even lumbering old Chaste has dropped python2 I think agile young pints should be fine to follow suit!
