### ISSUE TITLE
Ubuntu support: Add 18! Drop 16?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1359]
We've currently set up OS testing on ubuntu 16 and ubuntu "latest". 

- [Recently, latest has become 20 so that 18 is no longer tested](https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04/)
- [16 is EOL since april 2021 and will be removed from github actions in september 2021](https://github.com/actions/virtual-environments/issues/3287)

So, we should definitely add 18 to testing. But should we remove 16 too, or wait till september?

**Comment by MichaelClerx** [comment]
Thoughts @fcooper8472 @martinjrobins ?

Anyone still using 16 @pints-team/devs ?

**Comment by fcooper8472** [comment]
We shouldn't still be using 16.04, no.  Interestingly we're currently testing on:

```
ubuntu-16.04, macos-latest, windows-latest
```

I think this should probably change to:

```
ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11, windows-latest
```

**Comment by MichaelClerx** [comment]
I think we left out ubuntu-latest on purpose, because it's already covered by the python-versions test (and the coverage test, come to think of it)
