### ISSUE TITLE
Add an OptimisationResult object

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#137]
And use for

- [ ] Base type: scores and parameter sets
- [ ] CMA-ES: Extra info...?
- [ ] xNES
- [ ] SNES
- [ ] PSO

Other things we might include in the base type:
- iterations
- unchanged iterations (should this be a global thing?)??
- evaluations
- finished flag (see #132)
- stopping criterion (string? enum?)

**Comment by MichaelClerx** [comment]
See also #129

**Comment by mirams** [comment]
Number of simulator 'evaluations' would be a nice thing to keep track of.

**Comment by MichaelClerx** [comment]
Added it to the list! In order to parallelise things we do the evaluations ourselves anyway. CMA-ES for example, has an "ask-and-tell interface" that works like this:

```
while cma.not_quite_finished_yet():
    samples = cma.ask()
    scores = evaluate(samples)
    cma.tell(scores)
```

I imagine other methods will have a similar interface? But yeah if there's no other option we can always add a wrapper around the function passed to the optimiser :-)

**Comment by MichaelClerx** [comment]
Don't need this anymore with proposals for #132 (except for number of evaluations, for which I'll make a ticket)
