### ISSUE TITLE
Better name for "functional tests" ?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1381]
There's already a thing called [functional testing](https://en.wikipedia.org/wiki/Functional_testing) which is "testing if software meets specifications", without knowing the details of how the thing works.

Not sure this is what we do?

"Statistical tests" feels better, but there's already a thing called that too, and we might well want to have a couple of those in PINTS one day.

I think what we're doing right now is [benchmarking](https://en.wikipedia.org/wiki/Benchmark_(computing))

> In computing, a benchmark is the act of running a computer program, a set of programs, or other operations, in order to assess the relative performance of an object, normally by running a number of standard tests and trials against it.[1] 

where "performance" does not need to mean speed. And we're certainly running "standard tests and trials"

Any thoughts, while it's still easy to change?

**Comment by DavAug** [comment]
Hmm what all our tests boil down to is testing the convergence of methods isn’t it? So if we can’t use functional testing or statistical testing, maybe we just go for the narrower convergence testing?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chonlei** [comment]
Convergence testing sounds a bit like the [convergence tests in mathematics](https://en.wikipedia.org/wiki/Convergence_tests).

I wanted to suggest 'performance tests', but then there is [performance testing](https://en.wikipedia.org/wiki/Software_performance_testing):
> In software quality assurance, performance testing is in general a testing practice performed to determine how a system performs in terms of responsiveness and stability under a particular workload. It can also serve to investigate, measure, validate or verify other quality attributes of the system, such as scalability, reliability and resource usage.

**Comment by MichaelClerx** [comment]
Yeah, most of the definitions seem to have very clear pass/fail criteria, whereas we're just seeing if they behave as well as we'd expect such a method to behave 🤷🏻

**Comment by MichaelClerx** [comment]
Also, to be clear, this isn't about a name for the notebooks (which we've been calling "pre-merge tests"?), but about naming the thing where we run some tests (based on the notebooks) on a regular basis, log the performance, and look for changepoints

**Comment by ben18785** [comment]
Changepoint tests? Isn't that what they all do?

**Comment by MichaelClerx** [comment]
Meeting: decided on changepoint testing
