### ISSUE TITLE
Workflow error?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1398]
Seeing an error in the workflow on a draft PR:  https://github.com/pints-team/pints/actions/runs/1162398706/workflow

```
    if: github.event.pull_request.draft == false
    name: Style
    runs-on: ubuntu-latest

    # Skip job if it's a draft PR
    if: github.event.pull_request.draft == false
```

Guess we should combine the two `if`s into a single statement?

@fcooper8472 ?

**Comment by fcooper8472** [comment]
Weird: looks like it's just a duplicate line?

Maybe just delete the first if and keep the one with the explanatory comment?

**Comment by MichaelClerx** [comment]
Good spot! Hmmm some merge issue then. Only happens in the func test branch!
