### ISSUE TITLE
Implement Kylie's models

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#14]
- [x] Aslanidi 2009
- [x] Clancy 2001
- [x] Courtemanche 1998
- [x] Di Veroli 2013 a
- [x] Di Veroli 2013 b
- [x] Fink 2008
- [x] Fox 2002
- [x] Grandi 2010
- [x] Hund 2004
- [x] Inada 2009
- [ ] Kurata 2002
- [ ] Lindblad 1996
- [ ] Lin 1996
- [ ] Lu 2001
- [ ] Matsuoka 2003
- [ ] Mazhari 2001
- [ ] Noble 1998
- [ ] Nygren 1998
- [ ] Oehmen 2002
- [ ] O'Hara 2011
- [ ] Priebe 1998
- [ ] Ramirez 2000
- [ ] Seemann 2003
- [ ] Severi 2012
- [ ] Shannon 2004
- [ ] Ten Tusscher 2004
- [ ] Wang 1997
- [ ] Winslow 1999
- [ ] Zeng 1995
- [ ] Zhang 2000

Skipping Kiehn 1999 because it doesn't have equations for the rate constants but a look-up table instead

**Comment by mirams** [comment]
Are these in CellML format somewhere? That would be good.

**Comment by MichaelClerx** [comment]
I'm doing them in Myokit because it's easy to write. Once I'm done, I'll export them all to CellML. Can stick them online somewhere then if needed.

**Comment by MichaelClerx** [comment]
Moved to other project: https://github.com/pints-team/ikr/issues/1
