### ISSUE TITLE
Increase test coverage to 100%

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#140]
Running through a lot of Pints code looking at coding style (using `flake8`, see README.md) I found some bugs just by looking! I think that means we need to increase our test coverage.

Ideally, we'd have

- a few quick tests that check if things do what they're supposed to (optimisers, inference) on toy problems, running in well under a second.
- lots of tests that check there are no classes you can load that will cause an error, no methods you can call that contain obvious bugs!

We're lacking quite a few of the 2nd

@jonc125 do you use any tools for this?

**Comment by jonc125** [comment]
Several things you could look into:
* https://www.pylint.org/ for extra linter checks
* https://hypothesis.readthedocs.io/en/latest/ for property-based testing
* One of our team has been looking at using [MyPy](http://mypy-lang.org/) to add static type checking, with mixed results.
