### ISSUE TITLE
xbest and fbest returned by ES methods

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1411]
CMAES, xNES, SNES, and our BareCMAES all maintain a "best point seen" as well as a "distribution mean".
The idea behind the methods is that the distribution mean ends up being the best guess for the optimum, even if the error at the "best point seen" was lower.
In problems I saw so far, the distinction was minimal and the two points pretty much overlapped.

In our interface, we have methods `xbest` and `fbest` to return the "best" points found.
Having the mean be approximately equal to the best seen was convenient, as we could return `(xbest, fbest)` instead of `(mu, f(mu))`, which requires an extra evaluation of `f`.

Now I'm seeing some problems where the two are quite different though.

It leads to slightly confusing situations, e.g. the last 6 points evaluated were:
```
  -251010.2,  528860.6
  -251010.2,  528860.6
  -251010.2,  528860.6
  -251010.2,  528860.6
  -251010.2,  528860.6
  -251010.2,  528860.6
```
(with some rounding!)
while the best point returned was:
```
-243985.5,  542142.3
```
A bit of checking showed that the best point wasn't even a local optimum, just a point that happened to occur in one of the searches and had the best score yet.

So what do we do?

I think we should

1. Update all these methods to return the distribution mean as `xbest`
2. Update the interface for these methods to allow `fbest` to be `None`
3. Possibly update the interface with an extra method `xbest_seen` or something similar?

Both results are useful: the mean is meant to be a noise-filtered optimum, but depending on your data set you might not really care for noise filtering?

**Comment by MichaelClerx** [comment]
Thoughts about this @ben18785 @chonlei @martinjrobins @alisterde @mirams ?

**Comment by MichaelClerx** [comment]
the pycma code internally refers to these two as the "best" (lowest error) and "favorite" (current mean)

**Comment by MichaelClerx** [comment]
An easy "fix" could be to add a method `xfavourite()` that returns a favourite, if the method has one, and the update the docs for `xbest` to say this is the best point seen, and may differ from the current best estimate of where the optimum is?

**Comment by mirams** [comment]
You definitely want the option to get hold of the best point, but I probably would expect these to return their defaults/favourites for the algorithms if I was using it out of the box

**Comment by mirams** [comment]
(I actually spent a while trying to figure out how to get pints to give me the best point because I assumed that it was giving me the CMA-ES favourite yesterday!)

**Comment by MichaelClerx** [comment]
This also shows up in the stopping criterion: We are currently stopping if the best seen value has stopped changing, not if the (function at the?) estimated mean has stopped changing.
Not sure what cmaes proper does

**Comment by MichaelClerx** [comment]
pycma seems to just use the best (within boundaries) in the current sample

**Comment by MichaelClerx** [comment]
![local-map-zoom-xbest](https://user-images.githubusercontent.com/517644/143870814-b6a0e5ec-8a9a-4d83-866d-8ab134006f4e.png)

Here's an image showing the issue: The blue crosses show the points CMAES evaluated, and the area where these are most dense is the methods final guess of where the optimum is. But the black circle is the point it actually returns (and which has a lower error / better score).
