### ISSUE TITLE
release 0.4?

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#1419]
@DavAug made the point that Transformations are still not in the current release of pints, might be time to do 0.4?

**Comment by martinjrobins** [comment]
are there any developer instructions on how to do a release?

**Comment by MichaelClerx** [comment]
Discussed this in meeting: everyone seems happy to release
@fcooper8472 knows how and has written instructions here https://github.com/pints-team/pints/blob/master/CONTRIBUTING.md#new-releases-on-pypi-for-pip
