### ISSUE TITLE
Refactor NoUTurnMCMC for pickling

### ISSUE THREAD

**Issue by DavAug** [pints-team/pints#1427]
High dimensional or hierarchical problems can take quite long to run O(hours to days) and the NUTS sampler can currently not be pickled because it relies on async generators. That means that we can't run, pickle and resume the inference at a later time.

The core of the ``NoUTurnMCMC`` is the ``nuts_sampler`` generator which maintains the state of the sampler in form of instances of the ``DualAveragingAdaption`` and the ``NutsState``. The ``nuts_sampler`` is a property of the ``NoUTurnMCMC``
which will have to be removed for pickling. However, then the state of the sampler (``DualAveragingAdaption``, ``NutsState``) is lost. 

I suggest to refactor the ``NoUTurnMCMC`` such that it maintains its state (``DualAveragingAdaption``, ``NutsState``) itself. If we then remove the ``nuts_sampler`` for pickling, it is possible to reconstruct the same ``nuts_sampler`` using the state.

**Comment by DavAug** [comment]
@martinjrobins I may need your help with this :D I decided to only maintain the ``DualAveragingAdaption`` state because the ``NutsState`` is not so easy to access and we can easily reconstruct it / initialise it again between MCMC steps. I wrote some tests and everything works as expected, but the samplers then suddenly start to diverge in their behaviour:

My question is: Does the NUTS sampler maintain a tree depth between mcmc proposals, or is a new tree built up for each proposal?

Orginal sampler: (I just printed to get to understand how the code is jumping because the generators make that quite complicated after a few iterations :D)
```
Draw momentum
Momentum:  [22.93517972 29.56379087]
j:  0
Draw direction of trajectory:  1
Start of new tree
Perform leapfrog step
Conitnue with energy at leapfrog step
Return state after start of tree
Draw random number in update
State state:  0
Returning tuple
<class 'tuple'>
Draw momentum
Momentum:  [  1.44046301 -13.75053679]
j:  0
Draw direction of trajectory:  -1
Start of new tree
Perform leapfrog step
Conitnue with energy at leapfrog step
Return state after start of tree
Draw random number in update
State state:  1
j:  1
Draw direction of trajectory:  1
Enter recursion at:  1
Start of new tree
Perform leapfrog step
<class 'numpy.ndarray'>
Conitnue with energy at leapfrog step
Return state after start of tree
Start of new tree
Perform leapfrog step
<class 'numpy.ndarray'>
Conitnue with energy at leapfrog step
Return state after start of tree
State state:  0
Returning tuple
<class 'tuple'>
Draw momentum
Momentum:  [-33.97726683 -19.51830844]
j:  0
Draw direction of trajectory:  1
Start of new tree
Perform leapfrog step
Conitnue with energy at leapfrog step
Return state after start of tree
Draw random number in update
State state:  1
j:  1
Draw direction of trajectory:  1
Enter recursion at:  1
Start of new tree
Perform leapfrog step
<class 'numpy.ndarray'>
Conitnue with energy at leapfrog step
Return state after start of tree
Start of new tree
Perform leapfrog step
<class 'numpy.ndarray'>
Conitnue with energy at leapfrog step
Return state after start of tree
Draw random number in update
Draw random number in update
State state:  0
Returning tuple
<class 'tuple'>
Draw momentum
Momentum:  [-35.1242957    2.80114768]
```

pickle load sampler
```
Draw momentum
Momentum:  [22.93517972 29.56379087]
j:  0
Draw direction of trajectory:  1
Start of new tree
Perform leapfrog step
<class 'numpy.ndarray'>
Counting loop 0
Conitnue with energy at leapfrog step
Return state after start of tree
Draw random number in update
State state:  0
Returning tuple
<class 'tuple'>
Draw momentum
Momentum:  [  1.44046301 -13.75053679]
j:  0
Draw direction of trajectory:  -1
Start of new tree
Perform leapfrog step
Proposal (array([4.70938992, 5.71100026]), (-3.159038149472493, array([ 0.14389368, -0.28496465])), True)
```

The main thing to see from this is that the samplers behave the same up to the last perform leapfrog step of the loaded sampler, after which the loaded sampler returns a proposal, while the original sampler continues with the energy etc that it would usually receive from the tell method. I don't really understand why either of those things happen to be honest 😂 

I thought that when a program is executed and it reaches ``yield x`` it returns the value of ``x`` to the ``next(generator)`` or ``generator.send(some_value)`` commands, but instead here the yield seems to be returned elsewhere as well? If that is the case, then the difference in the loaded sampler and the original sampler is likely because the tree depth is different, which is weird when the tree is built from scratch for each MCMC step.

**Comment by martinjrobins** [comment]
> My question is: Does the NUTS sampler maintain a tree depth between mcmc proposals, or is a new tree built up for each proposal?

Nope, a new tree should be built for each proposal, from memory only the mass matrix and epsilon is preserved between proposals.

>  thought that when a program is executed and it reaches yield x it returns the value of x to the next(generator) or generator.send(some_value) commands, but instead here the yield seems to be returned elsewhere as well?

No, your understanding is the same as mine, the yield should only be returned to one of those lines. The tree depth is dynamically decided on each proposal, so if the same random numbers are drawn it should be the same...?

I'm not sure what is happening, I'll have a look at the source code again and see if I can spot anythin

**Comment by martinjrobins** [comment]
one thing that jumps to mind is the yield while the coroutine is initialising (line 422?):

```python
L, grad_L = (yield theta)
```

This will only be done in the loaded sampler, so might disrupt the ask/tell flow. Did you take this into account?

**Comment by DavAug** [comment]
That’s a good point and I thought I had taken care of it, but I will investigate this further.


On 17 Jan 2022, at 10:42, Martin Robinson ***@***.***> wrote:

﻿

one thing that jumps to mind is the yield while the coroutine is initialising (line 422?):

L, grad_L = (yield theta)

This will only be done in the loaded sampler, so might disrupt the ask/tell flow. Did you take this into account?

**Comment by DavAug** [comment]
Ok, I think there might indeed be a bug:

I have inserted multiple print statements to understand the flow of the program as shown above. The relevant ones are:

1. The tell method prints:
```
def tell(self, reply):
        """ See :meth:`pints.SingleChainMCMC.tell()`. """
        if not self._ready_for_tell:
            raise RuntimeError('Tell called before proposal was set.')
        self._ready_for_tell = False

        # send log likelihood and gradient to nuts coroutine,
        # return value is the next theta to evaluate at but not necessarily the
        # proposed mcmc step. Final mcmc proposal is distinguished from
        # intermediate steps by tuple type.
        self._next = self._nuts.send(reply)

        # coroutine signals end of current step by sending a tuple of
        # information about the last mcmc step
        print(type(self._next))
        if isinstance(self._next, tuple):
            # extract next point in chain, its logpdf, the acceptance
            # probability and the number of leapfrog steps taken during
            # the last mcmc step
            self._current = self._next[0]
            current_logpdf = self._next[1]
            current_gradient = self._next[2]
            current_acceptance = self._next[3]
            current_n_leapfrog = self._next[4]
            divergent = self._next[5]
            self._adaptor = self._next[6]

            # Increase iteration count
            self._mcmc_iteration += 1

            # average quantities for logging
            n_it_since_log = self._mcmc_iteration - self._last_log_write
            self._mcmc_acceptance = (
                (n_it_since_log * self._mcmc_acceptance + current_acceptance) /
                (n_it_since_log + 1)
            )
            self._n_leapfrog = (
                (n_it_since_log * self._n_leapfrog + current_n_leapfrog) /
                (n_it_since_log + 1)
            )

            # store divergent iterations
            if divergent:
                self._divergent = np.append(
                    self._divergent, self._mcmc_iteration)

            # request next point to evaluate
            self._next = next(self._nuts)

            # Return current position as next sample in the chain
            return (
                np.copy(self._current),
                (current_logpdf, np.copy(current_gradient)),
                True
            )
        else:
            # Return None to indicate there is no new sample for the chain
            return None
```

The prints in the leapfrog step:
```
@asyncio.coroutine
def leapfrog(theta, L, grad_L, r, epsilon, inv_mass_matrix):
    """
    performs a leapfrog step using a step_size ``epsilon`` and an inverse mass
    matrix ``inv_mass_matrix``.

    The inverse mass matrix can be a 2 dimensional ndarray, in which case it is
    interpreted as a dense matrix, or a 1 dimensional ndarray, in which case it
    is interpreted as a diagonal matrix.
    """
    r_new = r + 0.5 * epsilon * grad_L
    if inv_mass_matrix.ndim == 1:
        theta_new = theta + epsilon * inv_mass_matrix * r_new
    else:
        theta_new = theta + epsilon * inv_mass_matrix.dot(r_new)
    print('Perform leapfrog step')
    L_new, grad_L_new = (yield theta_new)
    print('Conitnue with energy at leapfrog step')
    r_new += 0.5 * epsilon * grad_L_new
    return L_new, grad_L_new, theta_new, r_new
```

Each tell call will have exactly one `print(type(self._next)` statement which is a tuple for a MCMC proposal. Once an MCMC proposal is returned, a new tree is constructed and exactly one leapfrog step performed. This is marked by the print statement `print('Perform leapfrog step')`. Then a proposal is returned. The original sampler follows this pattern for the most part, but then suddenly appears to deviate from it:

```
<class 'tuple'>
Draw momentum
Momentum:  [  1.44046301 -13.75053679]
j:  0
Draw direction of trajectory:  -1
Start of new tree
Perform leapfrog step
Conitnue with energy at leapfrog step
Return state after start of tree
Draw random number in update
State state:  1
j:  1
Draw direction of trajectory:  1
Enter recursion at:  1
...
```

This suggests that the sampler can falsely continue to build trees when it should interrupt, return and build a new tree from scratch for the next proposal.

**Comment by martinjrobins** [comment]
that is a weird bug, I can't see how that would happen, once the "Perform leapfron step" is reached there should be another yield, and the tell should return a proposal.......

**Comment by DavAug** [comment]
Ok no bug after all - my bad.. 😂
The 
```
Perform leapfrog step
Conitnue with energy at leapfrog step
```
sequence occurs from the next `tell` call after the proposal has been returned. I just had a minor bug in the `load_state`, where I confused the order of the input arguments to the `nuts_sampler`. Now the pickled sampler and the original sampler agree and I triple checked that the sequence of the build trees and leap frog steps are correct. A new tree is built from scratch after each MCMC step.

**Comment by martinjrobins** [comment]
great, so the pickling works! :)

**Comment by ben18785** [comment]
That's cool and a really useful feature of PINTS :)
