### ISSUE TITLE
OptimisationController.set_parallel()  no longer speeds up optimisation for CMAES

### ISSUE THREAD

**Issue by HOLL95** [pints-team/pints#1431]
After recently upgrading to pints 0.4.1, the CMAES algorithm is no longer sped up by the set_parallel command. 

Although the process is parallelised (via inspection of processes with top), the time taken for optimisation with set_parallel(True) and set_parallel(False) is the same for an equivalent number of iterations.

**Comment by MichaelClerx** [comment]
Sorry for the very late reaction. Can you give some more details about the problem you're solving with CMAES?
