### ISSUE TITLE
Add differential evolution MCMC

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#149]
Basic: http://library.wur.nl/WebQuery/wurpubs/fulltext/26336

DREAM: https://escholarship.org/uc/item/6j55p5kh (Matlab implementation), first described: https://www.researchgate.net/profile/James_Hyman/publication/41035177_Accelerating_Markov_Chain_Monte_Carlo_Simulation_by_Differential_Evolution_with_Self-Adaptive_Randomized_Subspce_Sampling/links/09e4150c0a96b6d034000000.pdf

**Comment by MichaelClerx** [comment]
See #158

**Comment by ben18785** [comment]
This paper explains premise behind differential evolution: https://msp.org/camcos/2010/5-1/camcos-v5-n1-p04-p.pdf

**Comment by ben18785** [comment]
This is also good: http://www.jstor.org/stable/pdf/10.1086/670067.pdf
