### ISSUE TITLE
Add reciprocal distribution prior (LogUniformLogPrior) to help estimate parameters that vary over multiple orders of magnitude

### ISSUE THREAD

**Issue by abillscmu** [pints-team/pints#1498]
Hi, thanks for a great package! It would be great to have a  [reciprocal/log uniform](https://en.wikipedia.org/wiki/Reciprocal_distribution) prior. It should be straightforward since it's implemented in `scipy.stats`, and I would be happy to implement it.

**Comment by ben18785** [comment]
Thanks @abillscmu -- sure, that'd be great. It's worth reading the [contributing guidelines](https://github.com/pints-team/pints/blob/main/CONTRIBUTING.md) before starting to implement this perhaps.
