### ISSUE TITLE
Error when attempting to run in parallel mode

### ISSUE THREAD

**Issue by feresro** [pints-team/pints#1529]
When I try to run a script for fitting a series of parameters to a set experimental data I get an error if I try to run it on parallel, if I switch the parallel off it runs just fine (opt.set_parallel(FALSE).
![Question_2](https://github.com/pints-team/pints/assets/162124583/769d644d-2679-440f-a93c-d5c93b9a67da)

**Comment by MichaelClerx** [comment]
Hi @feresro ,
on windows, you need to do as the error message says and make sure your code - or at least everything that isn't a class, function, or constant definition - is only called inside an `if __name__ == '__main__':` block.

So the example would become something like
```
import ...

class MyModel(...):

class MyPrior(...):

if __name__ == '__main__':
    model = MyModel()
    ...
```

See https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods

**Comment by feresro** [comment]
Hi @MichaelClerx, thanks a lot for the answer. Does that mean that if I run the code on a linux enviroment should work without adjustments?

**Comment by MichaelClerx** [comment]
Yeah it should!

**Comment by MichaelClerx** [comment]
@feresro did that solve your problem?

**Comment by feresro** [comment]
@MichaelClerx Sorry, yes it did! Did not tried to run it on windows because I had to move to a linux enviroment (therefore my second question) and it worked just fine there. Thank you!
