### ISSUE TITLE
Pints plots - can they be improved?

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#155]
I really like the KDE plots but they are expensive to plot for more than a few thousand posterior samples. At the moment, when KDE=False, we get a sort of heatmap that I personally don't find as useful as a scatter plot with opacity. 

Also, are there lower computational power options that we could use compared to KDE?

@chonlei sorry, I'm aware that this a view long after we'd decided on your pints.plots, but after a few days of playing with the default plots, I just feel that we could tweak these methods a little.

**Comment by ben18785** [comment]
To encourage people to first use known parameter values to generate fake data, I would also like to have the possibility of adding known parameter values to plots. This will also help with the examples we give.

**Comment by MichaelClerx** [comment]
See #163

**Comment by MichaelClerx** [comment]
Looking good! But why the new notebook? We should just update the old one :-)

**Comment by ben18785** [comment]
Ah, I didn't realise there was an old one!
