### ISSUE TITLE
Change 'burn-in' to 'warm-up' throughout Pints

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#157]
This term is preferable for a number of reasons, and is now industry standard.

**Comment by chonlei** [comment]
Can we somehow keep both? I think some people may get confused by the terms and may search one instead of the other. Or will this make this more confusing? 

(If we don't keep both, I think we should at least have the two terms in the documentation -- at least make the both searchable?)

**Comment by ben18785** [comment]
Hi Chon, I personally think we should just pick one and use that one. Warm-up is up-to-date with the MCMC literature (including Gelman etc.) and so I personally think we should be contemporary with our choice...

**Comment by ben18785** [comment]
But, yes, perhaps we could have two terms in the documentation. Or a clarification that warm-up = burn-in.

**Comment by MichaelClerx** [comment]
If it's the new standard then let's change!
It's easy enough to write something in the docs like "Sets the number of warp-up (burn-in) iterations"
