### ISSUE TITLE
Add an example of using a log_likelihood in an optimisation

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#159]
At the moment we estimate the parameters of the logistic equation with noise for a squared error (yielding ML estimates of the logistic parameters) but we could actually use it to do full maximum likelihood estimation (i.e. including the noise standard deviation) if we do optimisation on the log_likelihood directly. I feel that this might provide a nicer link between the optimisation and sampling/MCMC parts of Pints.

**Comment by MichaelClerx** [comment]
We can do that, yes, and Gary has done it for several problems!

However, Martin had some issues where the MLE didn't perform well compared to a simple squared error. I also feel it's conceptually much simpler to do optimisation without adding the stats...

**Comment by MichaelClerx** [comment]
I suggest we do this in the form of an example using an ion channel toy model (#124) and then do our thing of running CMA-ES with a log_posterior before running MCMC
