### ISSUE TITLE
Update description of Pints on github

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#164]
Think now it might be worth downplaying the whole 'hierarchical' modelling aspect (at least for the time being). 

Also, I think it's probably worth generalising the description to include other things than voltammetry and electrophysiology as I think our audience for this would be a bit more general... I think we are now thinking of Pints as an inference machine with many levers -- each level representing a popularly used sampling routine -- that can be applied to a wide range of time series inverse problems, from situations when no likelihood is available (ABC); likelihoods; likelihoods + sensitivity etc. It'd be nice to make a visualisation of the hierarchy triangle we discussed in the meeting to convey this, perhaps?

**Comment by MichaelClerx** [comment]
Sure! I've made some initial changes. Feel free to add the hierarchy! I'd like to link to our code organisation / documentation / examples too!

**Comment by MichaelClerx** [comment]
Could someone describe the hierarchy of methods again, @ben18785 @sanmitraghosh (just in the comments, not in the readme) ?
I would really love to have this clear, also for the organisation of our code

- optimisation
  - population based methods
- inference
  - mcmc
  - ...?

**Comment by MichaelClerx** [comment]
For the hierarchy, see #209 !
