### ISSUE TITLE
Investigate rPython and/or reticulate R packages

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#165]
Both of these packages allow an R user to call Python packages from R. Since a number of potential users may prefer R rather than Python, I'd be interested in seeing whether these packages allow an R user to effectively use Pints. Similarly, I'd be interested in knowing how easy it is to call a Python package from Matlab...

**Comment by MichaelClerx** [comment]
Can it reticulate splines?

**Comment by MichaelClerx** [comment]
This would link into the interfaces idea for #1071

**Comment by ben18785** [comment]
Yup, agreed
