### ISSUE TITLE
Create AbstractAdaptiveMCMC class

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#167]
@sanmitraghosh suggests we should structure adaptive mcmc classes this way, using a method `_adapt()` called at the end of every MCMC step.

Seems sensible, unless we can think of methods that won't fit this scheme? It there's 3 that do and 3 that don't then I don't think it's worth it. I don't have this kind of overview though!

**Comment by ben18785** [comment]
I'm not convinced there are going to be enough adaptive samplers (by my count, just standard MH and Remi's method) to make this worthwhile. The differential evolution algorithm is so different that it makes sense for this to be on its own and the 'emcee' algorithm depends on an external package. I just think we have enough to do already without restructuring the code base.
