### ISSUE TITLE
Organisation: Optimisation and Inference ?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#171]
Hi all!

Currently our main methods faill into three main packages: `optimisation`, `mcmc`, and `nested`.

What would be a better way to split these (and future) methods? Optimisation and inference? @ben18785 and @sanmitraghosh I remember we talked about a hierarchy of methods, should each leaf in this hierarchy be a package, for example?

Would love to have one layout we can follow everywhere: (1) in the code base (2) In the documentation (3) in the examples (4) in our papers, etc.

**Comment by ben18785** [comment]
@MichaelClerx I agree with you. Optimisation and inference sounds good (particularly because SMC and particle MC doesn't really fit in any of those boxes).

**Comment by MichaelClerx** [comment]
@sanmitraghosh also suggested optimisation and sampling

**Comment by martinjrobins** [comment]
Optimisation and sampling sounds good to me. Sampling seems more general than inference, and it clearly describes the outputs

**Comment by MichaelClerx** [comment]
So it's between sampling and inference then?

Are there maybe other categories we could spit sampling/inference into? So that we'd get e.g. `optimisation`, `mcmc` and `smc` ? This would be great if the split could be made so that all methods in a single category could share a common interface

**Comment by mirams** [comment]
Don't particularly mind, although I would think `sampling` (probability distributions) is just one bit of `inference` (which suggests priors, data and Bayesian approach).

**Comment by MichaelClerx** [comment]
See #209
