### ISSUE TITLE
rhat and rhat_all_params

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#172]
I don't understand the difference between rhat and rhat_all_params from the docstrings!
Also, maybe these methods could be merged into a single method with an `all_parameters` argument?

(No need to abbreviate words like "points" and "parameters" etc., by the way!)

**Comment by MichaelClerx** [comment]
(Love the references to literature by the way, thanks!)

**Comment by ben18785** [comment]
rhat and rhat_all_params do different things: rhat calculates R-hat for a single parameter; it is called by rhat_all_params. Realistically, I think users will need the latter, but I need/want the former as it makes the code easier to read, I think. How should I handle this sort of issue? Basically, where I create a helper function that no user will need but I want it..? Sorry for my ignorance of these things!

**Comment by MichaelClerx** [comment]
Two options:

If you only need it from one method, you can use nested methods:

    def run(xs):
         def f(x):
            return x*2
        # code that uses f(x) a lot!

Which is slightly less efficient, but sometimes cleaner than not having a method for it at all

Alternatively, define a private method:

    def _f(x):
        return x*2

    def good_thing_1(xs):
        # code that uses _f(x)

    def good_thing_2(xs):
        # code that uses _f(x)

**Comment by MichaelClerx** [comment]
And then with really excellent docstrings that explain what they do, esp. for the private method as that probably does something a lot more obscure (and in need of explanation) than the public ones :D

**Comment by ben18785** [comment]
Thanks Michael. That clears that up!
