### ISSUE TITLE
Add FFT-based score function

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#18]
Martin wrote:

> [C]an you create an efficient score function that depends on the distance between experiment and model in the frequency domain, rather than time domain? I guess the score class can just take an FFT of the values when its created and re-use this?

**Comment by MichaelClerx** [comment]
Martin wrote:

"_[C]an you create an efficient score function that depends on the distance between experiment and model in the frequency domain, rather than time domain? I guess the score class can just take an FFT of the values when its created and re-use this?_"

**Comment by MichaelClerx** [comment]
@martinjrobins Do we need this ticket? Sounds quite problem specific. If so, users could just implement whatever as long as it extends `ErrorMeasure` or `LogPDF`

**Comment by martinjrobins** [comment]
yea, this is specific to electrochem stuff
