### ISSUE TITLE
Come up with a good way to validate inference methods

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#181]
Ideas:

- Compare resulting mean: norm(mean - real) should be below some tolerance
- Compare resulting variance: Should be within some range of "true" variance? We can get this for one of our test problems using Pints or STAN or some analytical solution?

- Compare our methods against each other: do they all agree (downside is it's no longer a unit test, so we'd need a test per class for the methods, and a single massive test for all the output? It would also fail when 1 of X methods fails)

~Open questions:~

- Should we seed the random generator first? Reduces the scope of our testing! (And could fail if numpy's generator fails) --> Yes
- Should we test different toy problems or just the one? --> Multiple
- Should we split the tests into a short and a long suite? --> Yes #238

**Comment by MichaelClerx** [comment]
Decided we should have tests of code (do you get errors when you run stuff) separated from this kind of validation stuff

**Comment by ben18785** [comment]
I have been doing some thinking on this and thought we could start with the following models to test all sampling software against:

- Correlated 3/4-D Gaussians (already in our toy models); potentially a number of models: low correlation vs high correlation,  start samplers near mode vs away from it, and so on. The benefit of using a toy model is that we know what the true distribution is and, hence, means that we don't need to do any preliminary runs with a reliable sampler to estimate its properties. 
- Logistic equation. Think have figured out how to determine a numerical deterministic solution to the posterior here -- not as simple as it sounds -- if we use flat priors on all parameters. We can compare this to the sampling one.

Any other ideas? @MichaelClerx @martinjrobins @sanmitraghosh Remember that the models need to be simple enough that even the worst samplers (so long as they are actually coded up correctly!) will converge in a reasonable amount of time to the posteriors. This isn't benchmarking.

**Comment by sanmitraghosh** [comment]
I think since we are not inventing or proposing a new sampler, thus we need simple tests to see that we have coded up correctly. For that the best thing to do is to use the Banana distributions. Pretty much all adaptive samplers should be able to sample it correctly. And this is also a standard test case used in just about every paper. There are a few other non-linear analytically tractable distributions such as the ring and flower. I would get some code for these as well.

For unit test we should compare the norm of sampled vs true mean vector. Some papers also use MMD for comparison which we can incorporate within our tests.

**Comment by ben18785** [comment]
Hi Sanmitra,

Let's chat about this tomorrow if you're in? My feeling is that the banana
may be too complex for some samplers (non-adaptive Metropolis and other
stuff will be in here too), but we can try it! As I said, remember that
this is not meant to benchmark, just to test that they work.

Agreed that we can use a correlated normal to do quite a bit of unit
testing. Was thinking of adding the logistic though for completeness.

Cheers,

Ben

**Comment by MichaelClerx** [comment]
We have something now so closing this. We can still make new tickets criticising or adding to the current  options!
