### ISSUE TITLE
Add population MCMC

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#186]
As defined here: https://pdfs.semanticscholar.org/88d9/b46f7196499679338a01484461eb86d701fd.pdf

**Comment by ben18785** [comment]
Think I can make the chains adapt their proposals over time... need to double check that things still converge.

**Comment by chonlei** [comment]
@ben18785 A paper on choosing the temperature ladder:
https://arxiv.org/pdf/1501.05823.pdf

**Comment by MichaelClerx** [comment]
Implementation of this will be simpler once we have #253
