### ISSUE TITLE
Differential evolution example has undocumented stuff at the end

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#189]
We'd agreed to set up the examples as follows:

1. Some "first example" shows how all methods of a class work, with lots of separate cells and explanation
2. The specific method ones then just show how to do that method, in a format you can easily copy-paste

The method also seems to be returning multiple chains, while claiming to adhere to the current MCMC interface (which specifies a single returned chain). We can discuss these things, but they shouldn't go on master until the whole codebase is consistent!

**Comment by ben18785** [comment]
Yep, will get on creating those examples. Thanks for pointing that out.

Re: multiple chains, yeah, not sure how to handle this one. The method, by its nature, involves multiple interacting chains and so will return multiple chains.

What do you think is the best way forward here? Do we need a new class, MCMCMultipleChains?

**Comment by MichaelClerx** [comment]
Good question! Probably something like that yeah, are there many methods that do multiple chains at the same time? And does this mean they're not independent chains?

**Comment by MichaelClerx** [comment]
This is mostly fixed now in #198 except that we use rhat without explanation. Will add separate issue for this!
