### ISSUE TITLE
Warning from plot.pairwise

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#190]
Running this:

    import pints.plot
    pints.plot.pairwise(chain, kde=True)
    pl.show()

Currently gives us this warning (in python2.7):

    /usr/lib64/python2.7/site-packages/matplotlib/axes/_base.py:1292: UnicodeWarning: Unicode equal 
    comparison failed to convert both arguments to Unicode - interpreting them as being unequal
      if aspect == 'normal':
    /usr/lib64/python2.7/site-packages/matplotlib/axes/_base.py:1297: UnicodeWarning: Unicode equal 
    comparison failed to convert both arguments to Unicode - interpreting them as being unequal
      elif aspect in ('equal', 'auto'):

Suspect this is not our fault, but would be nice to avoid this somehow anyway!

**Comment by ben18785** [comment]
Yeah think this is a Matplotlib issue. Not sure what we can do about it?

**Comment by MichaelClerx** [comment]
It's pretty annoying, because it's nothing to do with the input we give to the method. I wouldn't normally recommend this, but I've simply added code to suppress the unicode warning.
