### ISSUE TITLE
Make pip install matplotlib by default??

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#191]
The default pip install currently doesn't include matplotlib, because we didn't want it to be required on servers without graphics. But... It is nice for users (esp. in virtual environments) to have matplotlib...

Should we change the default installation instructions?

Or maybe add matplotlib to the core dependencies but have the internal rule never to import it outside of a plotting method?

**Comment by mirams** [comment]
Even on a server nice to have it to auto-generate a load of PDFs etc.?

**Comment by MichaelClerx** [comment]
Pints only uses matplotlib to create debug plots to show!

**Comment by mirams** [comment]
If the examples won't run without it, I think you should install it!

**Comment by MichaelClerx** [comment]
Agreed. Just got to work out how exactly, sometime, with this ticket as a reminder

**Comment by ben18785** [comment]
Yep, good idea Michael! I think it's a common enough dependency that we can have people install it at the start.

**Comment by MichaelClerx** [comment]
Ok, it seems to be alright on arcus, so let's just go ahead then...

I'll still reject any code that imports matplotlib as part of `import pints` though :D
