### ISSUE TITLE
Select better initial starting points for MCMC sigma

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#192]
At the moment we use a starting proposal that is a matrix with 0.01 * initial parameter values as our default proposal covariance matrix for MCMC. I've found that for parameters < 1, this leads to a very high rejection rate (like >99%) in doing standard Metropolis (for AdaptiveCovariance it doesn't matter because sigma adapts). 

This is because the typical step length is given by the standard deviation = sqrt(0.01 * initial parameter). Since sqrt(0.01) = 0.1, and sqrt(initial parameter) > initial parameter, this can lead to a step length that is comparable to the initial parameter value. For example, suppose a parameter, theta = 0.01, initially (like our growth parameter in the logistic), then the step length we use as default is about 0.01; which leads to a very high rejection rate.

I propose something like the following to replace our current default rule,

sigma = np.diag(0.005 * self._x0**2).

This seems to yield a better acceptance rate.

This probably isn't optimal, but something like this would, I think, be better than our current default rule. 

What do people think?

**Comment by ben18785** [comment]
Actually, the above rule doesn't work for theta >> 1. We probably need two separate cases, dependent on whether theta > 1 or < 1.

**Comment by MichaelClerx** [comment]
I'd also suggest setting `sigma[i, i] = 1` in any direction `i` where `x0[i] == 0` (because it's definitely not zero, and you have no other information about the scale so `1` seems a reasonable guess?

We could use the prior to guess to, if given, I do something similar for the sigma guess with optimisation boundaries: https://github.com/pints-team/pints/blob/master/pints/_optimisers/__init__.py#L108-L138

**Comment by ben18785** [comment]
Yep, good point!

**Comment by chonlei** [comment]
This might well relate to the problem I had, as @ben18785 suggested, I will give it a try and confirm that.

**Comment by MichaelClerx** [comment]
Am addressing this problem as part of #198 as well
