### ISSUE TITLE
Add something to check test coverage

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#202]
Does this even exist?

What am I asking :-)

@jonc125?

**Comment by jonc125** [comment]
Yes, these things exist. I've not set one up personally; will ask here for recommendations.

**Comment by jonc125** [comment]
https://codecov.io/ seems to be the main thing used here; see e.g. https://github.com/codecov/example-python

**Comment by MichaelClerx** [comment]
Thanks!

**Comment by MichaelClerx** [comment]
Awesome! Thanks @martinjrobins and @jonc125 !
