### ISSUE TITLE
Use order (likelihood, prior) for LogPosterior class (and throughout Pints)

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#204]
Noticed that the nested samplers get both a logprior and a loglikelihood as input (compared to a single logposterior for MCMC methods).

Does this mean they can only work within a Bayesian paradigm?

**Comment by ben18785** [comment]
Yes, that's correct.

**Comment by MichaelClerx** [comment]
Cheers!
One more thing, I noticed the order of the arguments is `log_likelihood, log_prior`. For the `LogPosterior` class I chose the opposite (not sure why). The equation is usually written `likelihood * prior` as well isn't it? So maybe best to be consistent with that order throughout Pints? @ben18785 @sanmitraghosh ?
