### ISSUE TITLE
Diagnostics `rhat`, `rhat-params`, and `effective_sample_size` need docs mention

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#206]
Need to:

- [x] Add them to the sphinx docs (docs/sources/diagnostics.rst should be created)
- [x] Double-check docstrings
- [x] Do a local build and check if it worked before uploading (`cd docs`, `make clean`, `make html`, check results in `docs/build/html` in browser)

**Comment by ben18785** [comment]
Addressed in #468.
