### ISSUE TITLE
Add pints to pip

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#208]
Not just yet, but should do this eventually

**Comment by MichaelClerx** [comment]
https://packaging.python.org/tutorials/packaging-projects/

**Comment by MichaelClerx** [comment]
Anyone remember what we decided on this?
Do it manually? Some sort of github action? Password management? @fcooper8472 @martinjrobins ?

**Comment by martinjrobins** [comment]
Thibault used github actions for Pybamm (https://github.com/pybamm-team/PyBaMM/blob/develop/.github/workflows/build_wheels_and_publish.yml). This is probably more complicated than what we need though, as Pybamm needs to compile C/C++ code as well

**Comment by fcooper8472** [comment]
Pints is now on pip: https://pypi.org/project/pints/

One minor issue this has brought up is that the long description is just the Readme, which contains relative links that only make sense with the full source tree (e.g. on GitHub).  The easiest thing might be to make those links GitHub explicit, e.g. instead of
```
To install PINTS as a [developer](CONTRIBUTING.md), use
```
have
```
To install PINTS as a [developer](https://github.com/pints-team/pints/blob/master/CONTRIBUTING.md), use
```

**Comment by fcooper8472** [comment]
In terms of automating a release, there are a couple of options:

1. Automatically, when a new release is authored on GitHub
2. Manually, when you press a button in the GitHub actions UI

In either case it's a simple GitHub actions script, just with different triggers.

**Comment by MichaelClerx** [comment]
Awesome! Yeah I think hard links would be best

Automatically updating sounds good, but is maybe a bit tricky if we make a mistake in the release (as pip offers no way back once a release is out, without changing the version number).
So maybe a button press would be better?

How are we doing things with passwords and such? Is it tied to github permissions?

**Comment by fcooper8472** [comment]
@MichaelClerx it's not too big of a deal if you make a mistake with a release.  You can "yank" the release from PyPi so that pip will never choose it, and you can always then bump the minor version number.

I'm not sure having a button would make it any less likely to get it right, versus authoring a release, which also has a button to press.  I think I lean to the automatic-on-release model.

See the actions script in the PR #1193 for what this would look like.

**Comment by fcooper8472** [comment]
The password is a token generated through my PyPI account, stored as a GitHub secret.

**Comment by MichaelClerx** [comment]
That looks good! (Although PINTS supports Python 2.7, as we expect people to run it on hardware provided to academics...)

One thing that PR is missing is an update to CONTRIBUTING.md that describes how releases are made (and maybe says who gets to do it, and when?)

**Comment by fcooper8472** [comment]
@MichaelClerx I have added 2.7 to the `python_requires` clause.

However, I would like to reiterate my personal opinion that it is irresponsible of us to be enabling the continued use of Python 2.7.

**Comment by fcooper8472** [comment]
Think the PR is in good shape.  @MichaelClerx could you merge?  I want to create a new release tagged at 0.3.0 and check whether that upload action works as planned

**Comment by MichaelClerx** [comment]
> @MichaelClerx I have added 2.7 to the `python_requires` clause.
> 
> However, I would like to reiterate my personal opinion that it is irresponsible of us to be enabling the continued use of Python 2.7.

It's not that I don't want people to switch to 3.5+, it's just that I think it's less important to do that than to allow everybody everywhere to use our software. Why force academics everywhere to spend their time educating their IT staff? It'll happen soon enough anyway. I don't think we need to be at the forefront of that battle

(It'd be different if security mattered for PINTS, or PINTS-based applications, in any way)

**Comment by fcooper8472** [comment]
Seems to have worked perfectly!

https://pypi.org/project/pints/

**Comment by MichaelClerx** [comment]
Excellent!
Would you like me to add some more elaborate release notes to the github page?

**Comment by fcooper8472** [comment]
By all means!

And if you want to update anything in the contributing document or README etc, just bump to 0.3.1 and create a new release :+1:

**Comment by MichaelClerx** [comment]
OK! I've edited the release with a summary of features, which was hard! Too many of them :D  (or too few pints releases).

Does this trigger the script again? Or is it all good?

**Comment by fcooper8472** [comment]
Only when the release is published, so no, editing the release info won't trigger anything.
