### ISSUE TITLE
Hierarchy of methods

### ISSUE THREAD

**Issue by sanmitraghosh** [pints-team/pints#209]
As requested by @MichaelClerx : 

MCMC : 
    i)AdaptiveCovariance, DREAM 
    ii) Netsed sampling 
    iii) Particle based ones--PopulationMCMC, SMC 
    iv) Likelihood free ---ABCMCMC, ABCSMC 
    v) Score function based---MALA, HMC, NUTS 
    vi) DifferentialGeomtric ones---smMALA, RMHMC 

Optimisation :
     i)PSO, GA 
     ii) Info Geometric ones ---CMAES, XNES, SNES.

I have given an exhaustive list, probably all of these wont be implemented (or needed). But you can organise them these way.

**Comment by ben18785** [comment]
Thanks Sanmitra. Although think this is a more apt division:

- Sampling: MCMC, nested, importance sampling, ABC etc.
- Optimisation 

Since, for example, SMC is not MCMC, nor is nested sampling, etc. So think, keep the same two-division thing but call one 'sampling'.

Sound ok?

**Comment by sanmitraghosh** [comment]
Sounds good to me, as there are overlaps anyway.

**Comment by MichaelClerx** [comment]
I remember there was some structure in the information that MCMC methods needed? So an order from likelihood free up to methods needing fisher information?

**Comment by ben18785** [comment]
Yep!

**Comment by MichaelClerx** [comment]
Well what was it? :D

**Comment by sanmitraghosh** [comment]
For MCMC methods i)---iii) only need logPosterior. Methods v) needs derivative of logPosterior and vi) Hessian of logPosterior.
iv) is a bit tricky, ideally the user should define a distance function between data and states. However, least squares is a good distance function for time series problems.

Hope this helps @MichaelClerx @ben18785

**Comment by MichaelClerx** [comment]
@sanmitraghosh @ben18785 can you have a look here: http://pints.readthedocs.io/en/latest/#hierarchy-of-methods and see if you agree?

To edit the file, look in `docs/source/index.rst`

**Comment by sanmitraghosh** [comment]
I think this is okay.

**Comment by ben18785** [comment]
Ok, I think we need to move 'PopulationMCMC' to be under the MCMC heading. We also need to add emcee hammer and simple 'Metropolis' (i.e. the unadapted version) to the MCMC samplers.

Finally, I'm not a fan of 'score function based' as a heading. It's not just using the score (i.e. the derivative of the log likelihood) but also the derivative of the log priors; in other words, it uses the derivative of the log posterior. I would call it something like '1st order sensitivity MCMC samplers'. Then perhaps just call what used to be 'MCMC' as 'MCMC without gradients'?

**Comment by MichaelClerx** [comment]
Is it just 'Metropolis'? Or 'Metropolis-Hastings' ? (I've put Metropolis-Hastings for now)

**Comment by ben18785** [comment]
At the moment we only do 'random walk Metropolis' not 'Metropolis-Hastings'. That's because we don't allow parameters to have one-sided boundaries when sampling from them. Is that right? In that, we currently don't have MCMC methods which allow for had boundaries...

**Comment by MichaelClerx** [comment]
Yeah that's right! Priors, but no boundaries

**Comment by mirams** [comment]
I think Hastings added capability to have asymmetric proposal distributions, is that right? And one example/application of that is implementing hard 'boundaries' so that no points are proposed outside a bound?

**Comment by ben18785** [comment]
Yes, that's right. It just has asymmetric proposals, whose most useful purpose is to deal with (single) boundaries in parameter space. I think we should - at some point - perhaps consider implementing this.

All it'd mean is we log transform the variables, apply the Jacobian to the log posterior and sample, then apply the inverse transform back. The reason for doing this is that often it is much easier and more intuitive to set priors on untransformed variables.

**Comment by MichaelClerx** [comment]
We should probably mention this in the AdaptiveCovarianceMCMC file somewhere then?

At the moment the proposal distribution is hardcoded.

Sounds like it also ties in to #31 a bit :-D
