### ISSUE TITLE
Combining priors

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#212]
HI all,

Mathematically, how do we combine priors? And should we add functionality for this in Pints?

I have a real life example, in the form of Kylie's case study, which contains a simple uniform prior (lower and upper bounds on each parameter) and a more complicated constraint that says:

```p1 * exp(p2 * 50) < 1000```

where `p1` and `p2` are parameters.

Feels to me like this is part of the prior, although it could also go into the objective function (where you quite often have funny constraints, e.g. sparsity, penalisation, etc.)

Interested to hear your thoughts! @ben18785 @sanmitraghosh @mirams @DavidGavaghan

**Comment by mirams** [comment]
There is really only one prior over all parameters, it should be possible to define it as

`prior = f(vector_of_params)`

Sometimes we treat them as independent, but that is a special case really. So I wouldn't describe it as combining priors, rather that we've marginalised the real prior at the moment!

**Comment by MichaelClerx** [comment]
Why is there only one prior? What if you have two sources of information?

**Comment by MichaelClerx** [comment]
In Kylie's case it's fairly simple to do, because for inference we can use an unnormalised prior, so we can create a first prior from the lower/upper boundaries as `c1 > 0` within boundaries and `0` outside. Then multiply with `c2 > 0` if the rate constants are within boundaries or with `0` outside. (In Kylie's code c2 = 1). The fact that it doesn't sum to 1 anymore doesn't matter for MCMC. But what if we want to use e.g. a lognormal prior on the parameter boundaries + the restriction on the rate constants?

**Comment by ben18785** [comment]
There's always only one prior, which is a probability distribution defined over the space of all parameters. It's often the case that that probability distribution can be decomposed into a product of independent distributions over single parameters. There are occasions, however, when we don't want to choose this sort of decomposition - we need dependence between parameter values. The example you mention is such an occasion. Here whether we assign a positive prior probability density to one parameter's value depends on the value of another.

I think that we need a mechanism for specifying dependent priors in Pints. How we do this, I'm not sure. Whether it's something we want to do now, I'm also not sure. I guess it depends how important these sorts of constraints are for the models we are looking at, of which I am not as au fe as you guys.

**Comment by chonlei** [comment]
I thought, formally, if we have really two sources of information, we should update the prior using the Bayes rule (i.e. the posterior becomes the next prior when we use the new information -- the third source of information if you like). If the combining process is too complicated to work out mathematically, than we do MCMC...

But in the case that @MichaelClerx you started with, I think it is easy enough to work them out by simply changing the uniform priors...

However, since priors should really be one (big) function, besides those we have in Pints now, can we have a "user defined" prior option? Just like how we allow users to define the loglikelihood, then in that case, one can probably do something like
```
def MyPrior(x):
    p1, p2 = x  # my parameters
    if p1 * exp(p2 * 50) < 1000:  # one condition
        return 0
    [the rest of the condition...]
    return <the prior>
```
If someone really what to go for something "special"?

**Comment by MichaelClerx** [comment]
Hi @chonlei ! Yes that's the best way to currently implement it in Pints!

It _does_ mean that we have to be a bit more careful how we define the `LogPrior` class, since we then have to make clear that it's okay to have an unnormalised `LogPdf` as a prior, and we have to be explicit about the fact that not all priors can be used as an input to methods that assume you can sample from the prior without MCMC and such.

That's why I was hoping there was a clean way to do this. It doesn't sound like it should be too hard!

**Comment by MichaelClerx** [comment]
@sanmitraghosh agrees that it's not an easy thing to do _in general_, so we should just stick with the priors we have an let people override things like @chonlei suggested above.

Thanks everyone! Closing this ticket
