### ISSUE TITLE
Add an example showing how to define a custom Problem

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#214]
Make it clear in a single notebook that it can be done instead of defining a model

**Comment by chonlei** [comment]
Just wondering what do you mean by a custom Problem?

**Comment by MichaelClerx** [comment]
A `pints.SingleSeriesProblem` defined directly, instead of via a `pints.ForwardModel`. See #211

**Comment by MichaelClerx** [comment]
A problem needs data, which probably makes this a bad idea... Closing!
