### ISSUE TITLE
Add an example showing how to write a custom prior

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#215]
Can anyone think of a good example where this is necessary?

**Comment by chonlei** [comment]
If we had 2 measurements A and B (say two time series...), and we believe that the A, B comes from the same source, i.e. their parameters share the same "true" distribution. Then we can probably do something like 1. run a MCMC using A with a simple prior (say uniform one) and get an posterior out of it, and then 2. we need to update the posterior using another source of information, i.e. B, then we run another MCMC using B but with the prior comes from the posterior in step 1?

For 2D case, we can e.g. use KDE to estimate the posterior from step 1, but I don't know if it is wise to show this but not able to extend to higher dimensions...

Or are we stepping into something that is not necessary? ( I think this one we combine the two sources of uncertainty... namely the uncertainty from noise and uncertainty of the "true" parameters. Did I get this wrong? @mirams )

**Comment by MichaelClerx** [comment]
Hi Chon! That's a cool idea, but I was thinking more in terms of a simple LogPrior we define directly, for example boundaries that are not aligned with the parameter space axes (e.g a normal uniform prior that's slightly rotated, or a triangle instead of a square for a 2d problem). It'd help the example if we had a real world reason for doing so

**Comment by MichaelClerx** [comment]
Another abstract example would be a (hyper)sphere around some known point in parameter space
