### ISSUE TITLE
Initial adaptation free period for adaptive MCMC methods

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#216]
@sanmitraghosh told me he didn't know of any theoretical basis for having an adaptation free period at the start of an adaptive MCMC routine.

Does anyone else have any ideas? The AdaptiveCovarianceMCMC methods seems to work fine if we start adapting straight away. @ben18785 @mirams ? Should we ask Remi about this?

**Comment by MichaelClerx** [comment]
Hi Ben! What are your thoughts on this?

**Comment by mirams** [comment]
Surely things that adapt according to covariance of chain need some samples to take covariance of to get started?

**Comment by ben18785** [comment]
Yep, I agree with Gary. Also, it’s relatively inexpensive to take a few initial samples...

**Comment by MichaelClerx** [comment]
That's not really the point! We just have this functionality built in that there's no published rationale for other than "everyone is doing it". You can gather initial samples while adapting. In fact, the methods seem to work fine if we enable adaptation from the start.

I don't mind, but just asking why we're doing this!

**Comment by mirams** [comment]
Always makes sense to propose wide and shrink down and learn what target looks like. Not to start with zero covariance/heavily biased covariance and grow up and potentially explore only one local minimum or one direction or both...
