### ISSUE TITLE
HH toy model has no values

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#217]
The `pints.toy.HodgkinHuxleyIKProblem()` class has no `_values` variable, which is assumed for pints problems

**Comment by martinjrobins** [comment]
Sorry, I created a pull request with a naive fix, but realised that I hadn't thought it through, so closed it.

Is this class a model or a problem. It sort of seems like a model, but is inheriting from SingleSeriesProblem. In which case, this class should have a _values, correct?

I added a commit that put in values, but realise now this does not make sense, as you would like to add noise etc. Perhaps this class should be a model instead?

**Comment by MichaelClerx** [comment]
Ah! You're right! I never thought about adding values, we should probably just generate some in the __init__ method?
Or maybe writing it as a `Problem` instead of a `Model` was a bad idea :-/

**Comment by MichaelClerx** [comment]
Ok, I'll rewrite as a Model!

**Comment by martinjrobins** [comment]
Yea, as a model is better. If you just generate values in the `init` then you have to decide whether or not you will add noise, what type of noise, how much noise etc.
