### ISSUE TITLE
Get DREAM mcmc into ask-and-tell interface

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#219]
Hi @ben18785, Can you help me with this when you get back?

**Comment by MichaelClerx** [comment]
Backup code in branch [issue#219dream](https://github.com/pints-team/pints/tree/issue%23219dream)

**Comment by ben18785** [comment]
@MichaelClerx Are we putting DREAM into this interface? Is it worth the effort?

**Comment by MichaelClerx** [comment]
It's done! (And yes)
