### ISSUE TITLE
Gradient Matching (fitting the slopes rather than absolute values)

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#22]
Following Gary's suggestion on slack

**Comment by martinjrobins** [comment]
requires #298

**Comment by MichaelClerx** [comment]
We can think of this in two ways:

1. Solving the ODE as usual, and then approximating a gradient for both the data & the simulation, and minimising those. This would fit in PINTS quite easily (could just be an error measure - even involving smoothing for the experimental data!)

2. Without solving the ODE, see e.g. https://www.frontiersin.org/articles/10.3389/fbioe.2015.00180/full

> To reduce the computational complexity, several authors have adopted an approach based on gradient matching [e.g., Calderhead et al. (2008) and Liang and Wu (2008)]. The idea is based on the following two-step procedure. In a preliminary smoothing step, the time series data are interpolated; then, in a second step, the parameters θ of the ODEs are optimized so as to minimize some metric measuring the difference between the slopes of the tangents to the interpolants, and the θ-dependent time derivatives from the ODEs. In this way, the ODEs never have to be solved explicitly, and the typically unknown initial conditions are effectively profiled over.

**Comment by MichaelClerx** [comment]
Still a good idea, but wondering if it's within scope (or if you'd just make a different model)

**Comment by MichaelClerx** [comment]
Can be done with errors, priors etc
