### ISSUE TITLE
Split tests and validation

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#221]
At the moment our tests do two things:

1. Test if we made programming errors (typos, things that return the wrong values, checks that fail)
2. Weakly test if the methods do what they should do (do optimisers converge? what is the mean of a sampled distribution?)

We've also got coverage testing, which goes in category 1.

I'd like to make this an explicit split, and move category 2 to a separate directory, perhaps called `validation`. @martinjrobins @jonc125 @sanmitraghosh do you know the accepted terminology for these two things?

**Comment by jonc125** [comment]
You can certainly set up one set of tests to run every push/PR, and have another set that run every week, say, and are longer. Which is probably appropriate for longer convergence tests and the like.

**Comment by MichaelClerx** [comment]
Don't think this makes sense anymore
