### ISSUE TITLE
Add thinning and warm-up to MCMCSampling

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#226]
default = off!

**Comment by ben18785** [comment]
@MichaelClerx Isn't this done already? Or does it need to be added to some variants?

**Comment by MichaelClerx** [comment]
We just do it manually now!

E.g.

chain = chain[1000:]

for warm-up, or

chain = chain[::10]

for thinning

I'm strongly inclined to leave it that way. People need to inspect the data before they discard part of it anyway!

**Comment by ben18785** [comment]
I agree!

**Comment by MichaelClerx** [comment]
Wondering if we need to add thinning on-the-fly anyway to reduce memory use for very long chains / high-dimensional problems
