### ISSUE TITLE
Add methods to optimisers/inferers to log an informative "state"

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#228]
For example, for adaptive covariance MCMC we might want to return the acceptance rate, whether or not adaptation is enabled, and maybe other parameters as well.

This could then be used to
- Log to screen (maybe using tabulate?)
- Log to disk

Note that this information is meant for humans to check on the method, not as a complete description of the object state (for that, see #194)

**Comment by MichaelClerx** [comment]
Tabulate only works when you have the whole table in memory, so not suitable for on-the-fly logging. Does anyone know of a popular, well-maintained alternative? I can't find one so might code something up myself. Shouldn't be more than 100 lines or so I'm guessing
@jonc125 ?

**Comment by jonc125** [comment]
Not sure exactly what you're after here, but you could just use Python's standard logging module with suitable handlers and formatters? I.e. have a named logger for this kind of informative output, that gets directed both to stdout/stderr and file (perhaps depending on user options).
