### ISSUE TITLE
Update documentation in Nested ellipsoid sampler

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#230]
Quick (maybe) question: @MichaelClerx I think the documentation in http://pints.readthedocs.io/en/latest/samplers/nested_ellipsoid_sampler.html#pints.NestedEllipsoidSampler.run for run() is not quite sufficient? 

Currently it has "See: `pints.MCMC.run()`", although I know you have not finished doing the documentation for the updated version of ask-and-tell interface in pints.MCMC.run(), but I think the two return different things -- right? Especially in the nested samplers, they have return as `(samples, marginal_log_likelihood)` but the other is just `chains`...?

And can we do something with the terms `chains` vs `samples`?

PS: please close this later if you are aware of it and are working on it... (Sorry! Just saw it and wanted to note it down somewhere before we, or I, forget about it.)

**Comment by MichaelClerx** [comment]
Hi @chonlei ! That's alright, it's good to point these things out!

It _is_ currently wrong, esp. after the changes I made. We'll need to fix this when we update the interface for nested samplers! (As part of #220)

Sorry about the temporary mess! It's just that so many things depended on this I wanted to merge it sooner than later. But in general yeah, this is _not_ the way we (I) should be doing things!
