### ISSUE TITLE
Name of LogPDF

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#237]
I'm a bit unsure of the name of the `LogPDF` class. It seems like a generic function that takes a vector input and a scalar output, not a PDF. It is unnormalised, so I don't see how you can sample from it, what if the output was > 1, or 0, or negative!

@ben18785 @sanmitraghosh @MichaelClerx

**Comment by MichaelClerx** [comment]
It is the _log_ of a function though, so it should be non-decreasing.

In general `-logpdf` is an error measure, but not every error measure can be used as a logpdf (since it doesn't have to be the log of anything)

**Comment by martinjrobins** [comment]
LogPDF does look better than LogFunction :) But are we able to call it a PDF, since it does not sum to 1?

**Comment by ben18785** [comment]
In Pints we have LogPosteriors and LogPDFs currently - both of which are
unnormalised. I personally prefer these to including the word
'unnormalised' there, as most of the time the distributions we are sampling
from are unnormalised. Happy if there are other names that are less
confusing though.

**Comment by MichaelClerx** [comment]
Related to this, how do we interpret the Rosenbrock function as a PDF? Does it make sense to do that?

**Comment by ben18785** [comment]
Yep, we can imagine the Rosenbrock function as an unnormalised pdf from
which we want to sample. It's used a fair bit in MCMC to test different
sampling algorithms because it has a tricky covariance structure.

**Comment by martinjrobins** [comment]
OK, if referring to an unnormalised function like Rosenbrock as a PDF is fairly well established in the literature I'm happy to go along with it, as I can't suggest a better alternative!
