### ISSUE TITLE
Add functional tests for optimisers

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#241]

**Comment by MichaelClerx** [comment]
I've added a test that optimises on the fitzhugh nagumo problem, and plots the final score with different settings for max_iterations. Any further ideas anyone?

**Comment by martinjrobins** [comment]
Looks great, thanks @MichaelClerx. Suggestion: I think that plotting the results versus commit sha would be more informative

**Comment by MichaelClerx** [comment]
Bit trickier, but think I've done it in: https://github.com/pints-team/functional-testing/commit/3cb0f09dec1d38cb8d851f20d148257d2bad0d38

**Comment by MichaelClerx** [comment]
We now have tests based on the logistic model, fitzhugh-nagumo model, and beeler-reuter model
