### ISSUE TITLE
Update examples and plotting functions: Change `chains` to `samples`

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#249]
Make sure that:

1. All plotting functions that take lists of samples (or 2d arrays) use `samples`, not `chains`
2. Some of the examples use `samples` rather than `chains`

**Comment by chonlei** [comment]
Should we have all of them in `samples`? (i.e. even the MCMC ones, we call them `samples` rather than `chain`? They all are under the `sampling` category anyway in our hierarchy of methods.)

**Comment by MichaelClerx** [comment]
The MCMC _methods_ can use the term chains, because that's accurate and appropriate there!

Plot methods should use `chains` if they're only useful for MCMC, and `samples` if they are also useful for other 2d arrays of samples.

> Should we have all of them in samples? 
Which ones do you mean exactly?

**Comment by chonlei** [comment]
Inside the MCMC classes, yes, I think they are fine, you are right.

But maybe in the examples? 

`chains = mcmc.run()` in https://github.com/pints-team/pints/blob/master/examples/inference-differential-evolution-mcmc.ipynb
and 
`samples = sampler.run()` in https://github.com/pints-team/pints/blob/master/examples/inference-nested-sampling.ipynb

Thought might be confusing to have them different in the examples. But if everyone thinks that is fine, then that is fine.

**Comment by MichaelClerx** [comment]
Hmmm... My feeling is our users should have some understanding of MCMC and other methods, and know things like that MCMC generates a markov chain. It's not the goal of Pints to teach people about stats, just to make a bunch of methods available and test them on our problems!
