### ISSUE TITLE
Investigate different methods of implementing boundaries

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#25]
Two options:

1. Implement a periodic transform on the parameter space (strategy used by CMA-ES, for example)
2. Implement a transform on the score function

**Comment by MichaelClerx** [comment]
Wrote a short script to explain triangle-transform (for my pints presentation today):

    #!/usr/bin/env python
    import numpy as np
    import matplotlib.pyplot as pl
    from matplotlib.patches import Rectangle

    lower = -4
    upper = 6
    r = upper - lower

    def transform(x):
        y = np.remainder(x - lower, 2 * r)
        z = np.remainder(y, r)
        return ((lower + z) * (y < r) + (upper - z) * (y >= r))

    x = np.linspace(-16, 18, 1000)
    y = transform(x)

    x2 = np.linspace(lower, upper)
    y2 = transform(x2)

    pl.figure()
    pl.xlabel('Parameters the optimiser sees')
    pl.ylabel('Parameters the model sees')
    pl.gca().add_patch(Rectangle((lower, upper), r, -r, alpha=0.1))
    pl.plot(x, y)
    pl.plot(x2, y2, lw=3)

    def f(x):
        return 0.02 * (x*2)**2 + 1.3 * np.sin((x - 0.5) * 1.4)


    pl.figure()
    pl.xlabel('Parameters the optimiser sees')
    pl.ylabel('Score the optimiser sees')
    pl.ylim(-2,  4.5)

    pl.gca().add_patch(Rectangle((lower, upper + 3), r, -14, alpha=0.1))

    x3 = np.linspace(lower - 5, upper + 5, 1000)
    pl.plot(x3, f(x3), 'g--')

    pl.plot(x, f(transform(x)), lw=3)

    pl.show()

![triangle-1 svg](https://user-images.githubusercontent.com/517644/31717142-b037a168-b402-11e7-8002-151c7b6bae54.png)

![triangle-2 svg](https://user-images.githubusercontent.com/517644/31717143-b04edb8a-b402-11e7-8712-d7c9d15698c3.png)

**Comment by MichaelClerx** [comment]
Some details:
- the transform creates infinite local minima, but as they all map to the same real parameter values this isn't a problem!
- the resulting landscape is continuous, but not smooth
- at the borders, you may get fake minima (example on the left) and maxima (example on the right), but this shouldn't be a huge problem for the optimisers. Especially since the best value usually won't be on the borders, but somewhere in the centre

**Comment by MichaelClerx** [comment]
> Not a problem for the answer you get back, but could create problems for the optimiser: imagine a swarm of points across the x axis in the bottom plot there, and a CMA-ES or particle swarm style minimisier now trying to push and pull them to converge together to a global minimum, it is going to struggle to converge properly even in 1D, and will have to do far more work than simpler approaches.

Shouldn't they be able to cope with this anyway, as it can easily happen within the boundaries?

**Comment by mirams** [comment]
Why not test it - run a 1D PSO on the above example with the boundaries defined each way and see how many forward evaluations you need...

**Comment by MichaelClerx** [comment]
It should be quite straightforward o implement different strategies and compare them though, if anyone wants to try!

See:
- [TriangleWaveTransform](https://github.com/pints-team/pints/blob/master/pints/_optimisers/__init__.py#L501-L532) just make a different one of these
- And then stick it in somewhere, for example in [xNES](https://github.com/pints-team/pints/blob/master/pints/_optimisers/_xnes.py#L86) 

[Our cmaes version passes the problem off to pycma](https://github.com/pints-team/pints/blob/master/pints/_optimisers/_cmaes.py#L84-L89) (which also uses an InfBoundaryTransform, that's where we got the idea), so you'd have to disable that if you want to check with CMA-ES itself

**Comment by MichaelClerx** [comment]
Another thought: If you optimise a `LogPosterior` with a `UniformPrior` but without a `Boundaries` object, you get an infinite jump at the boundaries already!

**Comment by mirams** [comment]
I think I need to see some examples. I can imagine optimisation with boundaries, and inference with a prior (that by definition defines boundaries). 

I can see that knowing where some boundaries are without evaluating prior PDFs could be useful for speed/convenience of calculations, but conceptually isn't that where they should go for inference problems? @ben18785 ?

**Comment by MichaelClerx** [comment]
In Pints, `Boundary` objects are only used in optimisation. For inference we typically use a `LogPosterior` made up of a `LogPrior` and a `LogLikelihood`. 
When evaluating a `LogPosterior` we assume that `LogPrior` evaluation is fast, and don't evaluate the `LogLikelihood` if the prior returns `-inf`
See: https://github.com/pints-team/pints/blob/master/pints/_log_pdfs.py#L132-L137

But you can stick a `LogPosterior` into an optimisation. If you'd do that without a `Boundaries` object, it'd run an unbounded optimisation (the optimiser woudn't know where the boundaries were) that would have an infinite jump at the boundaries implied by the prior

**Comment by MichaelClerx** [comment]
This touches a little bit on our discussions today, I guess @ben18785 @martinjrobins . Going back to the original issue:

- [x] Implement a periodic transform on the parameter space (strategy used by CMA-ES, for example)
- [ ] Implement a transform on the score function --> this can be done with #1070 

So then the remaining work on this issue would be

- [ ] compare both strategies for CMA-ES ?

**Comment by MichaelClerx** [comment]
Switching the controller from "best" to "best guessed" tracking shows that the triangle transforms do actually cause issues for xNES, at least.

Checking out `1411-best-vs-guessed` (see #1420) and running the script below a few times, occasionally results in a very long run and a failure to converge. Some debugging shows that these cases are always accompanied by out-of-bounds values, and an ever-increasing sigma.
Running without boundaries, these issues seem to go away

Probably best to remove the triangle transform idea from pints then...

```
#!/usr/bin/env python3
import pints
import pints.toy as toy
import numpy as np
import matplotlib.pyplot as plt

# Load a forward model
model = toy.LogisticModel()

# Create some toy data
real_parameters = [0.015, 500]
times = np.linspace(0, 1000, 1000)
values = model.simulate(real_parameters, times)

# Add noise
values += np.random.normal(0, 10, values.shape)

# Create an object with links to the model and time series
problem = pints.SingleOutputProblem(model, times, values)

# Select a score function
score = pints.SumOfSquaresError(problem)

# Select some boundaries
boundaries = pints.RectangularBoundaries([0, 400], [0.03, 600])

# Perform an optimization with boundaries and hints
x0 = 0.011, 400
sigma0 = [0.01, 100]
opt = pints.OptimisationController(
    score,
    x0,
    sigma0,
    boundaries,
    method=pints.SNES,
)
opt.set_f_guessed_tracking(True)
found_parameters, _ = opt.run()

# Show score of true solution
print('Score at true solution: ')
print(score(real_parameters))

# Compare parameters with original
print('Found solution:          True parameters:' )
for k, x in enumerate(found_parameters):
    print(pints.strfloat(x) + '    ' + pints.strfloat(real_parameters[k]))

# Show quality of fit
plt.figure()
plt.xlabel('Time')
plt.ylabel('Value')
plt.plot(times, values, label='Nosiy data')
plt.plot(times, problem.evaluate(found_parameters), label='Fit')
plt.legend()
#plt.show()
```
