### ISSUE TITLE
Handling `nan` (e.g. from simulation errors) throughout Pints

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#251]
It's quite possible for a simulation (arguably with a bad prior) to return values such as `nan` or `inf` or `-inf` in the simulated values.

Error measures involving these can end up as `nan` (any sum involving `nan`, or the combination of `+inf` and `-inf` in any way), or as `inf` (e.g. `(x - inf)**2`), or maybe as `-inf`, if we introduce some error measure that doesn't square everything.
Similarly `LogLikelihoods` would end up as `nan` or `-1 * inf = -inf`

I'm wondering what the best way to handle the `nan`s is! Perhaps we should catch this in the `ErrorMeasure` and `LogLikelihood` classes, and ensure that they always map to a single value (i.e. `inf` for an `ErrorMeasure` and `-inf` for a `LogLikelihood` ?

I think that way we won't have to deal with these cases in the optimisation / inference methods*

Any experience with these things in numerical software framework @mirams @jonc125 @martinjrobins ?

-----------

* Inequalities involving `inf` and `-inf` work as normal, e.g. `5 < inf` => `True`, `inf < -3` => `False`, while inequalities involving `nan` all evaluate to `False`: `5 < nan` => `False`, `5 > nan` => `False`, `5 == nan` => False.
This means that if you say accept a point if `nan > last_loglikelihood` it's fine, but reject if `nan < last_loglikelihood` would never work!
It'd be nice to avoid these delicacies as much as possible.

**Comment by MichaelClerx** [comment]
(Note that we'd still have to check if any external _optimisation_ methods can handle `inf`, if they'd prefer `nan`, or if there's something else we should do for them)

**Comment by martinjrobins** [comment]
I would be wary about mapping nan to inf. I'd like to know if my model was returning a nan (i.e. pints would throw some sort of error), because it would probably point to a mistake I'd made in the model.

**Comment by jonc125** [comment]
Yes, I think pints should say what models are allowed to return, and treat things outside this as errors. In other optimisers, I've had the model throw exceptions if something like this happens, and the optimiser treats that as an impossible parameter set. But you probably want at least to be able to log that this happens (or stop the optimiser if it happens a lot) because it may just be a bug in the model, not an intended consequence of bad parameters...

**Comment by MichaelClerx** [comment]
Agreed.
At the moment pints doesn't say anything. But `inf` and `-inf` will always be allowed, because we're dealing with logs a lot, and those arise naturally there.

I'd propose that `NaN`s are not allowed: If the parameter set cannot be evaluated users can simply return -inf (for loglikelihoods) or +inf (for error measures) and we don't need any special code to handle this!

Suspect that NaNs will crash things atm., so might be implicitly implemented already...

**Comment by MichaelClerx** [comment]
I think we're alright for this
