### ISSUE TITLE
Implement "stupid-mcmc" (also known as "prefetching")

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#26]
See:

1. Brockwell (2006) Parallel Markov chain Monte Carlo simulation by pre-fetching
2. Strid (2009) Efficient parallelisation of Metropolis-Hastings algorithms using a pre-fetching approach

**Comment by MichaelClerx** [comment]
I'm inclined to drop this issue, as @ben18785 has repeatedly pointed out that you shouldn't just do one chain (in parallel), you should do multiple and then compare them to see if they're acceptable!

We can already do multiple in parallel, so unless you have lots and lots of cores (not a trend in home computing at the moment) doing individual methods in parallel seems less desirable? @mirams ?

**Comment by mirams** [comment]
Yeah, certainly low enough priority to close for now. Have to keep scope sensible!
