### ISSUE TITLE
Plotting: better boundaries for histograms and pairwise plots

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#273]
Can we add the functionality to hide outliers in these plots, by setting the boundaries based on some clever measure (@chonlei has nice example using n-th percentile)? We could add an optional argument to disable this and revert to the current min/max behavior.

Can anyone spot any downsides to this idea?

**Comment by martinjrobins** [comment]
But the default behaviour for any plotting package is to show *all* the data, shouldn't we follow this by default? The optional argument could show the n-th percentile...

**Comment by chonlei** [comment]
I think the idea is to show _all_ the data by default, but then add an extra optional argument (on top of what we have right now) to show only the n-th percentile (just optional).

**Comment by MichaelClerx** [comment]
I would have made it default behaviour! But yeah maybe best to make the user request it explicitly...

**Comment by chonlei** [comment]
If this is just an optional argument, I can add this feature together with the PR #272.

**Comment by MichaelClerx** [comment]
Ok!
