### ISSUE TITLE
Optimisation runs into bug on windows

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#276]
Some issue with a random seed & max int size?

@chonlei Do you see this in Python 2.7?

**Comment by chonlei** [comment]
Did it terminate with an error or is it doing some weird things? No, I don't think I have seen any termination error other than the multiprocessing one. Do you have an example? I can test in on my machine.

**Comment by sanmitraghosh** [comment]
@chonlei get my 'multitrace' branch and run the optimisation in the Fitzhugh notebook with cmaes.

**Comment by MichaelClerx** [comment]
Not sure if we managed to reproduce this. Closing for now
