### ISSUE TITLE
Add example of customising plots

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#277]
Basically, an example where we do:

    fig, axes = pints.plot.some_plot(samples)
    for ax in axes:
        ax.plot(extra data)

For example we could add quartiles or mean + 1,2, and 3*sigma lines to a histogram

**Comment by chonlei** [comment]
@sanmitraghosh @MichaelClerx besides the sigma lines, is there anything else we want to add?

**Comment by MichaelClerx** [comment]
No, anything you do with the axes objects is fine!

**Comment by MichaelClerx** [comment]
@chonlei ?
