### ISSUE TITLE
Investigate other adaptive MCMC samplers

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#278]
See [this](https://people.eecs.berkeley.edu/~jordan/sail/readings/andrieu-thoms.pdf) paper.

**Comment by ben18785** [comment]
[This](https://amstat.tandfonline.com/doi/abs/10.1198/jcgs.2009.06134#.W4ssvtJKhPb) other paper by Rosenthal and Roberts has more variants.

**Comment by ben18785** [comment]
Interesting [paper](https://www.tandfonline.com/doi/pdf/10.1080/03610926.2014.936562?needAccess=true) that uses a Robbins-Monro process which they claim guarantees convergence of the optimal step length for RWM. They also implement it in adaptive routines and show it works well. Would be nice to include as a separate adaptive method for some samplers.

**Comment by ben18785** [comment]
Nice article by Rosenthal on adaptive MCMC (from Handbook of MCMC). Nice straightforward answers to questions about adaptive MCMC at the end. Also, good description of Metropolis-within-Gibbs.

**Comment by MichaelClerx** [comment]
Hi Ben! Is this all covered in the new adaptive mcmc classes?

**Comment by ben18785** [comment]
Yep!
