### ISSUE TITLE
Function to benchmark all possible sampling algorithms on a given model

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#285]
Create a function that evaluates number of effective samples per second across all possible sampling algorithms for a given model. To minimise computational cost, a fixed runtime could be applied for each model run. To minimise the search space of sampling algorithms (if specified), we could just pick one sampler from each of the main classes.

This is similar to #229 so expect this function exists @martinjrobins ? This may be what you were already thinking so forgive me if this is a repetition. I wasn't sure whether the exercise in #229 was going to be something for users or something for the paper or both.

**Comment by martinjrobins** [comment]
Yea, this is in #229, but my plan was that it was something for the paper (that would eventually be a separate repository in the pints_team organisation). It would be nice to export some of this into pints, as long as we can reduce the run-time to a sensible number.

**Comment by MichaelClerx** [comment]
Definitely something we should have, but agree with martin that we should very carefully if this is Pints or something on top of Pints! Could easily have a extra pints-team repos for this

**Comment by MichaelClerx** [comment]
Now thinking this is too big a thing to just have one function for. @martinjrobins has been doing it and it's a lot of work, requires bayesian parameter tuning, and even then tweaks etc.

Out of scope!
