### ISSUE TITLE
Add ESS stopping criteria to mcmc

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#290]

**Comment by MichaelClerx** [comment]
See also #70

**Comment by ben18785** [comment]
I'd pull a @MichaelClerx argument on you here @MichaelClerx : "this would make the MCMCController object more complicated and could be done using ask/tell". Haha. So, how about we drop this? :}

**Comment by MichaelClerx** [comment]
😄 😄 😄 

Implementing shared stopping criteria is already something the controllers do though, and we intended to have more than one stopping crit. right from the start, so I don't quite agree with your reasoning there

But happy to drop any issues we don't think are useful
