### ISSUE TITLE
Implement delayed acceptance adaptive Metropolis (DRAM)

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#295]
Described [here](https://bmcsystbiol.biomedcentral.com/articles/10.1186/s12918-017-0433-1).

**Comment by ben18785** [comment]
[This](https://www.researchgate.net/profile/Marko_Laine/publication/220286586_Dram_efficient_adaptive_MCMC/links/00b49520541c0c66d0000000.pdf) is a more thorough description of DRAM. Interesting in that, by allowing multiple proposals (and rejections), it is possible to incorporate kernels that search both short and long distances, and also allows the ratio between short and long proposals to change over time: potentially you'd want to do longer steps to begin with to globally explore, followed by shorter steps later on when you're more confident in what you've found.

I see no problem of using DRAM in tempered sampling methods like SMC and population MCMC.

@MichaelClerx @martinjrobins A difficulty with this may be how to fit it into ask/tell. Since we would be repeatedly calling ask (albeit with potentially different kernels) for one given iteration. What do you think?

**Comment by MichaelClerx** [comment]
I think we could alter the scheme to work like this:

    chain = []
    for iteration in range(1, max_iter):
        sample = None
        while sample is None:
            x = sampler.ask()
            fx = evaluate(x)
            sample = sampler.tell(fx)
        chain.add(sample)

so that the sampler could ask for multiple evaluations before returning a new sample.

**Comment by ben18785** [comment]
Sorry being slow here... Is None what the sampler returns if it rejects the proposal?

**Comment by MichaelClerx** [comment]
No it returns the next sample in the chain! So if it accepts or rejects a sample it returns the next sample in the chain (the proposal if accepted, else the previous sample). If it's not in a position to accept/reject yet it returns `None`.

**Comment by ben18785** [comment]
Ok, makes sense. I think I see how to proceed here, thanks.

**Comment by MichaelClerx** [comment]
Great! Note that the above scheme isn't actually implemented yet, just saying that's how we could do it :D 

The place to make changes would be in the docs here: https://github.com/pints-team/pints/blob/master/pints/_mcmc/__init__.py#L77-L83
And here: https://github.com/pints-team/pints/blob/master/pints/_mcmc/__init__.py#L205-L211

Then update the code here: https://github.com/pints-team/pints/blob/master/pints/_mcmc/__init__.py#L398-L416

And run all the tests to check if all the samplers still work. Would advise doing this in a separate ticket if we find it's really necessary! Thoughts @martinjrobins ?

**Comment by martinjrobins** [comment]
No new thoughts from me, what you suggest sounds sensible.
