### ISSUE TITLE
Investigate bridging distribution options for population MCMC and SMC

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#296]
There are two options available: `p(theta|x)^(1-T)` or `p(theta|x)^(1-T) p(theta)^T`, where `p(theta|x)` is the posterior and `p(theta)` is (typically) the prior. At the moment we do the former, but a real mix is used in the literature.

**Comment by MichaelClerx** [comment]
Do you propose that we implement both? Or that we figure out what the best one is?

**Comment by MichaelClerx** [comment]
Actually, I strongly prefer the current version as we can work with any logpdf, and don't need to know about priors / posteriors

**Comment by ben18785** [comment]
I was thinking we allow both options. For logPDFs we could just use another distribution (rather than the prior) as a bridging distribution. Think it’d be good to compare their performance, if possible.
