### ISSUE TITLE
implement gradients/sensitivities for toy problems

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#298]
Many other tickets refer to gradient based methods (#22 #283 #293 #104). First step is to implement gradients for the toy problems

- [x] AnnulusLogPDF
- [x] ConeLogPDF
- [x] ConstantModel
- [x] EightSchoolsLogPDF
- [x] FitzhughNagumoModel
- [x] GaussianLogPDF
- [x] GermanCreditLogPDF
- [x] GermanCreditHierarchicalLogPDF
- [x] GoodwinOscillatorModel 
- [x] HighDimensionalGaussianLogPDF
- [x] LogisticModel
- [x] LotkaVolterraModel
- [x] MultimodalGaussianLogPDF
- [x] NealsFunnelLogPDF
- [x] ParabolicError
- [x] RosenbrockLogPDF
- [x] SimpleHarmonicOscillatorModel
- [x] SimpleEggBoxLogPDF
- [x] TwistedGaussianLogPDF

Not doing:
- ActionPotentialModel: odeint
- Hes1Model: odeint
- HodgkinHuxleyIKModel: Separate ticket #650 
- MarkovJumpModel: stochastic simulation algorithm
- RepressilatorModel: stochastic simulation algorithm
- RosenbrockError: Can use pdf instead
- SIRModel: stochastic simulation algorithm

**Comment by MichaelClerx** [comment]
I don't think we need it for all problems, do we? I don't want us to get carried away doing lots of nice gradient-based stuff when in real life we hardly ever have them.

(I know there's ways to get them, but they've been around for decades and still don't see much use, that worries me!)

**Comment by martinjrobins** [comment]
probably start by doing for one easy problem and one hard one to get an idea of how the gradient-based stuff works (presumably after that we can just say "nope, doesn't work").

**Comment by MichaelClerx** [comment]
See also #43 #118

**Comment by martinjrobins** [comment]
I'll wait until @sanmitraghosh verifies the correctness of the fitzhugh nagumo sensitivities before I merge it in...

**Comment by ben18785** [comment]
Good stuff @martinjrobins - thanks for doing this.

**Comment by sanmitraghosh** [comment]
@martinjrobins corrected the FN model in your branch. Have a look.

**Comment by sanmitraghosh** [comment]
I think its pretty easy to test if the sensitivities are correct by using theano gradient test. I am attaching here a theano test file I have written for the FN model.
 [theano_test_pintsToy.zip](https://github.com/pints-team/pints/files/1860399/theano_test_pintsToy.zip)
Assuming theano is installed, run
theano-nose test_pintsModelSens.py

**Comment by martinjrobins** [comment]
Thanks @sanmitraghosh  for testing the gradient

**Comment by sanmitraghosh** [comment]
@martinjrobins I have uploaded these files now in master branch studies folder. commit issue-298-sensitivities

**Comment by MichaelClerx** [comment]
Now that we have an easy one and a hard one, shall we close this ticket?

**Comment by MichaelClerx** [comment]
@martinjrobins says yes

**Comment by ben18785** [comment]
@martinjrobins @MichaelClerx Think we do need this for the toy pdfs (and they're easy to do) so am reopening.

**Comment by MichaelClerx** [comment]
@ben18785 which ones specifically? Can you update the list at the top?

**Comment by ben18785** [comment]
@MichaelClerx Have done so. I am happy to add these to be honest -- shouldn't take too long for the toy pdfs.

**Comment by MichaelClerx** [comment]
I think we've got plenty now that have sensitivities, so closing this!

**Comment by ben18785** [comment]
Not sure we have many toy models (not toy distributions). Can we keep this
open please?

**Comment by MichaelClerx** [comment]
If you have some idea for how to implement it, then yes. The ones I've looked at (SIR, hes1, Lotka-Volterra, Repressilator) all use scipy to integrate an ODE, so don't offer an easy way to obtain the sensitivities.
This is fine by me, as it reflects the real-world situation

**Comment by ben18785** [comment]
Yep, I think either getting sensitivities via the Jacobian method or
(better) using adjoints is fine. I'd also be happy if this were implemented
in a notebook to show others how to do it...

**Comment by MichaelClerx** [comment]
Well, feel free! But maybe we should pick a specific model and create an issue for that? I don't want to give the impression that it's a requirement for all toy models/problems to have sensitivities implemented

**Comment by martinjrobins** [comment]
pretty sure the fitzhugh nagumo model uses the Jacobian method to get the sensitivities

**Comment by MichaelClerx** [comment]
Perhaps see https://github.com/pints-team/pints/issues/501

**Comment by MichaelClerx** [comment]
https://github.com/pints-team/pints/issues/650

**Comment by MichaelClerx** [comment]
Is that enough to play with @ben18785 ? Can we shut this issue now?

**Comment by MichaelClerx** [comment]
Many addressed in  #1038 now. I'd be happy to shut this issue

**Comment by ben18785** [comment]
Let's keep it open as have a few ones here I still want to implement

**Comment by MichaelClerx** [comment]
Some more weren't ticked off. Remaining ones are all tricky. Closing this as initial issue (need for some gradients to test gradient-based samplers) has been more than met.
