### ISSUE TITLE
Add example notebook showing user's own custom likelihood or prior

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#303]
Not sure if this is currently possible but it is a really useful feature (Stan has it, for example). Inevitably there are situations when users will want to place different priors on parameters or use different likelihoods to what we have. Having this functionality or, at least, demonstrating using a Jupyter notebook how to do this, would allow Pints to be extensible without us having to extend it!

**Comment by chonlei** [comment]
I think that is definitely possible with what we have in Pints. I think we have a jupyter notebook for how to make a custom prior, @MichaelClerx did that already. And we can do a custom likelihood example too if needed or if we have a good example? Before we had the multiple series option, that is how I dealt with it – make a custom likelihood.

**Comment by chonlei** [comment]
See this one, e.g., https://github.com/pints-team/pints/blob/master/examples/writing-a-prior.ipynb

**Comment by ben18785** [comment]
That’s great Chon, thanks. Yes, I think a custom likelihood example would be good too.

**Comment by MichaelClerx** [comment]
Ben, if you can think of a good example feel free to add it!

It's easy to do, just implement the [LogLikelihood](http://pints.readthedocs.io/en/latest/log_pdfs.html#pints.LogLikelihood) interface for Bayesian stuff, or the [LogPDF](http://pints.readthedocs.io/en/latest/log_pdfs.html#pints.LogPDF) interface for anything else.

**Comment by MichaelClerx** [comment]
https://github.com/pints-team/pints/blob/master/examples/writing-a-logpdf.ipynb

https://github.com/pints-team/pints/blob/master/examples/writing-a-prior.ipynb
