### ISSUE TITLE
Reduction to univariate form

### ISSUE THREAD

**Issue by sanmitraghosh** [pints-team/pints#304]
@MichaelClerx  Are you using a univariate normal for a multiseriesproblem? If not then ignore and close this.

Otherwise, the likelihood should be product (across n_outputs) of multivariate normals. Now as I have used a diagonal covariance thus for one of the n_outputs the likelihood reduces to product of univariates on each time points. However, in this case there should one product (sum in log) across n_outputs also. 

But more importantly I used the same sigma for all outputs just for the FN toy model.  In general we should allow different sigma's for different states, always for unknownnoise. I should have coded up with that to start with. Sorry for that.

 It is thus easy to work and organise using multivariate form for multiseries. More consistent with standard literature.  Thus I think we should revert back to MvNormals.

**Comment by MichaelClerx** [comment]
Hi @sanmitraghosh !

We currently use an independent sigma for each output, and at the end sum the log likelihoods of the different outputs together.

Is that ok?

(The things I've seen described as multivariate typically assume you want a covariance matrix of size `n x n` where `n` is the number of points in your data set. For us this would mean we assume some kind of covariance between points at time `t[i]` and `t[j]` which is not really what we're after.)

**Comment by MichaelClerx** [comment]
Had a chat, fixed!
