### ISSUE TITLE
Add methods to search in transformed parameter space

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#31]
Ideally, this would automatically update priors too, somehow...?

**Comment by mirams** [comment]
does this mean transforming parameter sets to make optimisation easier?

**Comment by MichaelClerx** [comment]
Yes

**Comment by MichaelClerx** [comment]
@martinjrobins Would we need separate methods for dimensionalising / non-dimensionalising, or is this the same thing?

**Comment by martinjrobins** [comment]
not the same thing, dimensionalising is the inverse of non-dimensionalising. So I think separate methods would be suitable.

**Comment by MichaelClerx** [comment]
Ok! What would a good workflow be?

I'm guessing something like this:

1. Define `Boundaries` and (optionally) a `Prior` in ordinary parameter space
2. (Optional) Define a methods to dimensionalise and a method to non-dimensioanlise
3. (Optional) Define a method to perform some arbitrary transform to a nicer parameter space, and a method to do its inverse
4. Pass everything to pints, receive a solution in ordinary parameter space

Internally:
- Initial guesses would be in ordinary space, but then (forward) transformed by Pints before passing them to optimisers
- Methods such as CMA-ES would generate new guesses in the transformed space, and Pints would then (inverse) transform these back to ordinary space for the model
- Methods that want to sample from the prior would have to know to apply the forward transformations to the samples before using them
- The final result would be in transformed space, so Pints would have to (inverse) transform them before handing back to the user

**Comment by MichaelClerx** [comment]
So I think dimensionalising/non-dimensionalising is just a type of conditioning with extra semantics?

Would maybe be easiest to only have one pair of forward/inverse transformations, and have model wrapper writers execute multiple transforms inside these methods if required?

**Comment by martinjrobins** [comment]
Perhaps the user should just define everything in non-dimensional parameter
space? Because if you send dimensional parameters to the model, it will
just have to non-dimensionalise them anyway. Plus, the non-dim is set only
once, and you wouldn't normally change it (so not too onerous for a user).
But you might want to try different conditioning transforms to see the
effect on the fitting.

**Comment by MichaelClerx** [comment]
Ok, in that case I think (non-)dimensionalising is something that happens outside of Pints, so will just be part of the wrapper code / code using Pints

**Comment by mirams** [comment]
If your model is non-dimensionalised, then yeah, definitely keep the parameters nondimensional. 

That's a bit different to the scalings to assist with minimization though (which could apply to dimensional or nondimensional data, or optionally include the nondimensionalisation step) - might be nice to have a small collection of 'sensible things to try' that were classes or objects in pints. e.g. Log scalings, direct 0->1 scalings, Ross' power scalings

In terms of us using PINTS as a prototype for WebLab fitting, it is definitely something the WebLab fitting will want to capture...

**Comment by MichaelClerx** [comment]
Ok! But I don't think we need to transform priors!

- If you've defined a prior on the original space, just make sure the method knows to transform post sampling. No need to work out what the transformed distribution looks like.

- If you want to define a prior on the transformed space, i.e. you're thinking in that space, then update your model to use that space in the first place!

**Comment by mirams** [comment]
Not sure about that. We should consider Ross' conductance scalings as an example...

**Comment by MichaelClerx** [comment]
From which paper?

**Comment by MichaelClerx** [comment]
Trying to imagine what this would look like in Pints.

## Option 1, we let the user handle it:

```
class TheUsersModel(pints.ForwardModel):
    def simulate(self, parameters, times):
        # The first 4 parameters are log-transormed
        parameters[:4] = np.exp(parameters[:4]
...

# Define boundaries
lower = [...]
upper = [...]
# Apply log-transform to boundaries
lower[:4] = np.log(lower[:4])
lower[:4] = np.log(lower[:4])
# Create boundaries object
boundaries = pints.Boundaries(lower, upper)
```
With this method, we don't change anything in Pints at all.

This is easy enough, I think, but maybe we'd want something where Pints does more and the user does less?

## Option 2, we handle it with lots of objects

```
class TheUsersModel(pints.ForwardModel):
    def simulate(self, parameters, times):
...

# Define boundaries
lower = [...]
upper = [...]
# Create boundaries object
boundaries = pints.Boundaries(lower, upper)

# Create log transform (using some short of shorthand)
transform = pints.ComposedParameterTransform(
    'log', 'log', 'log', 'log', None, None, None, None)

model.add_parameter_transform(transform)
boundaries.add_parameter_transform(transform)
```

We could make this work by having model.simulate() be a method of the abstract `ForwardModel` class and then having all implementing classes have a `model._simulate` instead that remembers to check for any boundary transforms.
I'm not a huge fan of this, as it means (1) we make the interface to ForwardModel a (tiny) bit more complicated and (2) the user still needs to remember to pass the transform to boundary and prior objects.

## Option 3, We make the mcmc and optimisation methods handle this

```
class TheUsersModel(pints.ForwardModel):
    def simulate(self, parameters, times):
...

# Define boundaries
lower = [...]
upper = [...]
# Create boundaries object
boundaries = pints.Boundaries(lower, upper)

# Create log transform (using some short of shorthand)
transform = pints.ComposedParameterTransform(
    'log', 'log', 'log', 'log', None, None, None, None)

...

optimiser = pints.CMAES(score, boundaries=boundaries, transform=transform)
```

This has the advantage that we define the transform as something used only by the optimiser, i.e. not actually a property of the model. However, it means we need to implement this separately for every optimisation or inference method we add.

## Conclusion?
I'm leaning towards option 1, let the user sort it out

(With respect to the web lab, one of the things the web lab code will do is define `ForwardModel` objects with the cellml models, simulator, etc., This will be responsible for creating the parameter vector for the user-define parameters and linking it to the simulation, I don't see why this couldn't include log-transforming a few of them as well).

**Comment by MichaelClerx** [comment]
If we choose method 1, we can still add an example to the example pages showing how it's done

**Comment by martinjrobins** [comment]
I'm happy to go with option 1, I'll do up an example for this

**Comment by martinjrobins** [comment]
Example done, I'm going to close this as complete.

**Comment by mirams** [comment]
They end up being a bit more complicated than one line when different mappings happen on different parameters etc., and you might even want to test that you have defined the two mappings properly by putting parameters through both transforms! 
e.g. here are two I just wrote for a real 5D problem (in C++!):

```c++
    /** The hard lower bounds to explore in the optimisation -  asymptotes */
    const double mLowerBounds[5] = { -8.0, -9.0, 0.5, -3, -200.0 };

    /** The hard upper bounds to explore in the optimisation -  asymptotes */
    const double mUpperBounds[5] = { 8.0, 0.0, 2.0, 9, 200.0 }; // arrays for lower and upper parameter bounds, respectively

    /** Whether to sample each parameter logarithmically or not (bounds above are to power 10 for the 'true' ones here). */
    const bool mSampleWithPowers[5] = { true, true, false, true, false };

    /**
     * External (real) to internal (CMA-ES) parameter mapping.
     *
     * @param externalParams  the external parameters to convert to CMA-ES's internalParams
     * @param internalParams  the internal CMA-ES parameters (filled by this method).
     * @param dim  the dimension of the parameter vector.
     */
    libcmaes::TransFunc genof = [this](const double* externalParams, double* internalParams, const int& dim) {

        for (int i = 0; i < dim; i++)
        {
            double working_param = externalParams[i];
            if (mSampleWithPowers[i])
            {
                working_param = log10(working_param);
            }
            internalParams[i] = atanh(2.0 * ((working_param - mLowerBounds[i]) / (mUpperBounds[i] - mLowerBounds[i])) - 1.0);
        }
    };

    /**
     * Internal (CMA-ES) to external (real) parameter mapping
     *
     * @param internalParams  the internal CMA-ES parameters to convert to externalParams
     * @param externalParams  the external parameters (filled by this method).
     * @param dim  the dimension of the parameter vector.
     */
    libcmaes::TransFunc phenof = [this](const double* internalParams, double* externalParams, const int& dim) {
        for (int i = 0; i < dim; i++)
        {
            externalParams[i] = mLowerBounds[i] + (mUpperBounds[i] - mLowerBounds[i]) * (tanh(internalParams[i]) + 1.0) / 2.0;
            if (mSampleWithPowers[i])
            {
                externalParams[i] = pow(10.0, externalParams[i]);
            }
        }
    };
```

and the correct one needs to get called whenever:
 * specifying bounds (if separate to transform, they are actually included here with the `tanh` in my example),
 * initial guess(es), 
 * doing forward evaluations, 
 * getting/printing out solutions. 

I guess you could write the two conversion methods yourself and then call them in all these places, but having a simple (optional) interface to do this for you if you just provide two methods is nice. If nothing else it saves you getting in a muddle over which of the two methods needs to be called, and whether or not you are in transformed space or not!

**Comment by martinjrobins** [comment]
I'm with @MichaelClerx on this, don't think the benifit-to-work ratio is high enough to provide a custom interface for this.

**Comment by MichaelClerx** [comment]
Been discussing this with Gary & Chon and thinking about it again today.

Wondering if this is a simple solution:

```
class ParameterTransform(object):
    """ An interface for parameter transformations """

    def n_parameters(self):
        """
        Returns the dimensionality of the space this transform is defined on.
        """
        raise NotImplementedError

    def transform(self, x):
        """
        Transforms a parameter vector ``x`` in model-space to an equal-sized
        vector ``y`` in search-space.
        
        Typically, ``x`` would contain real physical parameters as used by a
        model, while ``y`` would contain parameters with a less-clear physical
        meaning but in an easier-to-explore space. The ``x:y`` mapping should
        be ``1:1``.
        """
        raise NotImplementedError
    
    def detransform(self, y):
        """
        Transforms a parameter vector ``y`` in search-space back to
        model-space.
        
        See :meth:`ParameterTransform.transform`.
        """
        raise NotImplementedError
```
Then, we would make `MCMCSampling`, `Optimisation`, and all the other "engines" take a `ParameterTransform` as an optional constructor argument (or via a set method). So we _wouldn't_ implement it in any of the individual methods, and users using ask-and-tell directly would need to do their own transformations. But it _would_ work as a convenience thing (which is what 99-100% of users do).

So in e.g. MCMCSampling it would use the transform to:
  1. Change the user's ``x0``. Not sure if we could also do the sigma! Any ideas? @mirams ?
  2. Detransform before checking boundaries or evaluating priors
  3. Detransform before evaluating the loglikelihood/error
  4. Detransform before storing or outputting

Difficulties I can see just now are:

1. Can we use an arbitrary transform to transform the user-given sigma as well?
2. How do we go about checking rectangular boundaries? E.g. in cma-es we just tell `cma` what the lower and upper boundaries are, but will this still work if we allow transforms that reverse sign (reasonable) or perform some non-monotonic (but reversible) transform (a bit insane but maybe could happen?)

@mirams @martinjrobins ?

**Comment by MichaelClerx** [comment]
One nice thing is if we do it in the wrappers, we don't have to do it in every single method ever.
Another nice thing is if we do it before the output, we don't have to update any plot or analysis methods etc.
@ben18785 how would e.g. an R-hat or an effective-sample measure be affected if you detransform the chain (so from easy search-space back to meaningful, user-friendly model-space) _before_ evaluating these diagnostic measures? Because that's a consequence of what I'm suggesting...

**Comment by MichaelClerx** [comment]
Thinking about MCMC a bit more, I guess that only makes sense if transformations are monotonic right? What I mean is, an ordered sequence of (1-dimensional) points a < b < c < d can only be transformed to a sequence f(a) < f(b) < f(c) < f(d) or -f(a) < -f(b) < -f(c) < -f(d). There's bound to be a nice spacey way to say this. Points near each other stay near each other, right? Otherwise the MCMC on a transformed space won't make any sense?

**Comment by mirams** [comment]
I'm wondering whether this would work most nicely if the parameter arguments themselves were all overloaded with an optional simple little `CleverParameter` class that stored a parameter vector but also could store/point to a forwards and backwards transform, and knew which one they currently were. Then whatever class was using the parameters for something (an initial guess, a bound, to run a simulation, to print out error message) could get hold of the appropriate transform methods and map to the right set of parameters for the given task.

I think it definitely has to be monotonic, or otherwise it isn't a 1:1 reversible mapping and all hell breaks loose. (which is why I don't like that sawtooth/periodic solution to imposing boundaries!). Presumably bounds could just be re-ordered after transformation if needed?

**Comment by MichaelClerx** [comment]
> I'm wondering whether this would work most nicely if the parameter arguments themselves were all overloaded with an optional simple little CleverParameter class that stored a parameter vector but also could store/point to a forwards and backwards transform, and knew which one they currently were.

I quite like that idea, but I'm not sure how much simpler it'd make things, as now creating a new point would require you to get the relevant transform from an existing point so that you could pass the reference on!

**Comment by MichaelClerx** [comment]
> I think it definitely has to be monotonic, or otherwise it isn't a 1:1 reversible mapping 

You could do something like swap the intervals [0,10] and [10, 20] to create a reversible 1:1 mapping that isn't monotonic though, right?

**Comment by mirams** [comment]
Yes, there are other reasons it should be monotonic too!

**Comment by mirams** [comment]
Ummm, I think 10 would then take two disjoint values in the transformed space. Yes - you want some continuity notion of things staying close to each other after the transform too. Monotonic gives you that.

**Comment by MichaelClerx** [comment]
Well, half-closed ones [0, 10) and [10, 20) then :D
But yes agreed it's a good idea for parameter transforms to be monotonic

**Comment by MichaelClerx** [comment]
At the Cside competition yesterday, it was all about who'd set the best boundaries and applied the best transforms. Nobody really talked methods :-D
So slapping a priority label on this

**Comment by MichaelClerx** [comment]
@MaksymPetyak this is the issue where we've been discussing parameter transforms!

I think the summary was to just allow 2 functions to be given to `MCMCSampling` and `Optimisation` that can perform the forward and backward transformation on a parameter vector. Tricky bits are introduced by boundary checking and methods that take a `sigma` as well as an `x0` as constructor arguments.

Regarding decorators and pythonicness, I would prefer to keep the use of advanced language constructs (we can argue over what that means) to a minimum, so that we can make use of a wide developer base and make it easy for non-expert users to read and use our code

**Comment by MichaelClerx** [comment]
If you think this proposal would solve your problems you could take it on first, get it merged and then build on that in your project. If not, it'd be great to see how you solve it, and work to get these related problems solved in as similar as possible a way

**Comment by chonlei** [comment]
> Been discussing this with Gary & Chon and thinking about it again today.
> 
> Wondering if this is a simple solution:
> 
> ```
> class ParameterTransform(object):
>     """ An interface for parameter transformations """
> 
>     def n_parameters(self):
>         """
>         Returns the dimensionality of the space this transform is defined on.
>         """
>         raise NotImplementedError
> 
>     def transform(self, x):
>         """
>         Transforms a parameter vector ``x`` in model-space to an equal-sized
>         vector ``y`` in search-space.
>         
>         Typically, ``x`` would contain real physical parameters as used by a
>         model, while ``y`` would contain parameters with a less-clear physical
>         meaning but in an easier-to-explore space. The ``x:y`` mapping should
>         be ``1:1``.
>         """
>         raise NotImplementedError
>     
>     def detransform(self, y):
>         """
>         Transforms a parameter vector ``y`` in search-space back to
>         model-space.
>         
>         See :meth:`ParameterTransform.transform`.
>         """
>         raise NotImplementedError
> ```
> Then, we would make `MCMCSampling`, `Optimisation`, and all the other "engines" take a `ParameterTransform` as an optional constructor argument (or via a set method). So we _wouldn't_ implement it in any of the individual methods, and users using ask-and-tell directly would need to do their own transformations. But it _would_ work as a convenience thing (which is what 99-100% of users do).
> 
> So in e.g. MCMCSampling it would use the transform to:
> 
> 1. Change the user's `x0`. Not sure if we could also do the sigma! Any ideas? @mirams ?
> 2. Detransform before checking boundaries or evaluating priors
> 3. Detransform before evaluating the loglikelihood/error
> 4. Detransform before storing or outputting
> 
> Difficulties I can see just now are:
> 
> 1. Can we use an arbitrary transform to transform the user-given sigma as well?
> 2. How do we go about checking rectangular boundaries? E.g. in cma-es we just tell `cma` what the lower and upper boundaries are, but will this still work if we allow transforms that reverse sign (reasonable) or perform some non-monotonic (but reversible) transform (a bit insane but maybe could happen?)
> 
> @mirams @martinjrobins ?

Not sure what state we are at for this, but I think the above set up is the cleanest thing to do.

However, two more points below:

1. I am not sure how we are going to transform the prior in this case! Unless we have another two methods `transform_s1` and `detransform_s1`, we cannot work out the prior in the transformed space(?!). Or easiest solution would be if there is not `_s1` provided, then we should warn the users that prior is _not_ transformed! Since we need `P(y) = P(x) * dx/dy` where `y = g(x)` with transformation function `g`!

```
def transform_s1(self, x):
   """
   Derivative of the transformation function.
   """
   raise NotImplementedError

def detransform_s1(self, x):
   """
   Derivative of the detransformation function.
   """
   raise NotImplementedError
```

2. for MCMC, I am not sure should we return the transformed parameter or detransformed ones, as for the case in Cside, transformed ones look more sensible to look at. Though I am happy to stick to detransformed parameters (original model parameter space).

**Comment by MichaelClerx** [comment]
What do you mean by 1? We evaluate the prior and the loglikelihood in untransformed space. In fact, remember the MCMC method doesn't even know about priors and likelihoods, it just has a LogPDF which may or may not be a LogPosterior.

The whole point of the proposal is making it so that users _don't_ see the transformed points :-)
If they want to see the transformed points then they should just do it themselves and work in those points everywhere :-)

**Comment by MichaelClerx** [comment]
What do you mean by 1? We evaluate the prior and the loglikelihood in untransformed space. In fact, remember the MCMC method doesn't even know about priors and likelihoods, it just has a LogPDF which may or may not be a LogPosterior.

For 2: The whole point of the proposal is making it so that users _don't_ see the transformed points :-)
If they want to see the transformed points then they should just do it themselves and work in those points everywhere :-)

**Comment by chonlei** [comment]
Yeah, can forget about 2 maybe!

For 1, on second thought, maybe I just over-thought about it... (maybe just see what I say before make sense or not!)

Yes, we evaluate the prior (and the loglikelihood) in untransformed space. And we want to make the _LogPDF in the transformed space_ (the whole point of doing transformation?!). Then I was thinking for the LogPrior, when we say 'uniform' LogPrior, we mean flat and uniform in the _untransformed space_ (_right?_), but they are _not uniform_ for LoPDF in the transformed sapce (_and this is OK, right?_).

**Comment by MichaelClerx** [comment]
> And what we are up to for this? Any PR for this?
> Since I am using this quite a lot, I would like to get involved and help out!

No PR yet! I'd be very happy if you made one.

Possible to-do list:

- [ ] Define transform class
- [ ] Start writing example notebook
- [ ] Implement transforms in optimisers --> they handle boundaries themselves!
- [ ] For CMAES, make sure lower and upper are still correct for rectangular boundaries, for non-rectangular do checking ourselves. Alternatively override CMA-ES's boundary scheme and do it ourselves (we do this already for XNES anyway)
- [ ] Implement transforms in MCMCSampling --> they don't have boundaries
- [ ] Figure out what to do with covariance matrices

**Comment by chonlei** [comment]
For sigma or covariance matrices, we could do linear approximation. I have done that privously and it seems to work, but that, if I remember correctly, it requires the first order derivative to do linear approximation (or higher order for better approximation). 

One other note, here I think, we are not restricting any combination kind of transform... for example,
```
x' = ax + by
y' = cx + dy
```
where `x', y'` are transformed parameters and `x, y` are the original paramters, is also a valid transformation, right? (Not sure why one would like to do that, but is possible...)

But not sure if that is a good idea, because sigma or cov matrix in transformed and untransformed space looks quite different... Though I think I have done that before, so think it is still feasible, if one provides the `_s1` thing for the transformation...

**Comment by MichaelClerx** [comment]
Trying to implement this just now, kind of come full circle, it's just pretty hard to do this everywhere! So now once again thinking letting the user do it is the best thing. That means users either write their ForwardModel class to accept parameters in transformed space, or wrap something around it to make it do that. From then on, they work in transformed space...

**Comment by MichaelClerx** [comment]
One thing we could perhaps do is provide a log-transform wrapper for models? Seems a common case...

**Comment by MichaelClerx** [comment]
As in this example: https://github.com/pints-team/pints/blob/master/examples/optimisation-transformed-parameters.ipynb

**Comment by MichaelClerx** [comment]
Summary: It doesn't make sense to have users define everything in model space and then try to convert all of this automatically to search space. If the search space is better behaved, users should just do everything in that search space and transform/detransform before simulations. Otherwise we have to figure ways to transform e.g. covariance matrices and partial derivative matrices. The best way to do this is probably problem-dependent, so best just avoid this problem altogether...
