### ISSUE TITLE
SingleSeriesProblem or SingleOutputProblem and uniform log prior

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#310]
I just tried running the adaptive covariance example and got an error:

AttributeError: 'module' object has no attribute 'SingleOutputProblem'

Is this because it has changed name to SingleSeriesProblem, or is this something else?

Upon changing the above, I also got the following error:

AttributeError: 'module' object has no attribute 'UniformLogPrior'

Has this changed name to UniformPrior? If I, instead put this in, I get the following errors:

ValueError: Prior must extend pints.Prior

Any ideas? 

On a related note, is there a way to test that running the examples doesn't throw an error?

**Comment by ben18785** [comment]
Think this is my fault -- I was using a past version of Pints inadvertently. Sorry!

One point still stands -- is there a way to do testing for the Jupyter notebooks?

**Comment by MichaelClerx** [comment]
Yup, you can use `run-tests --books`
It takes a while!

**Comment by MichaelClerx** [comment]
Yeah we have a "cron job" set up that does that

**Comment by MichaelClerx** [comment]
It keeps timing out though, so we have to be careful what we stick in there
