### ISSUE TITLE
Create toy model that returns a constant value

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#311]
This will be useful when developing unit tests as then we can do, for example,

    model = toy.ConstantModel() 
    times = np.linspace(0, 1000, 10)
    values = [1, -1, 1, -1]
    problem = pints.SingleOutputProblem(model, times, values)
    log_likelihood = pints.UnknownNoiseLogLikelihood(problem)

where `ConstantModel(x) = x`. Then `log_likelihood(np.asarray([0, 1]))=N(values | 0, 1)` by design, which makes it easy to design quick tests.

**Comment by MichaelClerx** [comment]
I don't agree with this syntax! Times should be the same size as values!

When you evaluate the unknownnoiseloglikelihood, what will happen to the sum?

Maybe you could instead define a `LogLikelihood` that ignores the values and model and always returns a normal distribution with some preset mu and sigma?

**Comment by MichaelClerx** [comment]
I see that the implementation actually works differently now :-)

**Comment by MichaelClerx** [comment]
Closed in #314
