### ISSUE TITLE
Population MCMC all samples at all temperature needed

### ISSUE THREAD

**Issue by sanmitraghosh** [pints-team/pints#315]
@MichaelClerx  Is there a quick way of obtaining samples from all the temperature chains? This is required for calculating the thermodynamic integral.  I need that for the hERG model selection task.

**Comment by MichaelClerx** [comment]
Hi @sanmitraghosh !

The private variable `_current` contains all the current samples of the internal chains (see [here](https://github.com/pints-team/pints/blob/master/pints/_mcmc/_population.py#L54-L57)). Depending on what you want you can either access it directly or you can add a method that exposes it (in which case you'd have to make a copy before returning (a bit like [here](https://github.com/pints-team/pints/blob/master/pints/_mcmc/_population.py#L266-L268)).

If you also want the `log_pdf` of those points, those are in the variable `_current_log_pdf`. Note that we store the untempered version, so you'd have to calculate the tempered version yourself if needed (see e.g. [here](https://github.com/pints-team/pints/blob/master/pints/_mcmc/_population.py#L248-L250)).

**Comment by sanmitraghosh** [comment]
@MichaelClerx Thanks.
