### ISSUE TITLE
Investigate adaptive HMC

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#316]
http://proceedings.mlr.press/v28/wang13e.pdf

**Comment by MichaelClerx** [comment]
See also #104

**Comment by ben18785** [comment]
Closing as is a duplicate of #677

**Comment by MichaelClerx** [comment]
Usually I'd go the other way and mark the newer one as a duplicate of the older one :-D

(It matters Very Little (tm), except that we should be encouraging people to search for existing issues before they open new ones - if we go the other way around it becomes some poor maintainers job to continually monitor old tickets in case they should be shut as a duplicate of a newer one)

**Comment by MichaelClerx** [comment]
(But thanks for noticing and closing, Ben!)
