### ISSUE TITLE
Update goodwin model to show all states

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#322]
@sanmitraghosh says this is a good test case for population and particle-based inference methods

**Comment by martinjrobins** [comment]
just curious, why?

**Comment by MichaelClerx** [comment]
It's not traditionally a model with hidden states, I just selected a random observable state at the time because we didn't have the MultiOutputSeries done yet!

**Comment by martinjrobins** [comment]
Sorry, I meant why is it a good test case for particle-based inference methods? Is the posterior multi-modal?

**Comment by sanmitraghosh** [comment]
@MichaelClerx @martinjrobins As per calderhead's paper it is multimodal, plus the posterior landscape has got ridges which is difficult to navigate using a simple chain. This is the case for all states visible and was demonstrated  [here](https://pdfs.semanticscholar.org/b31c/46d52fe572e7a388b26a531b03cc670401cb.pdf), read page 21 onwards
