### ISSUE TITLE
Unsupported sensitivities method shows up in docs of models

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#333]
Can workaround by adding this to all toy models without sensitivity support:

    def simulate_with_sensitivities(self, parameters, times):
        """ Not implemented. """
        raise NotImplementedError

But I think it would be better to define the `simulate_with_sensitivities` method only in a class `ForwardModelWithSensitivities` that extends `ForwardModel`

That would allow checking model support using `isinstance()` too

**Comment by martinjrobins** [comment]
That is a pain. Ok, I'll go with your suggestion and implement `ForwardModelWithSensitivities`

**Comment by ben18785** [comment]
Just a quick note. Do we want to return sensitivities always alongside with the forward model values? To me, in HMC etc. we only need the sensitivities in the ask side...

**Comment by martinjrobins** [comment]
good question. The majority of the time you will, since for ODE models you need to integrate the forward model to get the sensitivities.  Even for analytical sensitivities, in the logistic model the forward model is a term of the sensitivities, so I calculated it anyway.

**Comment by ben18785** [comment]
Cool. Yep, makes sense. Ignore me!

**Comment by MichaelClerx** [comment]
Ok! Will remove my workaround again then and close this :-)
