### ISSUE TITLE
Rename inference sampling?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#337]
1. Yes
2. No
3. Don't care

Will mostly be in documentation I think, probably not in the API much

**Comment by mirams** [comment]
I see sampling as one bit of inference (inference also including the process of using data, prior to assemble the distribution we want to sample from).

**Comment by ben18785** [comment]
The trouble with inference as a name, for me, is that you could also think of optimisation as a type of inference. You infer the best fit parameters in optimisation (albeit without uncertainty quantification).

**Comment by MichaelClerx** [comment]
Changed this in the examples & docs
