### ISSUE TITLE
Derivative for uniform prior

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#356]
Hi all!

For the d/dp of a log-prior, shall we just always return 0? Technically it's `+/- inf` for a point on the surface of a the hypercube, but chances are pretty small anyone'll hit that, and if they do, it'd mess up the method's sense of direction without any real benefit?

@sanmitraghosh @ben18785 ?

**Comment by MichaelClerx** [comment]
Sanmitra says stick with zeros everywhere.
@mirams ?

**Comment by mirams** [comment]
Not quite sure I am understanding the question? asymptote in a Log prior or edge of uniform prior, or what?

**Comment by MichaelClerx** [comment]
We're defining derivatives with respect to the parameters for the priors and likelihoods.

For a uniform prior d/dp would be zero everywhere except on the boundaries, where it'd be plus or minus infinity (step function!)

But that would be 1. a pain to implement, 2. very unlikely to actually happen when sampling, 3. very unhelpful.

So I was thinking I could leave it out

**Comment by mirams** [comment]
Zeros for uniform everywhere make sense I think.
