### ISSUE TITLE
suggested_parameters for logistic model

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#363]
All the toy models have suggested_parameters except the logistic model, is there a reason for this @MichaelClerx ? If not I'll put this in.

**Comment by MichaelClerx** [comment]
It's not an official part of the interface, just something that proved useful.

Feel free!

**Comment by martinjrobins** [comment]
whoops, forgot to do a new branch for this, been pushing to master. all tests pass though. @MichaelClerx, how does the interface look (I went with the double inheritance, cause otherwise I would have had to do two versions, one for sensitives, and one without)

**Comment by MichaelClerx** [comment]
@martinjrobins is this done now? Can we close the ticket?

**Comment by martinjrobins** [comment]
yup, I think so, closing...
