### ISSUE TITLE
Update color scheme and labels in `series` plot for multiple outputs

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#369]
As you can see in the repressilator example (PR #368 ), the series plot isn't quite ready for multi-output problems.

1. The label for each output is the same
2. The colour for each output is the same

Two options:

1. Update the labels, removing most of them, and cycle through a colorscheme (make sure this works in matplotlib 1 and 2)
2. (Probably easier), give the figure as many subplots as outputs

**Comment by chonlei** [comment]
Ah, just realised in our docs, we actually put 

> for a given list of ``samples`` and a single-output ``problem``

So we definitely said we are not ready for multi-output! 😄

**Comment by chonlei** [comment]
Oh, I meant the "a single-output ``problem``" bit, that means no "multi-output", and that is the bit that I am changing. I will keep "a given list of ``samples``" as it is -- as we don't handle multiple lists (e.g. multiple chains) in the `series()` plot.
