### ISSUE TITLE
create a gaussian process likelihood emulator for errors / log-likelihood

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#388]
- Initially this will wrap GPy (we will see how we can do this without requiring Pints users to install it unless needed)
- The GP would take an error/log-likelihood and then train the GP to emulate this 
- Maksym is joining us for the summer. He will code this up and provide a notebook example of its use

**Comment by MichaelClerx** [comment]
@martinjrobins can we close #45 as a duplicate of this?
