### ISSUE TITLE
setting hyper parameters of samplers

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#391]
After creating a  `pints.MCMCSampling` object, how can you set the hyper parameters of the underlying method object? @MichaelClerx?

**Comment by MichaelClerx** [comment]
For Optimisation we have a method `optimiser()`: http://pints.readthedocs.io/en/latest/optimisers/running.html#pints.Optimisation.optimiser

We should probably add the same for MCMCSampling!

**Comment by martinjrobins** [comment]
ok cool, I'll add that

**Comment by mirams** [comment]
One of my favourite Chaste coding conventions is 'Methods should be Verbs'. So maybe we should have a `get_` or something in front of `optimiser()`?

**Comment by martinjrobins** [comment]
yea, that is a reasonable convention, but probably should be a separate issue as it would involve lots of changes to apply the convention globally in pints

**Comment by MichaelClerx** [comment]
We're currently using the "I don't like typing get_ all the time" convention. It probably has a nicer name, but I'm quite a fan of that! Happy to discuss though. Maybe best to see what other Python packages do

**Comment by martinjrobins** [comment]
Yea, I'm kinda in the middle on this one. I am moving gradually away from using `get_`  for getters due to it being overly verbose and not playing nicely with auto-complete (I have to type 4 extra characters!!!!), but the whole "method-is-always-a-verb` is a nice clear and consistent convention to follow. Let me put it this way, I don't have the motivation to change what we already have, but I'm happy to go along if someone else does ;)
