### ISSUE TITLE
interface for setting hyper parameters of optimisers and samplers

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#393]
related to #391 

Proposal is to add a base class to all the optimisers and samplers, perhaps called `TunableMethods`, which provides member functions to set their hyper-parameters. This would allow you to easily tune the hyper-parameters of all the pints methods in a generic fashion (at the moment different methods have different member functions to set various hyper-parameters, there is no consistency)

I think you would only need two methods:

```python
def n_hyper_parameters(self):
"""
returns number of hyper parameters of this method
"""

def set_hyper_parameters(self,x):
"""
sets the hyper parameters of this method
"""
```

**Comment by MichaelClerx** [comment]
@sanmitraghosh @ben18785 ?
