### ISSUE TITLE
Add weighting output option in SumOfSquaresError

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#397]
As demonstrated in #396, in particular this toy model example: 
https://github.com/pints-team/pints/blob/cb004d40132d83486cf5a956c47653c58afaedfb/examples/toy-model-beeler-reuter-ap.ipynb

Model outputs in `MultiOutputProblem` can be in very different scales/order of magnitudes, which makes the optimisation ignores some of the model output.

@MichaelClerx also suggested to have `SumOfSquaresError` set it automatically as max(experiment) - min(experiment) in every output. 

(Note: not needed in log-likelihood if Gaussian noise is included, as that works as a scaling already.)

**Comment by MichaelClerx** [comment]
Thoughts / ideas @martinjrobins @mirams @ben18785 @sanmitraghosh ?

**Comment by martinjrobins** [comment]
Sorry, put this in the wrong place:

> Perhaps we can update the SumOfSquaresError to allow weighting in its constructor. Or maybe we want to go even further and set it automatically as max(experiment) - min(experiment) in every output?

I think by default the SumOfSquaresError should weight each output vector by its norm. And an option to manually specify weightings is great too!

**Comment by mirams** [comment]
I'm not sure this is something that we want to do automatically, it could lead to very odd behaviour if for instance one cell showed no response in am experiment and this no response was scaled up to give equal weight as a full response. 

Neither is weighting equally/according to length of time series necessarily a sensible thing.

I would advocate forcing the user to supply (and therefore think about!) the weighting when using multiple objectives.

**Comment by MichaelClerx** [comment]
> Neither is weighting equally/according to length of time series necessarily a sensible thing.

Agreed! For the record though, we have a `SumOfSquaresError` that just sums, a `MeanSquaredError` which also divides by length, and finally `RootMeanSquaredError`. Again, it's up to the user to select an appropriate measure

**Comment by martinjrobins** [comment]
yea, sounds reasonable, I agree with @mirams suggestion of forcing the user to specify a weighting (i.e. not providing any default)

**Comment by chonlei** [comment]
Maybe default can be all equally weighted -- and just add an option to change that if the user wants to?

**Comment by chonlei** [comment]
> For the record though, we have a SumOfSquaresError that just sums, a MeanSquaredError which also divides by length, and finally RootMeanSquaredError.
@MichaelClerx Do we want to add this to all of them then?

**Comment by MichaelClerx** [comment]
Yeah have something like `output_weights=None` and use 1s if it's None, else check if it's an array of the correct size!

> @MichaelClerx Do we want to add this to all of them then?

You decide. If you do do it, make sure you update all the documentation examples etc. as well!

**Comment by chonlei** [comment]
One problem is how should we change 
`de = 2 * np.sum((r.T * dy.T), axis=(1, 2))`
in the `evaluateS1()`?

**Comment by MichaelClerx** [comment]
It should be the derivative

**Comment by chonlei** [comment]
Just tried writing down the derivatives, it does not matter where/when to multiple the weights (as it does not depend on the parameters) as long as it is done *before* summing over that axis.

**Comment by MichaelClerx** [comment]
Great!
Can you look into the benchmarking thing too? Guessing (1000, 3) x (3,1) is a bit slower than (1,3) x (3,1), but maybe it makes no difference?

**Comment by chonlei** [comment]
Just for the record, I looked at the benchmarking thing, and you are right that (1000, 3) x (3,1) is slower than (1,3) x (3,1) -- by quite a lot in some cases, so have updated that.
