### ISSUE TITLE
Add optional R-hat convergence criterion to adaptive_mcmc code

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#40]
Burn-in should always happen first
But after that, stop either when max iterations is reached or when converged (if it works well, maybe set default max-iter to something very big?)

**Comment by ben18785** [comment]
This should be added to all MCMC routines.

**Comment by MichaelClerx** [comment]
Another question: Should we implement criteria like these in the results object?

I'd still like to have an interface like the one CMA-ES uses, where control is passed back to the user at every iteration. That would allow you to implement all disk-storage, output, statistical stopping criteria etc. exactly once, without having to do it separately in every method

**Comment by ben18785** [comment]
I closed it because it was implemented in _diagnostics. R hat is implemented in the MCMC result object, yes. We don't need it here.
