### ISSUE TITLE
Explain noise bias in 'first optimisation' notebook example

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#416]
In this [example](https://github.com/pints-team/pints/blob/e390527fb3ade9171641c7338d68109f12c296a4/examples/optimisation-first-example.ipynb) `In [14]`, we showed the found parameters are at the minimum of the score function but the actual true values are not, but we didn't explain what it means.

@mirams suggests 
> we could have a little subheading that says "Why aren't these exactly the parameters used to generate the data?" and then show as noise reduces that they tend to right answer. Although the 1D line graph will need axes with units fixed or it will just look the same!

**Comment by MichaelClerx** [comment]
Would be cool to combine this with an explanation of solver tolerance (which can create local min max, but also shift the optimum, as in gary's graphs)

**Comment by MichaelClerx** [comment]
@chonlei do you want to have a look at this?

**Comment by MichaelClerx** [comment]
Fixed in #1141
