### ISSUE TITLE
Git-push new functional test results

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#417]
Perhaps would be easiest if they lived in their own repository, separate from the functional testing framework itself?

@martinjrobins thoughts?

**Comment by martinjrobins** [comment]
Yea, this would make sense (a separate repo).

**Comment by MichaelClerx** [comment]
Done!
New problem: We need an account to push commits :-/

**Comment by martinjrobins** [comment]
you can set this up, using a GitHub OAuth token:

https://docs.travis-ci.com/user/deployment/releases/

but you might be right, easier getting a dedicated machine for this.

**Comment by MichaelClerx** [comment]
We have a dedicated machine now!

**Comment by MichaelClerx** [comment]
Implemented in aa1a8fc2eefedbe00f287be52c42996853040494

Should work if we set up the dedicated machine to have an SSH key that allows pushing

**Comment by MichaelClerx** [comment]
Works
