### ISSUE TITLE
Unbiased noise generators?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#419]
Hi all!

I'm wondering if we should add some noise generators that don't introduce a slight bias (due to lack of samples)?
For example, we could generate a noise signal of length N/2 and add it twice, once with a negative sign, to ensure the sum of the noise = 0 ?
This would mess with the distributions a bit of course...

The reason I'm wondering about this is that, for functional testing, it would be nice to compare the solution found by an optimiser with the true solution. But this only works if the true solution has the highest likelihood. Our examples show that, even with ~1000 samples, there is a notable difference between the true solution and the point of maximum likelihood.

Thoughts? @ben18785 @sanmitraghosh ?

**Comment by mirams** [comment]
I think we should use the same random seed and then test we get back an answer that we are expecting, having checked that this is in a problem where we know the max likelihood parameter set converges to the underlying parameters as we add more and more data?

**Comment by MichaelClerx** [comment]
Not sure I understand!

For functional testing we want to try with lots of different seeds (we do store the seed, for debugging). So I'm just wondering if it's worth it trying to remove this "artefact" so that we can just use a distance to true parameters as a quality of fit, instead of having to do something more complicated

**Comment by mirams** [comment]
Maybe I don't understand what functional testing is!

**Comment by MichaelClerx** [comment]
Never mind, I'm just plotting `f(x_found) / f(x_true)` now!
