### ISSUE TITLE
Update the MCMC classes to allow for a warm-up period

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#420]
(Not a burn-in period! But something like DREAM's warm up time, or adaptive covariance MCMC's non-adaptive stage)

For samplers, this'd mean adding:

- supports_warm_up() --> default False
- set_warm_up(bool)

For the MCMCSampling class, this'd mean adding

- set_warm_up_iterations(int)
- warm_up_iterations --> int

Both methods could raise an error if the underlying sampler doesn't support it.

We could then get rid of the `SingleChainAdaptiveMCMC` interface, and the MCMCSampling methods `adaptation_free_iterations() --> int` and `set_adaptation_free_iterations(int)`.

The advantage would be that we can have various types of warm-up via the same interface (e.g. no adaptation for adaptive-covariance-mcmc, or different proposal strategies for DREAM).

Thoughts @martinjrobins @ben18785 ?

**Comment by martinjrobins** [comment]
makes sense, I like this.

**Comment by MichaelClerx** [comment]
Yay! Does anyone have any suggestions for a name other than warm-up? (So that we don't confuse it with burn-in)?
@sanmitraghosh @ben18785 ?

**Comment by ben18785** [comment]
Sorry, not understanding, in MCMC 'warm-up' is 'burn-in'?

**Comment by mirams** [comment]
I'm imagining you are separating the concept of parameter estimate wandering to the right area with sampling becoming well-mixed and sensible acceptance ratio @MichaelClerx ? 

But I'd also imagine our Bayesian stats people @ben18785 would say that maybe this isn't possible or desirable to do, as in you can't say you are in the right place until you are well mixed!?

**Comment by MichaelClerx** [comment]
Uhm, no none of that! See above!

Two of the methods we have in Pints already, adative-covariance mcmc and dream mcmc, have an initial phase (that I'm calling "warm-up" but maybe should not?) during which the algorithm works slightly differently.

Adaptive covariance starts off by not adapting, and then adapts after N iterations.
Dream has what the authors call a "warm up" phase, during which it adapts some parameters. After N iterations, it stops doing this and switches to normal mode.

Since we have a structure where the sampler ("method") is not used directly, but via an `MCMCSampling` object that does boring stuff e.g. logging, checking stopping criteria, etc., I was wondering if we could abstract this concept of an "initial phase", so that I could introduce the methods I mention above!

**Comment by ben18785** [comment]
Yeah, "initialising" sounds good.

**Comment by mirams** [comment]
I think both cases (adaptation of the proposal distribution, or adaptation of algorithm parameters) is still ''burn in/warm up'' of the method in terms of it actually getting to sampling the distribution it is supposed to be and returning valid independent samples of the target distribution...

**Comment by MichaelClerx** [comment]
Agreed! Note that the current MCMCSampling method does _not_ remove any burn-in / warm-up samples. It just returns the full chain for you to inspect and manipulate yourself.

Thanks everyone!
