### ISSUE TITLE
Add rejection nested sampling example notebook

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#424]
See #107

**Comment by MichaelClerx** [comment]
Using multinest eggbox toy pdf

**Comment by MichaelClerx** [comment]
@ben18785 is this still something we want? We have a simple egg box too, but I suppose it'd be good to have the multinest one as well?

**Comment by ben18785** [comment]
This was done ages ago, I think. Will be handled in #503 and so am closing.

**Comment by MichaelClerx** [comment]
We usually wait with closing until things have been merged into master, but alright :-)
