### ISSUE TITLE
changes for pfunk.FunctionalTest

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#425]
After talking with @MichaelClerx, I would propose this new interface for pfunk.FunctionalTest:

```python
class FunctionTest():

  def _run(self):
  """ runs the test and generates the results object"""
  def _analyse(self):
  """  returns `True`  this test passed"""
  def _plot(self):
  """ generates some useful diagnostic plots"""
```

The idea is that all the functionality of a given test is implemented in the one file. 

There will be common code needed between tests, for example to get the latest test results, or test results over time, or average some quantity over time and check if it is 3 sigma away from the expected value, all these common function will be implemented in utility libraries that these tests call.

So a very standard test should be really quick to write (using these utility functions), but it should still be possible to write a very complicated and non-standard test with a bit of extra effort.

**Comment by martinjrobins** [comment]
@MichaelClerx: have the proposed new interface done up in branch `issue-425-pfunk-interface`. See what you think

**Comment by MichaelClerx** [comment]
Can you do a PR for easy comparison?

**Comment by martinjrobins** [comment]
all done
