### ISSUE TITLE
SMC intermediate MCMC steps: varieties

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#437]
Options:

- Adaptive covariance for multiple steps per temperature,
- Do adaptation across all temperatures,
- HMC.

**Comment by ben18785** [comment]
#465 now allows multiple MCMC steps per temperature.

**Comment by ben18785** [comment]
Been thinking about how to do multiple adaptation steps. Ideas:

- Could we do adaptation at a single temperature based on the accept/reject of the various particles? May be a question for Chris Holmes as am not sure if this breaks dynamic balance...
- Alternatively, adapt across all particles, temperatures and MCMC steps? This avoids the need for separate sigmas for each particle.

**Comment by MichaelClerx** [comment]
@ben18785 is this still something we want to investigate?

**Comment by ben18785** [comment]
Nah, let's close it. This sampler was useless.
