### ISSUE TITLE
Look into model selection using 'reversible jump mcmc'

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#44]
Chris Gill wrote:

_I had an idea last summer about how one might go about doing model selection and parameter fitting in one go using mcmc but didn’t have time to get the details working enough to share it with anyone.  It turns out someone has already developed the idea in quite a general framework, and it is useful - it’s called reversible jump mcmc.  Essentially you can jump between different parameter spaces provided you have a suitable map between them.  The wikipedia page has a fairly short intro to it.  I wondered if that might be an interesting direction to try out with the electrochemistry stuff, e.g. determining mechanism of action and the parameters in one (admittedly computationally expensive) go?  Just a thought, and I’m sure it will depend on how the different reaction models are specified, but I’ve been meaning to email you about it for some time now._

**Comment by mirams** [comment]
Yep - I looked into this very briefly, but some/all of the below might be wrong! 

This might be sensible for "nested models" (where most of the parameters map across). The difficulty is the line "provided you have a suitable map between them". For instance, you have an ion channel model C-C-O and jump to the model C-O. I think you need to get to an "equivalent" set of parameters once you've jumped model. I can see how you might be able to go down to smaller models by lumping/averaging/combining parameters somehow, but the leap up to add more parameters seems like another identifiability problem where there would be infinitely many options. 

But definitely worth someone looking at more carefully...!

**Comment by ben18785** [comment]
I am very late to the boat here (getting up to speed with github!), but don't think you'll want to do this in PINTS. RJMCMC is notoriously difficult to get to work in even modestly complex models. I honestly think that WAIC will be the best bet for model selection (I am also not a fan of marginal likelihoods!).

**Comment by MichaelClerx** [comment]
Closing this now until we have a more concrete idea of how/if to approach this
