### ISSUE TITLE
Set up skip for functional testing

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#453]
Ideas for cron jobs:

- https://github.com/pints-team/functional-testing/blob/master/cron1.txt
- https://github.com/pints-team/functional-testing/blob/master/cron2.txt

**Comment by martinjrobins** [comment]
skip is setup with a new user `pints`, which has a crontab pointing to the two scripts:

- `cron_daily.sh`
- `cron_hourly.sh`

It should start generating results, will check tomorrow if it is all working as expected

**Comment by MichaelClerx** [comment]
Seems to work?

**Comment by MichaelClerx** [comment]
Thinking we might want to change the hourly script to run the same test 3 times, so we have a bit more data about commits. If we do a single test for a commit, and the test produces an outlier, that will look quite significant in the graph, even though it's not

**Comment by martinjrobins** [comment]
done. I'll leave this for a while to see if it works ok....

**Comment by martinjrobins** [comment]
git pull wasn't working on skip, fixed now so should work now hopefully....

**Comment by martinjrobins** [comment]
all works
