### ISSUE TITLE
Parallelisation in nested sampling

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#456]
Hi @ben18785 !

The nested sampler has a look that goes

```
while not good enough:
    keep sampling()
```

if you like, we could keep track of how many iterations are usually needed before a sample is good enough, and then do this instead:

```
while not good enough:
    sample N times in parallel
    accept first one that's good enough, or keep going
```

that might speed things up. Do you think it'd be worth the effort?

Secondly, do you think we should add some sort of stopping criteria when it gets to the point where the while loop just keeps going (i.e. no improvements are made), or would that ruin the stats properties somehow?

**Comment by ben18785** [comment]
@MichaelClerx Yes, I think you're probably right -- perhaps it is not worth the effort to parallelise.

Yes, I think we could add a stopping criteria (as long as it is a hyper-parameter that could be set by the user).

**Comment by MichaelClerx** [comment]
Just sticking a priority label on this to have another look at it after the refactoring #631

**Comment by MichaelClerx** [comment]
This is being addressed in #928

**Comment by MichaelClerx** [comment]
Hey @ben18785 , I think we did this one! Want the honour of hitting the close button? :D

**Comment by ben18785** [comment]
Ha, closed!
