### ISSUE TITLE
DREAM has many hyper-parameters that aren't modifiable

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#462]
There are many hyper-parameters for DREAM that aren't listed in the hyper-parameter interface (see #431), and cannot be modified in any way

- [x] `b_star`
- [x] `p_g`
- [x] `delta_max`
- [x] `constant_crossover`
- [x] `CR`
- [x] `nCR`

**Comment by ben18785** [comment]
#466 addresses this
