### ISSUE TITLE
Division by self._L = 0 in dream

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#472]
On line 289, `self._p /= self._L * np.sum(self._delta)` part of self._L is zero. Should we start L off with 1s instead of 0s?

**Comment by ben18785** [comment]
@MichaelClerx Yes, strange. 

Does this actually throw an error? From re-reading the paper, it looks as though this shouldn't happen 
often so long as self._chains >> self._nCR. If it does, then, as you say, it may be best to set it to 1.

The default number of chains recommended by the paper is the number of parameters of the problem, although all the problems they test have 10 or more dimensions and self._nCR=3 in all their examples.

**Comment by ben18785** [comment]
Ok, sounds good.
