### ISSUE TITLE
ESS for population mcmc is funny

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#479]
If adaptation is disabled (`mcmc.set_initial_phase_iterations(0)`) the chains don't get swapped, so each chain explores its own mode. In this case we get ess of approx 10
With adaptation enabled, there's lots of swapping (which is what we want!), but the ess goes down to 1.

Could be that the ess just doesn't deal well with multimodal in this case. But @ben18785 wants to check just in case!

**Comment by ben18785** [comment]
@MichaelClerx Have now added ess calculations to the notebook for populationMCMC -- its ess is about 6x higher than for adaptive covariance by my calculations. See 4589d96

**Comment by MichaelClerx** [comment]
Ah brilliant. I was confusing ess and rhat... Should we have rhat in our functional testing do you think?
