### ISSUE TITLE
Replace priors by log-priors

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#48]
Sanmitra says it's better :-)

1. Are all the algorithms happy with this?
2. Should this only happen under the hood? I imagine users would prefer to specify a prior rather than a log prior... We could even think about giving the Prior class a log() method?

**Comment by martinjrobins** [comment]
1. I think all the algorithms should be fine, its just a matter of changing the * with a + when you combine it with the likelihood (and for the combined prior as well)
2. I think under the hood is best

**Comment by ben18785** [comment]
Just checking -- in PINTS under the hood are all priors and likelihoods logged? Otherwise I fear there would be numerical issues for our models where the likelihood is tiny...

**Comment by martinjrobins** [comment]
likelihood is logged. priors are not, but will be after this ticket is done
