### ISSUE TITLE
Check Rhat values on population MCMC

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#490]
I'm not convinced that the Rhat values are representing the (non-)convergence of the chains. When I look at the plots, it doesn't look like the chains have converged but Rhat says they have.

**Comment by MichaelClerx** [comment]
@ben18785 any update on this?

**Comment by MichaelClerx** [comment]
@ben18785 any update on this?

**Comment by MichaelClerx** [comment]
See also #264 and #487

**Comment by MichaelClerx** [comment]
@ben18785 this is another good one

**Comment by MichaelClerx** [comment]
@ben18785 is this issue resolved with the changes to R-hat you made recently?

**Comment by ben18785** [comment]
Yep!
