### ISSUE TITLE
Include examples involving sensitivity calculated by automatic differentiation

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#501]
as well as more traditional Jacobian matrix based approaches. It'll be interesting to see what works more efficiently. Perhaps have a look at [this](https://pythonhosted.org/algopy/) program.

**Comment by MichaelClerx** [comment]
Is this a PINTS thing though? It's an interesting question but from PINTS point of view sensitivities are something the user provides

**Comment by ben18785** [comment]
Yep, agreed. This package looks pretty neat as it allows auto differentials of Python and Numpy code: https://github.com/HIPS/autograd

**Comment by MichaelClerx** [comment]
@martinjrobins just found the same package!

https://github.com/HIPS/autograd/blob/master/examples/ode_net.py

> I didn't realise that the python autograd package can take the gradient of odeint, nice :slightly_smiling_face: (https://github.com/HIPS/autograd/blob/master/examples/ode_net.py)
> i.e. autograd can evaluate the sensitivities for every toy model in pints....

**Comment by martinjrobins** [comment]
I tried this:
- We would need to import autograd in every toy model. Not so bad, but it would be another dependency
- Its really, really slow. This is probably the killer.

**Comment by MichaelClerx** [comment]
Thanks @martinjrobins ! That's very useful to know.

I guess that means we don't add autograd as a dependency, but we can still make an example file showing (1) how to do this, and (2) why not to do this.

Because I'm sure we'll be asked again and again :D
