### ISSUE TITLE
Refactor nested sampling algorithms to fit in ask/tell

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#503]
They can fit into ask/tell as follows,

- Ask: propose a new point using the active set (and/or its segmentation, for example, the ellipses). At current, the ways we have for doing this are a) sampling from the prior (rejection sampling) b) sampling from a surrounding ellipse (elliptic sampling) c) sampling from a series of ellipses (multinest) d) Galilean Monte Carlo velocity process.
- Tell: accept the point if it has a likelihood above the current threshold.

Once convergence in the evidence is reached (this can, however, be controlled by the user on the fly), generate posterior samples. This will mean that we store all the ghost particles and their weights.

This framework will greatly simplify the existing code and make it far simpler to extend it.

**Comment by MichaelClerx** [comment]
See also  #568
