### ISSUE TITLE
new functional test: plot of # function evaluations versus time taken for all methods

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#512]
test would: 

1. pick a cheap model,
2. then loop through all methods (samplers and optimisers)
    2.1. run method until completion
3. plot number of time taken versus number of function evaluations 
4. calculate the gradient of the plot in 3 (should be a straight line)

If the gradient of the plot in 3 is too high, this indicates that more time is spent in the actual method rather than evaluating the model. Above a certain threshold would indicate an implementation problem, and the actual plot is useful to see what methods are more expensive than others

**Comment by MichaelClerx** [comment]
Closing for now!
