### ISSUE TITLE
functional testing all failing ATM, go through and tune thresholds to reasonable values

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#514]
https://github.com/pints-team/functional-testing-results

**Comment by martinjrobins** [comment]
Here are the current sigmas for the sampler methods on different problems. If the KL divergence goes above 3*sigma for any of the samplers they fail the test
- banana: 0.05
- normal: 0.05
- eggbox: 0.5

In general we are getting *a lot* of failures across the board on this, which is odd since the thresholds seem ok to me...

**Comment by MichaelClerx** [comment]
Could we draw the threshold in the graphs?

**Comment by martinjrobins** [comment]
for the optimisation tests, the "br" test is causing lots of problems with the methods, thinking that it might be best to remove this from functional testing, since it clearly is not an easy problem

**Comment by martinjrobins** [comment]
see #515, #516. #518

**Comment by martinjrobins** [comment]
custom thresholds and drawing them in plots in all tests now, closing
