### ISSUE TITLE
DifferentialEvolution performs poorly when sampling from a normal pdf

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#515]
The functional tests indicate that the DifferentialEvolution method performs very badly when trying to sample from a simple normal pdf

You can see the exact test that is run here in the `pfunk/tests/mcmc_normal.py` file in the functional-testing repo. 

To reproduce the problem, edit this file and set `DEBUG=True` on line 49 and then run the test:

```bash
./funk run mcmc_normal_DifferentialEvolutionMCMC_3
```

This will give you a trace of the chains.

**Comment by martinjrobins** [comment]
see also #516

**Comment by martinjrobins** [comment]
from @ben18785: "I'm hopeful that this PR will fix this. #497"

**Comment by MichaelClerx** [comment]
Seems to be alright now. Although will need some more data

**Comment by martinjrobins** [comment]
looks great, closing
