### ISSUE TITLE
PopulationMCMC performs poorly when sampling from a normal pdf

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#516]
The functional tests indicate that the PopulationMCMC method performs very badly when trying to sample from a simple normal pdf

You can see the exact test that is run here in the `pfunk/tests/mcmc_normal.py` file in the functional-testing repo.

To reproduce the problem, edit this file and set `DEBUG=True` on line 49 and then run the test:

```bash
./funk run mcmc_normal_PopulationMCMC_1
```

This will give you a trace of the chains.

**Comment by ben18785** [comment]
I'm hopeful that this PR will fix this. #497

**Comment by ben18785** [comment]
Sorry, commented in the wrong issue! Sorry, being a bit dense. Whereabouts can I see the default hyperparameters that are used in the tests? Are they just the defaults that the algorithm uses?

**Comment by martinjrobins** [comment]
yup, everything in the functional testing is left at the defaults. **Note** that this is different from the matrix comparison testing that I'm doing, where the hyper-parameters are optimised

**Comment by ben18785** [comment]
@martinjrobins So, I just ran the test in the popMC example notebook in the i516 branch I just uploaded. PopMC seems to work fine with the default params. After 8000 iterations, we have convergence in both dimensions.

How many chains are being used? Also, are you getting rid of the warm up iterations? I'm getting ess values of around 250 for this number of iterations. This contrasts quite significantly with the ess values in the functional tests.

**Comment by martinjrobins** [comment]
looks like just one chain, for 4000 iterators. The 1st 2000 iterations are being removed prior to the KLD and ess calculations.

You can see the exact test in the file `pfunk/tests/mcmc_normal.py`. 

You are right, it does seem to be converging, but the speed at which it converges is much slower than both AdaptiveCovariance and plain old MCMC (https://github.com/pints-team/functional-testing-results), hence it is failing the test (the test is that after 4000 iterations with the 1st 2000 removed as burn-in, the KLD value is < 0.15). Do you think the test is too difficult, or there is a problem with the method itself?

**Comment by ben18785** [comment]
Thanks Martin. I think the method itself is fine. It's just not the sort of
problem that population MCMC will do well at, which tends to be multimodal
problems. Also, every iteration in population MCMC we only update one of
the chains and so it will naturally be slower per iteration than other
simpler algos.

Can we increase the iterations or lower the threshold for pass?

**Comment by martinjrobins** [comment]
ok, thanks. I might just not test the pop mcmc against the normal pdf then, if it is expected to perform poorly here. I want the functional tests to all be problems that the methods should be able to beat easily (so if they fail its likely that there is a problem with the implementation).

**Comment by ben18785** [comment]
I still think it's a good test to be honest, can't we just lower the
thresholds for this sampler? I think that ultimately we will need bespoke
thresholds for different samplers anyway...

**Comment by martinjrobins** [comment]
yea, can do that if you think it is useful, I'll give that test a higher threshold

**Comment by ben18785** [comment]
That would be great, thanks. I just think that having a common threshold
across all samplers (if they use the same number of iterations) isn't going
to work ultimately, to be honest.

**Comment by MichaelClerx** [comment]
I'd prefer more iterations over a lower threshold, it does have to get there eventually!

**Comment by martinjrobins** [comment]
it would be nice to keep all these tests as quick as possible. You can clearly see the method converging in the KLD versus iteration plots, its just slower than the others.

**Comment by martinjrobins** [comment]
as an aside, am I correct in thinking that the number of chains for the egg_box problem should be at least 4 (one for each mode)?

**Comment by ben18785** [comment]
I don't think we should have the eggbox problem for testing. Almost all of
the methods will fail on it unless you start each chain on each mode (in
which case you are really just testing the Gaussian).

**Comment by martinjrobins** [comment]
you are correct that all the methods have rather abysmal performance on it! If you expect them all to do this then I'm happy to get rid of it. How about the pop mcmc method, should it be doing reasonably well on the egg box?

**Comment by ben18785** [comment]
Pop MCMC, SMC and multinest (probs not the nested samplers in Pints
currently) would be the only ones that may do ok here. I'd use it for
benchmarking rather than testing.

**Comment by MichaelClerx** [comment]
I want to leave the egg box in! Just make it pass easily, or even always, but we can't just say "it probably won't work" and leave it at that

**Comment by MichaelClerx** [comment]
If we want to advise certain methods for multi-modal distributions, then we need to be able to say "they work 10x better" or something similar, not "they work better than these other methods which we didn't even try because they probably won't work". That's what I'm afraid of :-)

**Comment by MichaelClerx** [comment]
> it would be nice to keep all these tests as quick as possible.

It would be nice, agreed! But let's not forget that we set this up to do things that weren't necessarily quick :-)

**Comment by ben18785** [comment]
Ok, but I’m not sure this’ll work for anything. I thought the point of validation tests was to check whether things have broken. Not to check if samples are more efficient than others. Isn’t that the benchmarking?

**Comment by MichaelClerx** [comment]
Fair enough

**Comment by martinjrobins** [comment]
to get the egg box to pass reliably I would have to set the pass threshold at the 1000's or 10000's, so I think it should go off, it is clearly too difficult for the mcmc samplers (the ellipsoid samplers though, are doing really well!!)

**Comment by martinjrobins** [comment]
pop mcmc passing for normal now, so closing this
