### ISSUE TITLE
banana problem failing across many samplers

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#518]
- [x] AdaptiveCovarianceMCMC
- [ ] DifferentialEvolutionMCMC (should be fixed by #497?)
- [ ] DreamMCMC
- [x] MetropolisRandomWalkMCMC
- [ ] PopulationMCMC

**Comment by martinjrobins** [comment]
I'm planning to raise the threshold for pass to a KLD of 3, but DifferentialEvolutionMCMC, DreamMCMC & PopulationMCMC will still fail this

**Comment by martinjrobins** [comment]
@ben18785, should this banana problem be solvable by these methods?

**Comment by ben18785** [comment]
No, probably not. Again I think this distribution should be used for benchmarking not testing...

**Comment by martinjrobins** [comment]
ok, I'm going to turn off the banana and egg box testing for the mcmc samplers (I might leave it for the nested samplers, these are doing really well). We can discuss when we next meet putting them back in, but I think since we are going to submit the JORS paper soon we need to have the functional testing passing!

**Comment by ben18785** [comment]
Ok, sounds good.

I’ve started to look at a range of functional tests for the samplers in a branch. Think there may be about 4/5 additional tests for each sampler. These examine different aspects of each’s functioning.

Is the best thing to do to create a PR in the functional testing repo? I also want to play around with the current outfitted plots.

**Comment by martinjrobins** [comment]
yea, lets just use the same workflow as we are currently using for the main repo (branches based on issues and then PR)

**Comment by martinjrobins** [comment]
turned off banana tests, closing
