### ISSUE TITLE
How to clone functional testing repo without results files?

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#522]
It keep crashing my git for some reason. Not sure if this is the reason but the "res" folder there currently returns a 404 error when I click on it.

@martinjrobins @MichaelClerx any ideas?

**Comment by martinjrobins** [comment]
The res folder is a git submodule of the functional-testing-results repo. Can clone using the 'hit clone - - recursive' flag. See README.md of repo.

**Comment by ben18785** [comment]
Should have said, I've been doing that (I think). I have been doing

git clone --recursive https://github.com/pints-team/functional-testing.git

and all seems ok until the end when I get the following error messages:

fatal: reference is not a tree: d089dc036be7f64002064e2cd0e5b7b80ae9c425
Unable to checkout 'd089dc036be7f64002064e2cd0e5b7b80ae9c425' in submodule path 'res'

This also happens when I don't do the recursive business... Any ideas?

**Comment by martinjrobins** [comment]
hmmm, I get a similar error, not sure why this is happening

**Comment by martinjrobins** [comment]
ok, I think I might have fixed, can you try again @ben18785. Either re-clone the entire thing, or go into the function-testing directory and do a  `git submodule update`

**Comment by ben18785** [comment]
Thanks Martin and sorry for the hassle. It now works for me.

I've been playing around with the testing infrastructure -- looks great!
