### ISSUE TITLE
Add toy distributions for functional testing

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#523]

**Comment by ben18785** [comment]
- Multimodal normal
- High dimensional normal
- Cone distribution

**Comment by ben18785** [comment]
Also, add independent sampling methods for cone. This is based on the Mathematica work I've done, where I use inverse transform sampling to generate an r value, then sample a point on the hypersphere with that radius.

**Comment by ben18785** [comment]
- [ ]  Annulus distribution
- [ ] Neal's funnel

**Comment by MichaelClerx** [comment]
We have a cone and annulus distribution now, with 448fffc2b41d23f9216c836793f50c95650c642b.
