### ISSUE TITLE
Add option to write MCMC chain to disk during run ("live" / dynamically)

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#542]
This can already be done via ask-and-tell (if you implement the disk-writing bit yourself), but it's a popular request esp. for very long runs that might unexpectedly terminate at some point.

Still wary of 'bloating' the MCMCSampling method, but coming round to the idea of this one...

**Comment by mirams** [comment]
The posterior density values in there too would be nice!

**Comment by MichaelClerx** [comment]
> The posterior density values in there too would be nice!

The LogPDF in Pints terms, we're not necessarily Bayesian ;-)

But yes

**Comment by mirams** [comment]
Was thinking about implementing this myself as it is becoming a roadblock, but there seems to be a method `MCMCSampling.set_log_to_file(filename=None, csv=False)` already? What does this do?!

**Comment by mirams** [comment]
Ah, just prints iteration number, function evaluations, acceptance ratios and not the actual chain locations and likelihoods?

**Comment by MichaelClerx** [comment]
> Ah, just prints iteration number, function evaluations, acceptance ratios and not the actual chain locations and likelihoods?

Yup! The stuff you usually get on screen (possibly with extra info)

**Comment by MichaelClerx** [comment]
What were you thinking for the output format? CSV? I'd like a header row in there. Something like `"iter","logpdf","p1","p2",...`? And multiple files (one per chain) or 1 file with multiple chains?

**Comment by MichaelClerx** [comment]
- Example of creating multiple file names here: https://github.com/pints-team/pints/blob/master/pints/io.py#L78-L86
- Maximum precision float output: `pints.strfloat(number)`
- And I'm guessing you probably want to open and close the file any time you write a line, rather than keeping it open...

Actually... just use another instance of the Logger class!

**Comment by mirams** [comment]
One file per chain will probably be easier to handle after? Not going to have chance to do this for a couple of weeks. But I will note that one of my chains crashed after 3 days with this, leaving me with nothing useful!:

       xs = [sampler.ask() for sampler in self._samplers]
      File "/usr/local/lib/python2.7/dist-packages/pints/_mcmc/_adaptive_covariance.py", line 68, in ask
        self._current, np.exp(self._loga) * self._sigma)
      File "mtrand.pyx", line 4511, in mtrand.RandomState.multivariate_normal (numpy/random/mtrand/mtrand.c:37052)
      File "/usr/local/lib/python2.7/dist-packages/scipy/linalg/decomp_svd.py", line 119, in svd
        raise LinAlgError("SVD did not converge")
    numpy.linalg.linalg.LinAlgError: SVD did not converge

**Comment by ben18785** [comment]
I know this probably isn’t useful for the current discussion but Gary’s chains’ issue is one I’ve encountered with others using adaptive covariance. Basically, when you have strong identification issues, the covariance matrix used for adaptation becomes lower rank and you get issues with forming it. 

I wonder whether it’s worth having a sort of try/catch mechanism used to form the covariance matrix? If try fails, then we basically stop adapting.

**Comment by MichaelClerx** [comment]
Sounds like a nice feature. Could you make a ticket for that?

**Comment by MichaelClerx** [comment]
@chonlei would you like to pick up this ticket (#542)? Should be easy enough to do by re-using the `Logger` class

**Comment by MichaelClerx** [comment]
Actually nevermind I'll have a look :D

**Comment by MichaelClerx** [comment]
On the subject of having both samples and their loglikelihoods; this is not something we currently have in [`save_samples()`](https://pints.readthedocs.io/en/latest/io.html#pints.io.save_samples) and `load_samples()`. Do we want something similar there? It would be good to have these methods be compatible at least.

An alternative would be to store logpdfs in a separate file?

**Comment by MichaelClerx** [comment]
Ugh. Second issue with the logpdfs is that we don't get this information from the sampler objects automatically. The main loop is:

```
xs = sampler.ask()
fs = f(xs)
ys = sampler.tell(fs)
```

So we know `f(xs)` of the suggested samples, but not `f(ys)` of the accepted samples. We could do ugly bookkeeping here but would probably make more sense to update the interface. That's a fairly big change...

@martinjrobins ?

**Comment by ben18785** [comment]
Can we save log likelihoods (not log posterior as this isn't generally as
useful) in a separate file?

**Comment by MichaelClerx** [comment]
If you really really want to then yes, but it's a bit of a hack. Basically inside `MCMCSampling.run()` you'd have to (1) Check that your LogPDF is a LogPosterior, (2) Decompose the LogPosterior into a prior and a likelihood, and evaluate them separately, (3) Evaluate both at every iteration, calculate the LogPosterior manually and pass it to the `MCMCSampler` object. (4) Do some bookkeeping to keep track of which loglikelihood goes with which sample, and to check whether samples were accepted or not, so you can store the correct one

**Comment by martinjrobins** [comment]
Yup, I'll be there at 11

**Comment by MichaelClerx** [comment]
Me too!

**Comment by MichaelClerx** [comment]
Summary of the discussion:

- Wanting loglikelihoods (_not_ logposteriors) is very common when using MCMC for model selection, so worth the extra code.
- Model selection sometimes requires no further work beyond running an MCMC routine, so users are unlikely to use the ask-and-tell interface directly and implement it themselves
- The ask-and-tell interface does _not_ specify that the accepted points should be ones previously given by ask(). For example, it would allow a user to check f(1), f(3), and f(4) and then conclude that a good point would be 2 (for which f(2) isn't known). However, Ben can't think of a method where this is the case, so it's probably OK to update the "contract"

**Comment by mirams** [comment]
Definitely want log-posterior rather than log-likelihood printing out to identify my Maximum A-Posteriori parameter set don't I?

**Comment by MichaelClerx** [comment]
One more question @mirams : At the moment, we have an optimisation going:

```
calculate_posterior():
    prior = sample_prior() # fast
    if prior == -float('inf'):
        return prior
    likelihood = sample_likelihood() # slow
    return prior + likelihood
```

if we keep this in, we'd get some blank fields for the likelihood column. Is that ok? Or would you like this hack disabled when logging to file?

**Comment by mirams** [comment]
If we have posterior, prior, likelihood (in some order!) as columns in a file then empty entries is fine by me. I wouldn't want to start trying to evaluate likelihoods when prior was '-inf' anyway, because we sometimes use the prior to restrict the parameter space to where the solver doesn't fail!

**Comment by mirams** [comment]
That said, this was mostly about writing MCMC chains to file, and in that case anything with a prior/likelihood of -'inf' should never be accepted into the chain, so I don't think the problem will arise?

**Comment by MichaelClerx** [comment]
Good point!

**Comment by MichaelClerx** [comment]
OK. Now I've got code to write the `LogPDF` evaluations to a separate file.

Only remaining problem is how to separate this into a prior and a likelihood for the Bayesian case. (Keeping in mind that we use an evaluator to evaluate all logpdfs in parallel). 

One option would be to add a special method (or argument) to `LogPosterior` to return all 3 calculated values. Then do the same for the method that returns sensitivities etc. This involves a bit of bookkeeping and API changes.

A second option would be to just calculate the prior a second time, and subtract this from the known value. This is OK provided the prior is quick. Can we always assume that?

**Comment by MichaelClerx** [comment]
@ben18785 says option 2.

**Comment by MichaelClerx** [comment]
Fixed in https://github.com/pints-team/pints/pull/552
