### ISSUE TITLE
Master-Develop-Issues branch structure

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#557]
Had a brief chat today about switching to a branch structure like the one below:

```
  master        develop         issue 1         issue 2
    |
release 1 ---- release 1           
    |             |     \------ commit
    |             |                |
    |             |             commit
    |             |                |
    |             |  /--------- commit
    |           merge      
    |             |  \------------------------- commit
    |             |                               |  
    |             |                             commit
    |             |                               |
    |             |  /------------------------- commit
    |           merge
release 2 -----/
    |
    .
    .
    .
```

Advantages:

- We can run functional testing on develop, and merge samplers into develop when we _think_ they are ready, then use func test results _over a few weeks / months_ to see if they really work before we merge into master

Disadvantages:

- Minor fixes made in branches will hang around in develop waiting for us to finish testing any new algorithms
- Any time a new sampler/optimiser is added to `develop` we have to start testing again, which delays new releases to master

Our conclusion (Ben, Chon, Martin, Michael) was to leave it as it is for now, but maybe move towards this structure in the future (when Pints is more stable?)

**Comment by MichaelClerx** [comment]
Maybe later!

**Comment by MichaelClerx** [comment]
I'm thinking this would be a good idea again.

Benefits:

- We can merge big PRs, but still have a few weeks/months to try them out in practice and/or correct mistakes we find
- We can make sure functional testing runs on `develop`, so that methods not in `master` can be tested for a while before every release

**Comment by martinjrobins** [comment]
yea, agree on the 2nd point there. Since functional testing takes a while to determine if there is a problem, a develop branch would be useful

**Comment by MichaelClerx** [comment]
I don't really mind! Since the pip install will be the standard from now on, we could rename `master` to `develop` and just keep developing (and testing) there?

I've actually just gone back to a single branch structure for Myokit yesterday, because it was annoying having two.

**Comment by MichaelClerx** [comment]
How would it speed things up to have an extra branch? I already use `master` at the moment, which is currently ahead of the latest pints release

**Comment by ben18785** [comment]
Cool, if it's more trouble than it's worth, I'm happy to leave it as it is.

**Comment by MichaelClerx** [comment]
I honestly don't mind! Happy to hear from @martinjrobins and @fcooper8472 and @iamleeg and anyone else who has experience working on bigger projects!

**Comment by MichaelClerx** [comment]
What's the benefit of having a `master` branch over using tags to indicate which snapshots of the `develop` branch are releases?

**Comment by ben18785** [comment]
@fcooper8472 -- yes, I was only suggesting it in the hope that it speeds up getting things merged (if it won't that's fine). The thing that's occurred recently is that some methods take ages to get into PINTS (because they're complicated) and, even once they do, they're not (without further changes) practically useful. NUTS is a good example of this, where we really needed transformation objects to make them usable. I guess I'm just trying to think about how we can balance ensuring practical usefulness vs code quality. But, perhaps, there isn't a nice solution for this!

**Comment by fcooper8472** [comment]
You could imagine `develop` being potentially slightly less stable than `master`: have it as a bit of a staging area where you accept that things might not be 100% polished, but you can get some good experience using a feature before it's polished and merged into `master`.  Dunno - just a thought!

**Comment by ben18785** [comment]
@fcooper8472 I like that idea!

**Comment by MichaelClerx** [comment]
I could see that being useful, but also a major drawback: it would mean that unpolished stuff can get into develop, after which the dev loses interest / finishes their degree, and then the next release would be delayed while some poor dev polishes the develop branch so that it can be merged into master

**Comment by martinjrobins** [comment]
I do like the idea of a develop branch where we can merge unpolished things that might still be useful to try out in practice for a while, and combine with other prs

**Comment by iamleeg** [comment]
I think I agree with Michael: given the choice of making everybody take a little bit extra effort to polish every contribution, or making somebody take the large effort of polishing the whole develop branch every now and then, I know which sounds more likely.

**Comment by MichaelClerx** [comment]
If we do do this we might as well change `master` to `main` at the same time

**Comment by MichaelClerx** [comment]
Closing this now.
- no action for ages
- if we'd had a messy development branch it would be a lot of trouble to do a new release today
- setup is already complex enough
- development has slowed down, so introducing a branch just adds complexity w/o pay off
