### ISSUE TITLE
Automatic sigma in MCMC

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#559]
~HamiltonianMCMC fails the Normal PDF test in functional testing. I've been doing some testing in a notebook, and it seems that the reason is that we don't provide a sigma, and the automatically  set sigma is way too small.~

At the moment, we set 

```
scale = abs(x0)
scale[scale == 0] = 1
sigma0 = diag(0.01 * scale)
```

In other words, in absence of any other information we scale the initial position x0 by 0.01 and use that as the diagonal of sigma0.

As far as I can trace the 0.01 factor has been there from the start, so probably inherited from optimisation, where I guess we set it small to stop the method from exploring too wildly in the beginning? Not sure. These are pretty much untested heuristics as far as I can tell.

Does anyone object to me removing the 0.01 factor?

@mirams @ben18785 @sanmitraghosh @martinjrobins @chonlei ?

**Comment by ben18785** [comment]
How many HMC steps per iteration are we using? Usually around 10 works well. I would have thought that having a step size similar to Adaptive MCMC would work ok. Happy to go with whatever works though.

This does raise a good point, though. Can we make these algorithms so that they self-tune during an initial phase? Alternatively, can we have a routine that a user can run that determines the best parameter set?

**Comment by martinjrobins** [comment]
I think investigating some sort of auto-tuner would be good at some point. Its what I do for the performance_testing, but there is nothing stopping us from doing it in an on-line fashion.

**Comment by MichaelClerx** [comment]
See also #615 and #1050

**Comment by MichaelClerx** [comment]
Before fancy tuning, would it make sense to remove the 0.01 as suggested above @ben18785 @martinjrobins ?

**Comment by martinjrobins** [comment]
all you would be doing is changing magic number `0.01` to `1.0` :) `0.01` is better than `1.0` though, you probably don't want any particular method immediately hitting a boundary, so better to be cautious and explore the local region only. I'd vote for leaving it in and closing this issue until we do auto-tuning (note that #1112 has a method for choosing a sensible step size initially, and then adapting it with dual averaging)

**Comment by MichaelClerx** [comment]
Fair enough!
I think the original issue for HMC was fixed now anyway
