### ISSUE TITLE
Set up an interface for likelihood-free inference methods (ABC)

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#56]
From last inference group meeting:

```
Likelihood free methods
=======================
When P(D|theta) is intractable
Approximate Bayesian Computeration (ABC) / abc rejection sampling
Synthethic likelihood (assume gaussian) --> Wood 2010, Nature

Software
========
Python: pymc3, ABC-sysbio
R: EasyABC, abc
```

**Comment by ben18785** [comment]
This should perhaps be the first step in fitting a complex model to data because it'll generate relatively fast (albeit, approximate) posteriors. I think inclusion of ABC (and other related varieties) should be a definitely "yes" for PINTS.

**Comment by MichaelClerx** [comment]
See #96

**Comment by MichaelClerx** [comment]
This is more or less covered by issues like #96, so am closing now
