### ISSUE TITLE
Should we func. test MCMC methods with the logistic model too?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#562]
We can't say much about the distribution, but they should be able to get a good MAP prediction of the true parameters, when started near the ~true~ best parameters?

See e.g. https://github.com/pints-team/pints/blob/master/examples/sampling-hamiltoniam-mcmc.ipynb which doesn't

@ben18785 @martinjrobins ?

*best params being those found by a reliable optimiser, so including noise bias

**Comment by martinjrobins** [comment]
So the HMC would fail this proposed test? Does that mean it is incorrectly implemented, or just bad in a performance sense?

**Comment by ben18785** [comment]
Strange that HMC fails this. I don't think it should...

**Comment by MichaelClerx** [comment]
Please have a look at the updated notebook then!

**Comment by MichaelClerx** [comment]
@martinjrobins turns out we discussed this before :-)

**Comment by martinjrobins** [comment]
oh good. Its less likely I'm doing something stupid then :)

**Comment by MichaelClerx** [comment]
Closing for now
