### ISSUE TITLE
Duplicate dependency lists

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#565]
Could we get rid of the `requirements` folder and just let `setup.py` do the installing? I'm doing this for Myokit and it works fine. It stops us from having to maintain two separate lists.

The only downside I can see is that devs can't `pip install requirements/dev.txt` to get the requirements without also installing the pints module

**Comment by martinjrobins** [comment]
Sounds good, I don't think this is much of a downside, so +1 for letting setup.py do all the installation
