### ISSUE TITLE
Add heatmap as an option for pairwise plot

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#566]
@mirams suggests to bring back heatmap as an option for `pints.plot.pairwise`.

I cannot remember exactly why we moved away from it and use only scatter/kde plots, because I certainly remember I used to do heatmap instead of scatter/kde plots.

I think if there is no objection of adding it as an option, I will quickly do it with all other pints.plot tickets that I owe. @ben18785 @sanmitraghosh @MichaelClerx?

**Comment by MichaelClerx** [comment]
Stick 'm in separate PRs though, will make it easier to merge!

**Comment by MichaelClerx** [comment]
Fixed in #623
