### ISSUE TITLE
Check out travis windows support

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#579]
If it works we can remove appveyor and simplify our set up

**Comment by MichaelClerx** [comment]
Appveyor is the bottleneck in our tests right now, so would be really good to have this. At the moment it still seems too experimental though.

- Docs still largely empty: https://docs.travis-ci.com/user/reference/windows/
- Billed as "early release" https://blog.travis-ci.com/2018-10-11-windows-early-release

(See also: https://github.com/MichaelClerx/myokit/issues/264)

**Comment by MichaelClerx** [comment]
This isn't looking _too_ bad: https://github.com/cclauss/Travis-CI-Python-on-three-OSes

Any experience @martinjrobins and @fcooper8472 ?

**Comment by MichaelClerx** [comment]
https://github.com/cclauss/Travis-CI-Python-on-three-OSes

A start, but only one Python version

**Comment by martinjrobins** [comment]
no, havn't tried it yet. Only on python version is a bit limiting :(

**Comment by fcooper8472** [comment]
I've looked into it before - but the 3-OS support seems much more mature on Azure (which we've been using for a while!)

**Comment by MichaelClerx** [comment]
See also #1074

**Comment by MichaelClerx** [comment]
All on actions now :D
