### ISSUE TITLE
Add an (optional?) time-out on the parallel evaluator

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#587]
Logs occasionally look like this:

```
3060  30610 -6.33e+07  35:03.9
3080  30810 -6.3e+07   35:17.8
3100  31010 -6.29e+07  35:31.9
3120  31210 -6.28e+07  35:46.1
3140  31410 -6.28e+07  36:00.1
3160  31610 -6.28e+07 680:57.2
3180  31810 -6.28e+07 681:11.2
3200  32010 -6.28e+07 681:24.8
3220  32210 -6.28e+07 681:38.4
```

even in situations where it's very unlikely the method should take any longer/shorter (e.g. no adaptive solving or anything). Presumably worker processes are not returning here for whatever reason. It'd be good to have something in the parallel evaluator that terminates workers that have exceeded a certain running time.

(Not sure if the `join` method could lead to hang-ups too, when discarding workers that are unresponsive?)

**Comment by MichaelClerx** [comment]
Does anyone else see things like this? @chonlei ? @martinjrobins ?

**Comment by MichaelClerx** [comment]
Now wondering if this is a tmux thing. It keeps resolving itself as soon as I log in...

**Comment by MichaelClerx** [comment]
Definitely something weird going on using parallel optimisation with tmux. Things occasionally get stuck, but then start going again when I check up on them

**Comment by chonlei** [comment]
> Does anyone else see things like this? @chonlei ? @martinjrobins ?

Not to that extreme...

**Comment by MichaelClerx** [comment]
To be honest I've not had it for ages, maybe I was using tmux wrong?
