### ISSUE TITLE
Add tests for different input shapes for every likelihood / error measure

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#606]
They should all be tested (and work for)
- Single-value data of shape ``(n_times,)`` (or just a list)
- A NumPy array of shape ``(n_times,1)``
- A NumPy array of shape ``(n_times, n_outputs)`` where n_outputs > 1

See #604, #605

**Comment by MichaelClerx** [comment]
Might also be worth discussing if things'd be easier we had ``(n_outputs, n_times)`` and ``(n_times)`` as the required formats

**Comment by DavAug** [comment]
Before I start testing I just want to clarify how the test may be best structured.

In test_error_measures.py are some error functions tested for single and for multi-output data and those are organized in separate tests. This can be straightforwardly done for all error functions and likelihoods. As far as I can see is the data for the single output problem here always `(n_times,)` or a list.

Would it be best to write yet another test which is structured exactly the same but passes data as `(n_times, 1)`? Or can this be done more elegantly?

**Comment by MichaelClerx** [comment]
I would write something in one test and then just copy-paste it into the other tests, bit repetitive but makes it easier to debug and add exceptions and such?

**Comment by DavAug** [comment]
Ok, so I write for example a `test_input_shape_mean_squared_error` and then I can check with `self.assertRaisesRegexp` that certain errors are thrown for wrong input shapes. But what's the best way to check that no error is thrown? Something like 
```
try:
    pints.MeanSquaredError(p)
except:
    raise ValueError(...)
```
or is it sufficient to just test the exceptions, because the functionality for lists and multi-output problems is tested in other tests.

**Comment by MichaelClerx** [comment]
Yup, test the exceptions as above! But also do a quick check to see if the other tests cover all three cases. 

It might even be worth it to bring all these tests in some kind of standardised format? But not a requirement for this ticket.

**Comment by DavAug** [comment]
Ok, thanks.

**Comment by DavAug** [comment]
The way `pints.vector` works, any input of shape `(1,1,1,...,1, n_times, 1, ..., 1)` will also be accepted by the single output problem. Is that ok, or should there be any exceptions?

**Comment by MichaelClerx** [comment]
Yeah that's fine. It's to get rid of differences like (n, 1) vs (n, ) and even (1, n) and your example :-)

**Comment by DavAug** [comment]
As I am writing the tests, I'm starting to wonder whether it really makes sense to test the various input shape exceptions on the error measure level. 
All exceptions are thrown on within the problem already. So wouldn't it make more sense to test the input shapes in the problem tests and then just assert that the problem passed to the error is a `pints.SingleOutputProblem` or `pints.MultiOutputProblem`?

**Comment by MichaelClerx** [comment]
Not sure I follow!
The idea is more to check that the __call__ methods like these:
```
class MeanSquaredError(ProblemErrorMeasure):
    ....
    def __call__(self, x):
        return np.sum(((np.sum((self._problem.evaluate(x) - self._values)**2,
                               axis=0) * self._weights) * self._ninv),
                      axis=0)
```
all work with the different data sizes they can expect. As you can see that's not super obvious

**Comment by MichaelClerx** [comment]
So just make sure that there's tests that call each error/pdf with each of the three shapes, (and check the correctness of the output)

**Comment by DavAug** [comment]
Another potentially unrelated question: The weights are currently just multiplied, without any normalization. Would it make sense to divide the error also by the total weight or does this introduce more problems than it solves?

**Comment by MichaelClerx** [comment]
That's the next one, the NormalisedRootMeanSquaredError :D
There's many different measures all with their own ups and downs, we can add as many as we like :-)

**Comment by DavAug** [comment]
Haha ok.

**Comment by DavAug** [comment]
I was using the 'ConstantModel' for testing and is it possible that the simulateS1 implementation is not correct?

The model is defined as 

`f(t) = (p_1, 2 p_2, 3 p_3, ..., n p_n)`

But the partial derivatives are currently computes as 

`del f / del p_n = 1` 

for all n. For example for `n_times.shape = (3,)` and `n_parameters.shape = (2,)` we get at the moment

```
dy = np.tile(np.diag(np.ones(2)), (3, 1, 1))
print(dy)

array([[[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]]])
``` 

when it really should be `del f / del p_n = n`, i.e. 

```
array([[[1., 0.],
        [0., 2.]],

       [[1., 0.],
        [0., 2.]],

       [[1., 0.],
        [0., 2.]]])
```

**Comment by DavAug** [comment]
Can we create another issue for this, so I can fix this quickly and finish the tests for this issue?

**Comment by MichaelClerx** [comment]
> Can we create another issue for this, so I can fix this quickly and finish the tests for this issue?

Sure!

**Comment by DavAug** [comment]
See #1122

**Comment by DavAug** [comment]
Changes in `ConstantModel` have been merged into this branch.

**Comment by DavAug** [comment]
PR #1125
