### ISSUE TITLE
add AR1 Log Likelihood

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#607]
Add AR1 noise Log Likelihood as provided by @ben18785

**Comment by martinjrobins** [comment]
added class, can you please check the implementation @ben18785, I was a little confused with your `t` index, should that be `i`?

@mirams, you can use this branch (issue-607-ar1) to test the ar1 likelihood on your data

note: the implementation still needs:
- [ ] testing
- [ ] documentation added

**Comment by ben18785** [comment]
Think all looks good! Thanks Martin!

**Comment by martinjrobins** [comment]
PR #663 forgot to add documentation for this class, and the ARMA one. This needs to be corrected to resolve this issue

**Comment by sanmitraghosh** [comment]
@martinjrobins @ben18785 I know a AR(1) model as:

Y(t) = C + phi1*Y(t-1) + white noise, white noise~Normal(0, sigma^2). And the corresponding likelihood shall be:

Normal(Y(t); C + phi1*Y(t-1), sigma^2). But I can't really understand either the AR(1) model here or the likelihood, can you please explain.

Word of caution:

If you want to implement a model:
X(t) = X(t-1) + q(t)
Y(t) = F(t,theta) + X(t) + r(t),  where q(t)~Normal(0,sigma_state^2) and r(t)~Normal(0,sigma_measurement^2).

Then, that is a state-space model where you have to run the forward filtering/backward smoothing algorithms to get the likelihood. Bacause of non-linear dependence of F(t,theta) the solution requires modern algorithms such as the [Particle MCMC](https://www.stats.ox.ac.uk/~doucet/andrieu_doucet_holenstein_PMCMC.pdf)
