### ISSUE TITLE
Toy models __call__() accept more than one input vector

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#612]
Some toy models (haven't checked all), but for example NoramlLogPDF:
```
>>> norm = pints.toy.NormalLogPDF([0], [1])
>>> norm([1])  # this is fine
-1.4189385332046727
>>>
>>> norm(1)  # this is not cool, why scalar...
-1.4189385332046727
>>> norm([1, 3])  # even worse, wrong number of parameters
array([-1.41893853, -5.41893853])
>>> norm([[1], [3]])  # attempting to give two inputs?
array([-1.41893853, -5.41893853])
```

I think except the first one, the rest is not acceptable according to Pints interface.

**Comment by MichaelClerx** [comment]
That's right, the input to __call__ should be (something that can be converted to) an array of shape `(n_parameters, )`
And the output should be a single number
