### ISSUE TITLE
Close figure objects in unit test

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#620]
Currently in unit test for `pints.plot`, it creates a lot of figure objects and leave them there. Maybe do

```
pints.plot.blablabla()
plt.close('all')
```

But that we have to `import matplotlib.pyplot` in the unit test.

(Cannot just do `fig, _ = pints.plot.blablabla(); plt.close(fig)`, this will leave only remove the stuffs in the figure but not the figure itself.

**Comment by MichaelClerx** [comment]
Any luck @chonlei ?
