### ISSUE TITLE
StudentTLogPrior investigate implementation

### ISSUE THREAD

**Issue by fcooper8472** [pints-team/pints#621]
Look at:

* inherit from `LogPrior`
* Number of params

**Comment by MichaelClerx** [comment]
See also #573

**Comment by MichaelClerx** [comment]
Hold on, still doesn't inherit from LogPrior!

**Comment by fcooper8472** [comment]
I'll tidy that up in #47

**Comment by fcooper8472** [comment]
The fix is now in the branch for #47 which will be merged (hopefully) soon, so closing this issue.
