### ISSUE TITLE
Change naming of e.g. `MCMCSampling`

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#622]
Perhaps to `MCMCRoutine` or `MCMCSamplingRoutine` ?

The current name is proving to be unhelpful

Ideas?

**Comment by chonlei** [comment]
Short name would be preferred, as this (or `mcmc_sample`) is probably the one that people use the most!! Why not just `MCMCSample`?

**Comment by MichaelClerx** [comment]
@martinjrobins and @ben18785 suggested MCMCController, as it controls an MCMCSampler

**Comment by MichaelClerx** [comment]
@ben18785 @martinjrobins what name should we give `Optimisation` then? `OptimisationController` ?

And what about nested sampling?

**Comment by MichaelClerx** [comment]
I do like the name `Optimisation`, although I guess it's a controller too... Perhaps better to be consistent?

**Comment by MichaelClerx** [comment]
Fixed in 66efb27c26b6352c99f7e80a1efbb15e4cf9d817
