### ISSUE TITLE
Rename KnownNoiseLogLikelihood and UnknownNoiseLogLikelihood

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#626]
All the other distributions are named according to their distribution. So I propose changing these to:

- GaussianLogLikelihood
- GaussianKnownSigmaLogLikelihood

This makes it explicit what we're doing since 'noise' can mean anything.

Also, this teaches people who may not be au fait with statistics what we need to do to define a statistical problem.

**Comment by MichaelClerx** [comment]
Sounds fair.
Is there any reason to prefer Gaussian over Normal?

**Comment by ben18785** [comment]
Nope. Happy to replace “Gaussian” with “Normal”. 

What’s the simplest way to change this throughout PINTS? Some sort of command line regex find/replace?

**Comment by MichaelClerx** [comment]
> Nope. Happy to replace “Gaussian” with “Normal”.

I'm fine with either, just wondering :-)

Yeah some sort of find/replace should do it. The notebooks will be the most work, I expect - all the other code is "covered" by unit tests so we should get errors if we forget to replace them.

(On the other hand, we might want to keep the old ones too but make them log warnings for at least a year or so, they are used _a lot_)

**Comment by mirams** [comment]
I suppose Gaussian has the advantage of not being mixed up with Usual / Default (even if it is!)

**Comment by ben18785** [comment]
- Also noticed that we use normal versus Gaussian in the toy distributions. Needs to be made consistent...
