### ISSUE TITLE
Set up general framework for plotting

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#63]
Requirements:

- Cleanly separated from the optimisation / inference code
- No graphical packages should be imported unless explicitly specified. So that everything can run without an X server (e.g. on servers), and on different platforms. In addition, loading graphical packages can be a state-changing operation (for example, you can't set the matplotlib backend if someone else has already touched matplotlib in the same process)
- Minimal dependencies (e.g. seaborn etc. only if they provide some killer feature)

**Comment by MichaelClerx** [comment]
From Slack:

> **Michael:** Having a good discussion with martinjrobins and chon here about plotting
> The main question is: Should we have plotting in Pints?
> One goal of Pints (as chon) mentions, was to re-use and share code throughout the group. So from this point of view it makes a lot of sense
> **Martin:** My opinion is that there should be minimal or no plotting functionality, since we are not a plotting library.
> **Michael:** And since it creates a bunch of issues, I'm coming round to martin's side!
> *But* we could definitely add a bunch of examples that show all the different plots, so that people can copy/paste and then customise
> (Because you always want to customise right?)
> **Gary:** Can’t we just plot with simple matplotlib scripts? A handful of them for common output like Ross’ nice MCMC matrix plot, makes a lot of sense?
> **Michael:** Yeah absolutely, but it's hard to stick them in a library without (1) adding dependencies or (2) making accidental errors (causing Pints not to run on headless systems / servers etc.)
> **Gary:** a folder of example plot scripts that are updated to work with output from various pints things makes sense to me. Don’t need to be ‘in’ the library.
> (Jonathan, Martin, and Michael agree)
> **Martin:** yea, agree with "example plot scripts" you can cut and paste

**Comment by MichaelClerx** [comment]
Unless anyone has any examples this ticket has then become:

- [ ] Finish #67
- [ ] Add some example plot scripts

**Comment by MichaelClerx** [comment]
@ben18785 @martinjrobins @mirams @sanmitraghosh Have a look at the four examples @chonlei placed in #88 

Is that the best way to do an autocorrelation plot?
And these look quite bulky! Are we sure we shouldn't add them as convenience functions?

**Comment by MichaelClerx** [comment]
I'm still undecided

**Comment by martinjrobins** [comment]
My main issue with convenience functions for the plotting is that I can see them quickly growing into very complicated functions as people put in more and more customisation options for the plots, based on whatever they need at the time. I definitely don't think any convenience functions should be used in the examples, cause wasn't the point to show how you can generate plots from PINTS results? If it is all hidden away in convenience functions then the user will be left no wiser about how to do the actual plots that they want.

**Comment by ben18785** [comment]
I would say that we just want one command that plots, say, four of the
diagnostic graphs. Honestly, I would be put off using an MCMC package that
didn't provide them as standard, and I'm sure others would too. If people
want to tailor the graphs, they can look at the source code to the
functions (or perhaps examples which contain full code).

**Comment by MichaelClerx** [comment]
@sanmitraghosh is saying something similar (right now, in our office :D )

@martinjrobins and I are coming around to the idea of having _diagnostic_ plots. 

What we could do is (1) leave the examples so people can see how to do fancy plots that they can customise. And (2) add diagnostic methods that create and return a full figure, but with zero customisation options and comments/docstrings that make it very clear these are not meant to be customised?

**Comment by ben18785** [comment]
Sounds good to me! That's standard practice with MCMC software.

Are we still on for 3pm today Michael?

**Comment by MichaelClerx** [comment]
Since there's a big time difference between kde and histogram plots, I think that would lead to 5 plot functions?

- [ ] `pints.plot.trace_plot(chain)`
- [ ] `pints.plot.autocorrelation(chain)` --> acorr for all parameters!
- [ ] `pints.plot.predictions(chain, problem)`
- [ ] `pints.plot.histogram(chain)`
- [ ] `pints.plot.kde(chain)`

Perhaps `pints.diag` or `pints.diagnostic` instead of `pints.plot` to make our intentions clear? And are the names for the last two methods ok?

**Comment by MichaelClerx** [comment]
@ben18785 yes 3 o'clock! (y)

**Comment by ben18785** [comment]
Great, see you then!

What does 'chain' mean in the above? The reason I ask is because trace
plots cannot be done unless you have more than one chain. I think the names
are fine. Would the autocorrelation plot produce one plot for each
parameter? I think that's what we want...

**Comment by MichaelClerx** [comment]
`chain` here would be the `chain` variable from the examples, which is an `n` by `d` matrix where `d` is the number of parameters and `n` is the number of points in the time series

**Comment by ben18785** [comment]
Ok. Is 'chain' for one Markov chain or many Markov chains? If the latter,
not sure we want to call it that...

**Comment by MichaelClerx** [comment]
Just the one! We haven't done anything with repeated runs yet

**Comment by ben18785** [comment]
Ok, still not sure we'll want to call the return value chain...can discuss
later!

**Comment by chonlei** [comment]
See PR #103

**Comment by MichaelClerx** [comment]
Closing this now, as we've made all the important decisions :-)
