### ISSUE TITLE
Investigate Python properties for use in setters and getters

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#632]
[This](https://stackoverflow.com/questions/2627002/whats-the-pythonic-way-to-use-getters-and-setters) suggests that we could have a single call to allow us to both set and get values from classes, which would reduce the size of namespace we are using by about a half.

What are peoples' opinion on these things? Naively, I am drawn to them since it'd mean users of PINTS would have fewer things to remember.

**Comment by MichaelClerx** [comment]
Hi @ben18785 ! 

Personally, I don't like this style, as it makes calling a function look like setting a property: Writing `obj.x = 5` looks like an assignment, and so should change some state, run as a single operation (change where `x` points to), and not have any side effects... 

We follow the convention set with `obj.set_x()` and get with `obj.x()` throughout Pints, so don't see much of an issue with remembering things there?

**Comment by martinjrobins** [comment]
I'm ok with using python properties for getters and setters, I've learned to accept that in python `obj.x = 5` probably means you are actually calling a function :)

The main issue is that pints needs to be consistent, we are currently using explicit getters and setters everywhere, so if we wanted to swap to properties someone would have to go back and change everything. 

I'd be happy to let someone else do that if they had the motivation, but I don't think there is a very good reason to change at this stage.

**Comment by MichaelClerx** [comment]
> I'd be happy to let someone else do that if they had the motivation, but I don't think there is a very good reason to change at this stage.

+1
