### ISSUE TITLE
How to set parameters of a sampler?

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#634]
I constantly find myself having to do, for example:

sampler = pints.NestedSampling(log_likelihood, log_prior, method=pints.NestedEllipsoidalSampler)

sampler._sampler.set_hyper_params(...)

This was following suit (I think) with the way the other sampling algorithms are implemented.

Is there a better way to handle this? To me it seems wrong that the sampler parameters should be accessed by an internal member function.

Is there a way we can have the sampling object subsume all the parameter set/get methods of the sampler being used? These would then change the parameters of all the samplers being used by the sampling object.

**Comment by MichaelClerx** [comment]
> sampler = pints.NestedSampling(log_likelihood, log_prior, method=pints.NestedEllipsoidalSampler)
> sampler._sampler.set_hyper_params(...)

Agreed that this is wrong!

> Is there a way we can have the sampling object subsume all the parameter set/get methods of the sampler being used? These would then change the parameters of all the samplers being used by the sampling object.

That's fairly simple to do I think, but seems a bit messy to me. Lets see if we can think of a cleaner solution...

**Comment by martinjrobins** [comment]
we could tidy it up like so:
```python
sampler.get_sampler().set_hyper_params(...)
```
But I would not like this:
```python
sampler.set_hyper_params(...)
```
the reason being that it is disguising what it is actually doing (i.e. setting the hyper-params of the internal sampler object). I think the sooner a PINTS user learns that pints.NestedSampling is a generic object that has an internal ask-tell sampler object, the better.

**Comment by MichaelClerx** [comment]
We currently have the `sampler()` and `samplers()` methods that let you access the underlying samplers:

https://github.com/pints-team/pints/blob/master/pints/_mcmc/__init__.py#L678-L702
