### ISSUE TITLE
Return log-likelihood at each sampled value

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#640]
I remember we had a discussion about this previously (I've looked through the issues but couldn't find the relevant one). 

We need code that returns the log-likelihood at each sample value. Do we have this implemented currently? I couldn't see it in the mcmc class.

Quite a few things depend on this: marginal likelihood estimators and model comparison stuff for example. Happy to implement this myself but want to check that no one else has done so yet.

**Comment by MichaelClerx** [comment]
Hi @ben18785 !

We've got code for logging this to disk, but not returning in memory just yet

https://github.com/pints-team/pints/blob/master/pints/_mcmc/__init__.py#L444-L470
https://github.com/pints-team/pints/blob/master/pints/_mcmc/__init__.py#L568-L578

We can certainly discuss adding this tomorrow, perhaps in light of #329 as well

**Comment by MichaelClerx** [comment]
Discussing during pints meeting with @martinjrobins @ben18785 and @MichaelClerx 

We think the best thing to do is to start storing this (and other things!) in the MCMCSampling and Optimisation classes. They are "single-use" objects already, so it makes sense to start using them as their own "result objects" (#329 #154 #129)

So the changes to the interface would be e.g.:

- run() still outputs the chains
- add a `set_loglikelihood_storage(store)` or similar, plus a get method for the setting
- add a `get_stored_loglikelihoods()` method or similar

Further, we could add a 
- `get_chains` to get the chains a second time (or in case people want to get everything via get_...)
- `set_chain_storage()` or similar, to disable chain storage in memory #584

**Comment by MichaelClerx** [comment]
> We've got code for logging this to disk, but not returning in memory just yet

See if there's some way to use the logging methods for this --> log to screen, disk, or memory

**Comment by MichaelClerx** [comment]
Hey @martinjrobins , what do you think:

`run()` returns all chains, except if `set_chain_storage(False)` is called, in which case it returns None

I'm now adding a `set_evaluation_storage()` method. Should that also update the output of `run()` ? Or should the evaluations be retrieved using a separate method?

**Comment by MichaelClerx** [comment]
Going with `set_log_pdf_storage()` and `log_pdfs()` for now to enable storage and retrieve the evaluations

**Comment by martinjrobins** [comment]
sounds good. I would have `set_evaluation_storage()` update the output of `run()` to be consistent with `set_chain_storage()`

**Comment by MichaelClerx** [comment]
Hmmmm, does everyone think that changing the returned value is a good idea? I've kinda gone off it now :D
@ben18785 @fcooper8472 ?
