### ISSUE TITLE
Add value-based tests for toy problems / distributions

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#649]
Just freeze them in place.

**Comment by ben18785** [comment]
Want to go through and look at log-likelihoods, log-priors, log_pdfs and all solutions to ODEs and set value-based tests for all these.

**Comment by ben18785** [comment]
Splits the issue up into smaller chunks: #721 #720 #719 #718

**Comment by MichaelClerx** [comment]
Thanks!
