### ISSUE TITLE
Add distance measures and suggested bounds for toy log_pdf problems

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#659]
Added suggested bounds:

- [x] annulus
- [x] cone
- [x] high dimensional normal
- [x] twisted Gaussian
- [x] Rosenbrock
- [x] Multimodal normal
- [x] Simple eggbox

Added distance function between samples and true distribution:

- [x] annulus
- [x] cone
- [x] high dimensional normal
- [x] twisted Gaussian
- [x] Rosenbrock
- [x] Multimodal normal
- [x] Simple eggbox

All toy log_pdfs will have a single `distance` function that yields some measure of distance from the true distribution to the samples for @martinjrobins performance testing for PINTS paper.

**Comment by MichaelClerx** [comment]
Closed in #699
