### ISSUE TITLE
Add examples/recipes of plots for posterior model-predicted time series

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#66]
Plots so far only concern about the parameters, but it would be good to compare the posterior model-predicted time series with the observed data. 

E.g. add posterior mean (80% prediction interval) model-predicted time series with the 10th and 90th percentiles of the prediction intervals, as well as dots as observed data (i.e. pints.SignleSeriesProblem( . ).values() ).

**Comment by chonlei** [comment]
And/or use each sampled parameters (from the MCMC chain) from the posterior to compare the posterior model-predicted time series with the observed data.

**Comment by ben18785** [comment]
I wholeheartedly agree with this sentiment -- this is a must for model validation in PINTS.

**Comment by chonlei** [comment]
Working on it, see: https://github.com/pints-team/pints/blob/mcmc-plot-examples/examples/plot-mcmc-fitting-result.ipynb

**Comment by chonlei** [comment]
Done in #88
