### ISSUE TITLE
Real data examples

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#675]
Do we currently have any real data examples in PINTS? I think that these - so long as the data were relatively few - would offer some really nice applied examples.

In particular, I think it would be difficult to illustrate the importance of #661 without them.

What do people think about this? Wasn't thinking a tonne of examples, maybe only handful to begin.

If people are pro, how would we include them?

**Comment by MichaelClerx** [comment]
There's this one: https://github.com/pints-team/pints/blob/master/examples/toy-model-sir.ipynb

**Comment by MichaelClerx** [comment]
There's now also the german credit score problems #1049, which has downloading data in it, so that  answers this I guess:

> If people are pro, how would we include them?

Ready to close this one @ben18785 ? Could always add tickets for specific data sets once we think of them

**Comment by ben18785** [comment]
Yep, happy to close...
