### ISSUE TITLE
AR1 and ARMA1 errors need a bit more documentation

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#676]
Seems both Simon and Sanmitra don't think the stated log likelihoods are obvious, so would be good to have a bit more of the derivation in the docstrings

**Comment by MichaelClerx** [comment]
This could be a good one for @ben18785 or @rcw5890 to pick up?

**Comment by rcw5890** [comment]
I'd be happy to give this a shot

**Comment by MichaelClerx** [comment]
Thanks!

**Comment by rcw5890** [comment]
Closed in #1093
