### ISSUE TITLE
Rosenbrock we use is actually 1 / Rosenbrock

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#691]
Need to change notebook as text is currently incorrect.

**Comment by MichaelClerx** [comment]
You mean for the pdf version? Or both pdf and error?

**Comment by ben18785** [comment]
Just the pdf, yep. The function for optimisation is fine. (And it was only
the text that was incorrect.)

**Comment by MichaelClerx** [comment]
Closed in  #692

**Comment by MichaelClerx** [comment]
Cool! Thanks
