### ISSUE TITLE
Value-based tests for log-likelihoods

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#719]
Log likelihoods:
- [x] AR1LogLikelihood
- [x] ARMA11LogLikelihood
- [x] CauchyLogLikelihood
- [x] GaussianKnownSigmaLogLikelihood
- [x] GaussianLogLikelihood
- [x] ScaledLogLikelihood
- [x] StudentTLogLikelihood

**Comment by MichaelClerx** [comment]
Closed in #728
