### ISSUE TITLE
Value-based tests for toy distributions

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#720]
Toy distributions:
- [x] Gaussian
- [x] Rosenbrock
- [x] Twisted Gaussian
- [x] Simple egg box
- [x] Multimodal Gaussian
- [x] Annulus
- [x] Cone
- [x] Neal's funnel

**Comment by ben18785** [comment]
Need to wait until #699 is merged as this contains updated distributions.

**Comment by MichaelClerx** [comment]
It's merged!

**Comment by ben18785** [comment]
Just checked all these distributions and all now have value-based tests (must have happened at an earlier merge).
