### ISSUE TITLE
Value-based tests for toy models

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#721]
- [x] Constant
- [x] Beeler-Reuter
- [x] Fitzhugh-Nagumo
- [x] Goodwin Oscillator
- [x] HES1 Michaelis-Menten
- [x] HH IK
- [x] Logistic model
- [x] Lotka-Volterra
- [x] Repressilator
- [x] SIR model

**Comment by MichaelClerx** [comment]
For what it's worth I've just checked both Fitzhugh-Nagumo and the Logistic model against an external implementation (sensitivities included) :D
