### ISSUE TITLE
Add inverse-gamma and log-normal priors

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#725]

**Comment by ben18785** [comment]
Also add sensitivities for these priors

**Comment by fcooper8472** [comment]
I'm also adding one thing to this issue: I have changed my mind about implementing Cauchy in terms of student-t, because the pdf really is a lot simpler, so will quickly re-implement Cauchy from scratch.

**Comment by fcooper8472** [comment]
Closed by #736
