### ISSUE TITLE
Add sensitivities for all priors in PINTS

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#726]
- [x] BetaLogPrior
- [x] CauchyLogPrior
- [x] ComposedLogPrior
- [x] ExponentialLogPrior
- [x] GammaLogPrior
- [x] GaussianLogPrior
- [x] HalfCauchyLogPrior
- [x] InverseGammaLogPrior
- [x] LogNormalLogPrior
- [x] MultivariateGaussianLogPrior
- [x] StudentTLogPrior
- [x] UniformLogPrior

**Comment by MichaelClerx** [comment]
Todo: 

- [ ] Add list of priors that need sensitivities to this ticket
