### ISSUE TITLE
Look at sanmitra's concerns about AR1 model

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#734]
https://github.com/pints-team/pints/issues/607#issuecomment-461435323

The docs should probably become a bit more clear about what and why we're doing, maybe with more literature references?

**Comment by sanmitraghosh** [comment]
Also the likelihood calculation of any moving average type model ARMA is non-trivial, as the hidden noise series/path needs to be handled carefully. One approach is conditional likelihood (conditioned on the first sample of the path) or for unconditional likelihood a method called Backforecast. 
There are a plenty of good literature on time series and those should be followed/referred.

**Comment by ben18785** [comment]
@sanmitraghosh We're using the conditional log likelihood here and so think all is ok. The generative model matches the inferential algorithm and so am fairly confident all is well.

**Comment by sanmitraghosh** [comment]
@ben18785 Can you explicitly write somewhere what the model is, I mean what your assumption is?
For example are you saying that the residual R(t) =Y(t) - F(t,theta) follows an ARMA(1,1) process ?
