### ISSUE TITLE
Maths in docstrings

### ISSUE THREAD

**Issue by fcooper8472** [pints-team/pints#735]
At the moment all maths in docstrings requires the escaping of each backslash character, which ends up looking messy.  For instance, here's the start of one docstring:

```python
"""
    Defines a gamma (log) prior with given shape parameter ``a`` and rate
    parameter ``b``, with pdf

    .. math::
        f(x|a,b)=\\frac{b^a x^{a-1} e^{-bx}}{\\mathrm{\\Gamma}(a)}
...
```

If you make the docstring a raw string literal by adding `r` to the start of it, the escape characters are no longer needed.  This makes the formulas look a lot nicer, and is how (for instance) numpy and scipy do their docstrings:

```python
r"""
    Defines a gamma (log) prior with given shape parameter ``a`` and rate
    parameter ``b``, with pdf

    .. math::
        f(x|a,b)=\frac{b^a x^{a-1} e^{-bx}}{\mathrm{\Gamma}(a)}
...
```

I think we should adopt this going forward and, eventually, rework the existing docstrings.

**Comment by ben18785** [comment]
That’s good to know. Thanks Fergus!

**Comment by MichaelClerx** [comment]
Anyone feel like going over the docs for this? Or making a list of docs that need adapting?

**Comment by MichaelClerx** [comment]
Nobody?

**Comment by MichaelClerx** [comment]
It seems that if we use raw strings, we can drop one of our exceptions from the flake8 configuration too:

https://github.com/ModellingWebLab/project_issues/issues/43#issuecomment-521605747

**Comment by MichaelClerx** [comment]
In fact, @fcooper8472 do you think we should update our flake8 config to complain about bad escape sequences again? That would maybe help us identify cases where we need to use a raw string

**Comment by fcooper8472** [comment]
I didn't know we had explicitly turned it off!  I'd say, yes, let's not allow invalid escape sequences, and any docstrings that contain maths can be `r""""""` strings.
