### ISSUE TITLE
Add script to check all "slow notebooks" exist on travis

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#757]
When notebooks that are listed as "slow" are renamed, the cron job falls over.

It'd be nicer if we have a test on travis PRs that checked this. @fcooper8472 this should be an easier one?

Pretty much a for-loop over the contents of https://github.com/pints-team/pints/blob/master/.slow-books (minus comments)

**Comment by fcooper8472** [comment]
@MichaelClerx  why do some in that list end in `ipynb` and some don't?

**Comment by MichaelClerx** [comment]
Good question! Maybe I was being lazy? Or maybe I made a parser that could handle both and wanted to test it... Feel free to change the rules here, no strong feelings from me!

**Comment by fcooper8472** [comment]
Fair enough.  When I do this one I'll add the extensions to each.  Since this is also essentially documentation (documenting which books are slow), it can go in as another doctest.

**Comment by MichaelClerx** [comment]
>  Since this is also essentially documentation (documenting which books are slow), it can go in as another doctest.

Hmmmmm! OK it can go in there but because the notebooks themselves are part of the documentation :D
