### ISSUE TITLE
Split problems into their own repositories

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#76]
Now that we've worked out how to use Pints in other projects while developing it at the same time (see #61), we can move the projects out of the pints repo.

This will make our codebase nice and compact, and to-the-point :-)

- [x] sip/sensai
- [x] electrochemistry
- [x] ikr-sine-wave

We can still use this github repo to coordinate these projects, just stick them in separate repos (see for example https://github.com/ModellingWebLab

**Comment by MichaelClerx** [comment]
We could create a (free) Pints organisation for this purpose. Shall I do that?

**Comment by mirams** [comment]
I would be careful with this, nice to have tests that check all your working problem examples aren't broken by interface changes in a rapidly evolving codebase. Do the 'problems' have any tests yet? 

Would be good for them to, so the person who breaks anything can update them all and check the problems still get the same answers, even if these are longer (nightly?) tests... Otherwise you need some method of automatically running all the problems and checking they work with latest Pints and alerting people that they need updating. I would have thought at this stage it is easier to have them in the subfolder with some testing.

**Comment by martinjrobins** [comment]
The electrochem folder has tests, which I currently need to reduce the time taken by!

I would be in favor of moving out sip/sensai, as I recall this is a huge subdir (15M), and I don't think everyone wants to download it when they clone pints. Note that this will be a pain to do, as you would need to purge the entire history of the directory to fully remove it! I'm on the fence about the other two, but think it is in general a good idea to move specific projects to other repos. For example, I have a private electrochem project that has data in it. I don't think testing them is a problem as they can just add pints as a  submodule. Then whenever a project upgrades their submodule, its own set of tests will be kicked off and test the new pints version.

**Comment by MichaelClerx** [comment]
@jonc what do you think about this problem of testing dependent projects still work (and using that as a way to test your software) ?

**Comment by jonc125** [comment]
There are several ways you can do it.
- As Martin says a project can depend explicitly on a specific version on pints via a submodule, then you only test against new pints when desired. The downside here is it's harder to see if changes in pints will break the project, so less helpful from a 'developing pints' point of view. This approach would probably be more common if the project was developed by a separate team, who only wanted to take pints updates occasionally.
- The project can have requirements files that, for their normal tests, pin a specific version of pints as a pip dependency, but you can define an extra 'pip defrost' test in Travis etc. that runs with non-pinned requirements, and even make this an 'allowed failure'.
- You can also set 'cron job' builds in Travis so you get a regular build of the project even if it hasn't been modified, checking it still works with the latest pints.

If you are going to move projects out, its probably worth doing them all at the same time and recreating the pints history so it never included them, to reduce the repo size. And that's better done sooner than later, as everyone using the repo will need to update their clones accordingly.

**Comment by mirams** [comment]
Yeah - depends whether you want it to be:
 * the responsibility of the pints developers to keep the projects working, 
or 
 * the project owners responsibility to make changes to keep up with pints.

If you go for the second you have to be careful to introduce enough tests of all things that the projects use to make sure wanted functions aren't lost/removed. Plus keep some sort of log of API changes so people know what to change to get it working again. I would be tempted to go for the first to let the problems drive the development and speed things up at the moment. Perhaps when it is more stable the second makes sense?

**Comment by MichaelClerx** [comment]
Sounds good. Let's leave this for now then

**Comment by MichaelClerx** [comment]
Thinking about this again!

> You can also set 'cron job' builds in Travis (daily/weekly/monthly) so you get a regular build of the project even if it hasn't been modified, checking it still works with the latest pints.

I think if we created an electrochemistry project and set this up, everything'd be fine?

**Comment by MichaelClerx** [comment]
This is done now! @martinjrobins We'll need to set up a new travis thing for the echem project. I've adapted the yaml file and added pints as a submodule, so hopefully that should work straight away!
