### ISSUE TITLE
Investigate stochastic gradient descent as a type of approximate inference algorithm

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#764]
See [here](http://www.jmlr.org/papers/volume18/17-214/17-214.pdf).

Really interesting because the paper shows that we can view an optimisation algorithm (SGD) as a type of approximate inference algorithm. Can we also show this for other algorithms, like CMAES?

**Comment by MichaelClerx** [comment]
Still on the table for CMA-ES, but closing this now as we're not too interested in the cases where SGD is useful (large data sets)
