### ISSUE TITLE
Switch func testing from cronjob to buildbot or jenkins?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#774]
@fcooper8472 says that way we can keep using skip to actually run the tests, but we get a nice interface for e.g. scheduling things, alerting us of failures etc.

Seems worthwhile?

**Comment by MichaelClerx** [comment]
And @fcooper8472 did it, too!

**Comment by MichaelClerx** [comment]
@fcooper8472 just checking; did you disable the cron-job @martinjrobins had set up?

**Comment by fcooper8472** [comment]
Yes that's right: there's currently a new cron-job that's poking the `azure-ci` branch to kick off the builds, but that too will go once the yaml config allows scheduled jobs.
