### ISSUE TITLE
Change log file system to a database back-end

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#779]
We probably want to do more complex querying on test results, so it'd be good to switch to some DB back-end (i.e. sqlite). Possibly with a free-form json text field in it for everything non-standard.

Thoughts @martinjrobins ?

**Comment by MichaelClerx** [comment]
Assigning this to @iamleeg , thanks Graham!

We'll also need to host this DB somewhere*, and I'm assuming there's infrastructure (or rules) in place at CS for that, so adding @fcooper8472 in because I think you know the most about this kind of thing!
Plus, seems the kind of thing RSEs should know about :D

*An alternative to that would be to have a local DB, i.e. sqlite. 

Happy to co-operate on all of this too!

**Comment by iamleeg** [comment]
> Possibly with a free-form json text field in it for everything non-standard

How "stable" is the test result format? We might want to look at something like mongodb or postgres's document support if it's liable to change, and make the reporting tools deal with extracting normalised data. If it's fairly stable then sqlite/postgres is a good option.

> An alternative to that would be to have a local DB, i.e. sqlite.

Yes, or an alternative is to use the same DB everywhere and create ad hoc clusters with `docker-compose` for local testing, a bit more upfront effort but fewer moving parts to keep synchronised.

**Comment by MichaelClerx** [comment]
> How "stable" is the test result format?

Not very volatile! I think the main fields would stay the same over longer periods. Have a look at some results files here and see what you think: https://github.com/pints-team/functional-testing-results/tree/master/results

What does document support entail?

And how would we be sharing the DB with `docker-compose`? As in, where is it stored?

**Comment by iamleeg** [comment]
> What does document support entail?

Just that postgres has a JSON datatype so you can store schema-less data in there. If we know what shape the data is and what questions we want to answer, there's little value in using document storage.

**Comment by iamleeg** [comment]
> And how would we be sharing the DB with docker-compose? As in, where is it stored?

That would just be for local testing. You'd have an environment variable with the connection string to the database, defaulting to something like `Driver={PostgreSQL ANSI};Server=postgres.cs.ox.ac.uk;Port=5432;Database=productionDB;
Uid=user;Pwd=pass;sslmode=require;`. But for local testing (of the functional tests...) you'd launch an empty database in a Docker image and connect to that instead.

It's just moving complexity from the tool (which would otherwise need to support both sqlite and postgres, and have configuration to choose one) to the environment: the complexity is still there.

**Comment by MichaelClerx** [comment]
Cheers.
Anyone have any thoughts on if we want a client-server DB running on server somewhere, or a file-based DB like sqlite?

**Comment by iamleeg** [comment]
For the purposes of proving the concept I'll start with a sqlite DB anyway, it won't cost much to move to a different database.

**Comment by MichaelClerx** [comment]
Final(?) issue: we're getting some database locked errors, presumably arising from doing things in separate processes?

https://dev.azure.com/FergusCooper/PINTS/_build/results?buildId=530

**Comment by iamleeg** [comment]
Oops. You're right, it's due to process contention. It's possible to get sqlite3 to wait with a timeout rather than abandon connection altogether, so I'll do that. To make it work well, I also want to change the writers so that they are context managers and you can `with results_writer_generator() as w:`. Any objections before I make that change?

**Comment by fcooper8472** [comment]
No objections from me, particularly if you explain that to me at some point :)

**Comment by MichaelClerx** [comment]
Sounds good. While you're at it, could you make it so that we 1. Create a test row in the DB, then write, 2. Add "static" test-specific info, write, 3. Write test results

So three blocks where the context manager is used, I think

**Comment by iamleeg** [comment]
Ah, there's a problem here. If only one test at a time can have an open database connection, then only one test at a time can be running. There's some redesign needed. What I think we need is for `FunctionalTest#run` to connect to the database, create its row with the "uninitialised" status, then disconnect. Then it calls `_run()`, building up information in the dictionary. Then it connects _again_ and dumps everything from the dictionary into the database.

If anyone knows of any reason why this is not a good idea (and let's be honest about my track record on this bug...) speak now etc.

**Comment by MichaelClerx** [comment]
Up and running now!
