### ISSUE TITLE
Add case study about the effects of assuming independent noise on inferences.

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#78]
There is a thought that many of the models in electrochemistry and electrophysiology result in errors that show persistence over time. I would like to include a case study that illustrates the effect of assuming independent noise on the inferences that result for models with persistent errors.

**Comment by mirams** [comment]
Yeah, I think it requires new terms in the inference. At the moment we have

`observation = model_output + epsilon_noise`

So we just have the usual "epsilon_noise" to represent the experimental/observation/noise on the data as a separate little iid term. The difference between what nature is doing and what we record. This is probably fairly accurate for our problems and wants to stay. 

For persistent errors I think we could do with doing some fits with a 'model discrepancy' (delta, with correlation over time).

`observation = model_output + delta_discrepancy + epsilon_noise`

As you'll know Ben, but not everyone might, people have done this by fitting a GP for the discrepancy (a la Kennedy & O'Hagan), which would be fun to try, but it's then unclear to me how to make predictions for new situations if you do it like that...

**Comment by MichaelClerx** [comment]
Ben was also saying very interesting things about autocorrelation! (But keep in mind this is a public repo so if they get _Really Super Interesting (tm)_ we might want to use slack or something instead :-)

**Comment by ben18785** [comment]
Yep, am trying to upload my Jupyter notebook to github but am struggling to
do so! It's attached Gary and contains an example of AR1 errors for the
logistic model. I haven't assumed another additive measurement noise, but
suspect we might run into identification issues if we did.

**Comment by MichaelClerx** [comment]
Chon uploaded it (and stuck it in the branch issue#78): https://github.com/pints-team/pints/blob/b49db958c0ec0f4e7e28f1e1fd5b513101be4c8c/examples/Logistic-ODE-AR1-Stan.ipynb

**Comment by MichaelClerx** [comment]
Thanks @ben18785 that looks really good! Would you have time somewhere in the next 2 weeks to sit together and transfer this to pints methods? We could also try and work out the git issue then

**Comment by mirams** [comment]
Yeah - nice - depending on the data generating process in reality, this autocorrelation in residuals could point to a couple of perhaps distinct things:
 * auto-correlation in the observational errors (model is probably right, data is subject to some messy errors that distort the true underlying signal)
or
 * model discrepancy (model is probably wrong, data is still iid around the true underlying signal).

Either way, a check that alerts the user to this autocorrelation in residuals, and suggests further investigation, would seem to make sense.

**Comment by ben18785** [comment]
@mirams Yes, I agree -- persistent residuals could be due to either autocorrelated measurement error or persistent modelling discrepancy. I suspect, from the model fits I've seen (apart from your stuff you showed at the conference Gary!), that the latter may predominate. I agree that we should include this feature as a default part of model checking in PINTS.

@MichaelClerx Sounds good. How about next Wednesday? Say, 3pm?

A question to all -- what would be some good example models to further test the AR1 stuff on? I was thinking of something in electrochemistry or electrophysiology...

I think that, paperwise, it'd be good to have, perhaps, two fake data examples: one with the logistic and one with another model; and also real data example. What would be the best real data to test this on? On second thought, it might be best to try this method on the real data first -- to see if it's actually useful!

**Comment by MichaelClerx** [comment]
@ben18785 15:00 next week is perfect!

If you're looking to fit a model to its own data the aslanidi model we started out with should be ok. Or Kylie's model (but not fit to the sine waves).

If you're interested in real noise... I'm planning to collect patch-clamp noise from files from a couple of different setups in the next few days. Maybe even ask other labs to send me the start of traces :D That way we avoid the whole fitting business (or if you like we fit a simple offset and treat the rest as the residuals)

**Comment by ben18785** [comment]
@MichaelClerx Great -- 3pm it is! I think I would rather start with real noise to see if the AR1 model works in practice, then work backwards to simulated data. This is the opposite way round to which I usually work, but in this case, I want to see just how good/bad the models are and, in this context, whether it is worth the effort of fitting an AR1 model. It would be good to use PINTS to fit such a model using adaptive covariance MCMC. Is this implemented yet? Also, have we compared the output of the various MCMC routines in PINTS with that of Stan for the logistic model and, perhaps, a few other test examples? If not, I think this would be very worthwhile. Suspect you may have been waiting on me for the Stan side of things; sorry for the hold up!

The code to run the Stan part is in the Jupyter notebook for the AR1 stuff -- or would you prefer it if I set up a new notebook just for this purpose?

**Comment by ben18785** [comment]
@MichaelClerx Ok, great idea. I'll create an issue for it.

**Comment by martinjrobins** [comment]
@ben18785, the electrochemistry models might be worth looking at, as there are loads of data points and very small measurement noise, leading to extremely tight distributions if you assume independent noise. I have one model (A + e -> B in solution) where the fit is almost perfect (and 10 identical experimental data sets). This is the one that Dave mentioned, he has checked the residuals previously and they are normally distributed, but he didn't check the autocorrelation. I also have another model (A + e -> B, surface confined) where the fit is quite poor, and there is obvious correlated residuals. We could start with the good fit and check the autocorrelation of the residuals. This model is all working in pints (see here for a test: https://github.com/pints-team/pints/blob/master/problems/electrochemistry/test/test_optimisation.py) and I can send you the data file directly.

**Comment by ben18785** [comment]
@martinjrobins That'd be great, thank you. Are you around on Wednesday at all? I'm coming into meet Michael at 15.00, and if you were there, perhaps we could chat about it/pass data?

**Comment by MichaelClerx** [comment]
So what's next for this? Should we add a `case-studies` directory or something to place these things in?

**Comment by ben18785** [comment]
I think add a case study. I have made noise functions (and added them in my
nested sampling commit) to add autocorrelated noise to create fake data. We
ultimately will want to add functions that create functions which estimate
these sorts of likelihood...

**Comment by MichaelClerx** [comment]
Ok, it's in `problems/noise` now: https://github.com/pints-team/pints/blob/master/problems/noise/Logistic-ODE-AR1-Stan.ipynb
