### ISSUE TITLE
Add plot of distribution of previous results

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#783]

**Comment by chonlei** [comment]
Plot the functional testing results of a predefined of commit window as distributions:
- Hope to use this as an error detection tool later (e.g. set alert if latest result fall out of n deviation).

**Comment by MichaelClerx** [comment]
We might drop this in favour of Ben's change-point graphs! See #780

**Comment by MichaelClerx** [comment]
Part of changepoint anaysis now
