### ISSUE TITLE
The examples for `pints.plot` do not use `pints.plot`

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#787]
- [ ] [Should use `pints.plot.trace`](https://github.com/pints-team/pints/blob/master/examples/plot-mcmc-trace-plots.ipynb)
- [ ] [Should use `pints.plot.series`](https://github.com/pints-team/pints/blob/master/examples/plot-mcmc-predicted-time-series.ipynb)
- [ ] [Should use `pints.plot.histogram` and `pints.plot.pairwise`](https://github.com/pints-team/pints/blob/master/examples/plot-mcmc-pairwise-scatterplots.ipynb)
- [ ] [Should also use `pints.plot.histogram` and `pints.plot.pairwise`](https://github.com/pints-team/pints/blob/master/examples/plot-mcmc-pairwise-kde-plots.ipynb)
- [ ] [Should use `pints.plot.autocorrelation`](https://github.com/pints-team/pints/blob/master/examples/plot-mcmc-autocorrelation.ipynb)

The link at the top of all these examples is broken too

**Comment by chonlei** [comment]
Hmmm?! These 'plot-mcmc-' example series are the break down of `pints.plot` codes, so we didn't use any `pints.plot` there.

But now think about it, I guess we could, for all of them, add a link saying user can use `pints.plot`, a one line code, to plot the same thing?

**Comment by MichaelClerx** [comment]
Well yeah, they should all show how to use `pints.plot`, not how to replace it with custom code :-)

**Comment by MichaelClerx** [comment]
@chonlei :D

**Comment by rcw5890** [comment]
> The link at the top of all these examples is broken too

@MichaelClerx Which of the three adaptive covariance MCMC examples should be linked to? Maybe 
https://github.com/pints-team/pints/blob/pints-plot-examples/examples/sampling-adaptive-covariance-haario.ipynb

**Comment by MichaelClerx** [comment]
Good question! I'd suggest the haario-bardenet one for now.

@ben18785 we messed up quite a few examples I think in the adaptive covariance renaming :D
Should we add some kind of general adaptive covariance notebook, or just link to the haario-bardenet one?

**Comment by rcw5890** [comment]
> * [ ]  [Should also use `pints.plot.histogram` and `pints.plot.pairwise`](https://github.com/pints-team/pints/blob/master/examples/plot-mcmc-pairwise-kde-plots.ipynb)

As far as I can tell, `pints.plot.histogram` does not have support for the kernel density estimation (only `pint.plot.pairwise` has it). So in this example, there is no way to streamline the one variable histogram+KDE case unless KDE support is added to `pints.plot.histogram`.

Do you think it is worthwhile to add the KDE to `pints.plot.histogram`?

Since `pints.plot.pairwise` is handling the KDE now, this part of the example may no longer be necessary anyway.

**Comment by MichaelClerx** [comment]
That's a good point. Maybe you could (1) add the pairwise plot with kde to the first (non-kde) example, and (2) open an issue to add KDE support to the `histogram` function (maybe copy-paste the current example code into that issue)

**Comment by rcw5890** [comment]
#1016 is now open to add the KDE to `histogram`.

All of the other example notebooks should now be updated.

**Comment by MichaelClerx** [comment]
Awesome! If you open a PR I'll review it
