### ISSUE TITLE
Functional testing results repo

### ISSUE THREAD

**Issue by fcooper8472** [pints-team/pints#790]
The [functional-testing-results](https://github.com/pints-team/functional-testing-results) repo is currently 1.6Gb, increasing by the hour.

This is because we seem to be literally versioning png images every time a new test is run, and that's not really a use-case that GitHub is intended for.

We're definitely going to hit the GitHub "fair use" limits either sooner or later, so we will need a new strategy for reporting functional testing results.

**Comment by MichaelClerx** [comment]
Good point!

Do you think it'd help to start storing the images as SVG? Then - if we're lucky and new points are on new lines - we're at least storing updates rather than replacements

**Comment by MichaelClerx** [comment]
This will be addressed in #803 and #779

**Comment by MichaelClerx** [comment]
And #828
