### ISSUE TITLE
Stop storing log files in functional testing

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#803]
At the moment we store 2 things per test:

- A log, of the kind you find in typical optimisation/sampling runs, with iterations etc.
- A result file, with all the information about the test, as well as the main results (ones we manually select and stick in there)

As far as I can see, we never use the log file information, but it takes up a lot of space. I'm therefore very tempted to stop storing this.

Thoughts @martinjrobins @ben18785 ?

**Comment by martinjrobins** [comment]
Yup, let's stop storing the log. Easy enough to rerun the test if needed

**Comment by MichaelClerx** [comment]
Done!
