### ISSUE TITLE
Start running repeats of a test in parallel, instead of sequential

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#815]
As discussed in meeting. May help prevent time-outs

**Comment by MichaelClerx** [comment]
This is in, right @fcooper8472 ?

**Comment by fcooper8472** [comment]
Yep, sorry, should have updated this!

Feel free to close this

**Comment by fcooper8472** [comment]
Incidentally this is one issue with having issues just in this repo and not in the functional_testing: when I tag my commits with #815 they don't show up here ;)
