### ISSUE TITLE
Reduce iterations for nested functional tests

### ISSUE THREAD

**Issue by fcooper8472** [pints-team/pints#818]
Functional tests for nested samplers currently use
```python
# Set max iterations
sampler.set_iterations(8000)
sampler.set_posterior_samples(2000)
```

But these tests are currently running for far too long.  @ben18785 has suggested just cutting the iterations in half.  Coupled with #815 this should bring the functional test run times well under control.

**Comment by fcooper8472** [comment]
Closed by https://github.com/pints-team/functional-testing/pull/12

**Comment by fcooper8472** [comment]
This failed!
```
ValueError: Number of posterior samples must not exceed 0.25 times (the number of iterations + the number of active points).
```
I have no idea why that's the case, since I don't know anything about these nested samplers (@ben18785 or @MichaelClerx)?

**Comment by fcooper8472** [comment]
In https://github.com/pints-team/functional-testing/commit/1e86d55693012f8788188338540045d16a37723b I have reduced the number of posterior samples, so there are now 4000 iterations and 1000 posterior samples.

This actually brings it in line with the `nested_normal` test, so suggest we run with this for the time being and see if it causes any problems.

**Comment by MichaelClerx** [comment]
@ben18785 did you get a chance to look at these yesterday?

Link here: https://github.com/pints-team/functional-testing/tree/master/pfunk/tests

If not, we can have another go at getting the repo cloned next Tuesday :D
