### ISSUE TITLE
Non-tuple sequence for multidimensional indexing?

### ISSUE THREAD

**Issue by fcooper8472** [pints-team/pints#819]
There are warnings in a number of the functional tests:

```
/home/pints/.local/lib/python3.6/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
```

But they don't seem to give enough information to identify where the problem is... Any ideas @MichaelClerx?

**Comment by MichaelClerx** [comment]
Good spot! Which tests do we see this in?

**Comment by MichaelClerx** [comment]
- opt_br_SNES

**Comment by iamleeg** [comment]
Try turning the warnings into errors to get a backtrace:

    import warnings
    warnings.filterwarnings("FutureWarning")

**Comment by MichaelClerx** [comment]
Unable to recreate this locally !

**Comment by MichaelClerx** [comment]
Do get the error on skip, using

```./funk run opt_logistic_XNES --plot```

**Comment by MichaelClerx** [comment]
Ah. It's a change in numpy that causes scipy to raise this error inside its methods. Nothing we can do about it. Has already been fixed in newer scipy versions!
