### ISSUE TITLE
Failing optimisation tests (Fitzhugh-Nagumo)

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#820]
The FN problem is quite hard for some optimisers, and so the tests fail relatively often

- Wondering if we should tweak the parameters a bit to get better results? The tests currently run really fast, so we could have internal repeats of the runs from various starting points; this is what we do in real life situations so not _that_ hacky
- Alternatively stricter boundaries or parameter transforms might help
- We could leave this as is for now, until we have a functional testing pass/fail criterion based on distributions...

**Comment by mirams** [comment]
I think it is nice to show which methods fail relatively often.... don't want to paint a false impression by starting too close to the right answer. 

But if we really would try different starting points, and it runs fast enough, nothing to stop the test being the best fit of a bunch of starting points?

**Comment by MichaelClerx** [comment]
Leaving this for now, to be fixed/changed when we get the new distribution based system
