### ISSUE TITLE
Tweak to multiprocessing?

### ISSUE THREAD

**Issue by fcooper8472** [pints-team/pints#824]
@MichaelClerx not sure what the purpose of this commit is:

https://github.com/pints-team/functional-testing/commit/6caa434dd43a4899a03c000c76bc1ed064a50f6c

If I've understood your commit correctly, it will turn off all multiprocessing.  As far as functional testing is concerned, `len(names)` is always `1` but `args.r` is `5`.  The point was to multiprocess over the `args.r` not over `names`.

Then you have the `if multi` inside the `for name in names` so even in the case of multiple names there would be no benefit?

**Comment by MichaelClerx** [comment]
Sorry, my mistake!

Commit was intended to 
- make single repeats run in a single process, for better debugging and as a slight optimisation
- fix linewidth

Will fix!

**Comment by MichaelClerx** [comment]
Fixed
