### ISSUE TITLE
Running 2 tests creates 1 empty row in DB

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#825]
Should at least have written python info, commit info etc., even if test not completed...

**Comment by iamleeg** [comment]
Can you give an example of a command line to run that exhibits this bug, please?

**Comment by MichaelClerx** [comment]
Sorry:

```
./funk run opt_logistic_XNES -r 2 --analyse
```

(or `python -m pfunk run ...`)

**Comment by iamleeg** [comment]
I've identified the problem, if not yet solved it. Each run creates a row in the database, but then they end up with the same ID for the row to write to. So the last write wins, but always writes to the first row.

**Comment by iamleeg** [comment]
@MichaelClerx see #17 in functional-testing: https://github.com/pints-team/functional-testing/pull/17

**Comment by MichaelClerx** [comment]
Thanks!
