### ISSUE TITLE
Multiprocessing: Think about what to do with `logging`

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#827]
All goes to stdout/stderr, but without indication of which process is writing

**Comment by iamleeg** [comment]
https://github.com/jruere/multiprocessing-logging on pypi

**Comment by MichaelClerx** [comment]
Prioritising: Should be easily done with answer above

**Comment by MichaelClerx** [comment]
https://github.com/pints-team/functional-testing/issues/26
