### ISSUE TITLE
Stop storing test results in git

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#828]
- [x] Get pints Projects website (https://cs.ox.ac.uk/projects/PINTS)
- [x] Add SSH key on skip, allowing it to rsync
- [x] Add script for automatic rsync
- [x] Make azure yaml call rsync script
- [x] Change report ~from .md to html file~ markdown to work nicely with hugo

Finally, figure out some way to backup the database anyway?

**Comment by iamleeg** [comment]
> Change report from .md to html file

Might be easiest to install `pandoc` and run it in a sync script

**Comment by MichaelClerx** [comment]
> Might be easiest to install pandoc and run it in the sync script

We're now thinking markdown is OK, as the website will be in hugo?

**Comment by fcooper8472** [comment]
Yep, I'm thinking we generate the relevant markdown page, stick it in the website (which could be a submodule, replaing function testing results), then the testing script can just run hugo on the website and deploy it?

**Comment by MichaelClerx** [comment]
@fcooper8472 we originally wrote

> Make azure yaml call rsync script

But have now made `funk commit` do it. Maybe it makes more sense to live in the yaml script though, as not every user who downloads the code can automatically do this?

**Comment by iamleeg** [comment]
> not every user who downloads the code can automatically do this

I think there are two different definitions of "this" and "not everyone" :)

1. not everyone who can run the tests can commit to the results repo
2. not everyone who can run the tests can deploy the website

Adopting the open world assumption, there are people who can do one of these things and not the other :). And people who can do both but don't _want_ to do both in a particular instance. So these should definitely be additional, optional steps, and not part of the standard test workflow.

**Comment by MichaelClerx** [comment]
OK, will make separate ticket for that
