### ISSUE TITLE
Functional testing redesign

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#832]
With the new database back-end, and Ben's stand-alone analysis in R, it might be good to rethink the code for functional testing.

I imagine we could have something like this:

1. External tool (Azure) schedules tests, updates things etc.
2. Current `pfunk` module runs tests and manages `pints` submodule, writes results to DB file
3. New R code reads DB file, runs analysis and generates plots
4. New module generates report, based on R code output
5. Script regenerates and updates website

So 3, 4 and 5 would be split off from `pfunk`, making it a test _running_ tool.

Does that sound sensible @martinjrobins @fcooper8472 @iamleeg ?

**Comment by ben18785** [comment]
A somewhat related issue is, can we now add further test problems? I think
there are a couple more problems that would be good to include (the toy
problems are already implemented so it's just a case of inserting them into
functional testing, I think).

**Comment by MichaelClerx** [comment]
We sure can! There are already some tickets open for that, but feel free to add more!

**Comment by MichaelClerx** [comment]
See https://github.com/pints-team/functional-testing#adding-tests for mini how-to

**Comment by iamleeg** [comment]
I think that's a great separation of concerns. If all of this stuff ends up in one tool it becomes tightly coupled, and workflows become constrained (e.g. you can only do analysis when Azure triggers a CI build)

**Comment by martinjrobins** [comment]
Yup, think this sounds good, that `pfunk` becomes a test running tool only. I was also thinking of running the comparison matrix (optimisers/samplers versus toy models) through `pfunk` as well.

**Comment by fcooper8472** [comment]
Sounds good to me!

**Comment by MichaelClerx** [comment]
Not sure anymore, now that we have changepoint detection in python too!

**Comment by MichaelClerx** [comment]
Happy to keep it as it is
