### ISSUE TITLE
Implement effective sample size calculations in PINTS

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#84]
The gold standard for sample generation is independent sampling. In practice, however, we can't do this -- our samples are dependent. Because of this dependence, our samples contain less information per incremental sample. Whilst one algorithm may generate many 1000s of samples per second, if they are highly correlated, then the resultant posterior will be much worse than another algorithm that generates 1 effective sample (i.e. equivalent to 1 independent sample from the posterior) per second.

A way to compare the performance of different samplers is to calculate the number of effective samples generated per second. This is easy to estimate with MCMC samples -- you just calculate the sample autocorrelations.

There is a fast way to do this using Fast Fourier Transforms which calculates the autocorrelations at all lags simultaneously. See 'Introduction to Markov chain Monte Carlo' by Geyer for formula and FFT details.

**Comment by MichaelClerx** [comment]
See https://github.com/pints-team/pints/tree/issue%2384

**Comment by MichaelClerx** [comment]
Does this remove the need for https://github.com/pints-team/pints/blob/16e94b356887ce6d6ca6dc3416390e0f84895825/examples/inference-effective-sample-size.ipynb ?

**Comment by MichaelClerx** [comment]
Added a pr so we can discuss the implementation :-)
See #135
