### ISSUE TITLE
`run_tests.py` may fall over if `nosub` is not specified

### ISSUE THREAD

**Issue by fcooper8472** [pints-team/pints#844]
### Symptom

This came to light when installing pints for @danielfridman98 on his Windows laptop. To reproduce:

- Install a clean Python 3.7.3
- Create a clean virtual environment
- Install PINTS (`pip install -e .[dev,docs]`)
- Run tests (`python run_tests.py --unit`)

This may fail with, e.g.,
```
ModuleNotFoundError: No module named 'numpy'
```

### Problem

`python run_tests.py --unit` runs the tests in a subprocess. This allows python2 or python3 to be invoked. The subprocess does not, however, run in the same environment, and so the python that's running the tests in the subprocess may not have the pints dependencies installed.

### Secondary problem

the `--nosub` option is masked by the `--unit` option, as the `if` statement for `unit` happens to be above the one for `nosub`.  This isn't intuitive at all!

#### One
Pass the `shell=True` option to the subprocess call.  I'm not a huge fan of this fix because, while it works, I don't understand why, and the documentation for that argument is unclear.

#### Two
Remove the subprocess functionality entirely.  I don't see any need for it: you can run the tests with any interpreter you like by running:
```
path/to/any/python run_tests.py --nosub
```
so the current invocations:
```
python run_tests.py --unit2
python run_tests.py --unit3
```
are essentially identical (as things stand) to:
```
python2 run_tests.py --nosub
python3 run_tests.py --nosub
```
Removing the subprocess functionality would simplify the testing script and remove the need for `unit2` `unit3` and `nosub` options (just leaving `unit`).

**Comment by MichaelClerx** [comment]
I think I'm OK with removing the subprocessing. Vague feeling there was a second reason though, something to do with Ctrl-C? But can't find any issues just now so happy to remove it...
