### ISSUE TITLE
Use this sphinx doc layout

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#849]
https://salib.readthedocs.io/en/latest/api.html#sobol-sensitivity-analysis

Looks great, w. references etc.

Would require:

- [x] Find out what the theme is called
- [x] Start using it
- [x] Update docstrings, if required
- [x] Update contributing.md with a basic template for docstrings

**Comment by abhidg** [comment]
Theme is https://github.com/bitprophet/alabaster - says it's the new default Sphinx theme.

**Comment by abhidg** [comment]
We should also settle on a docstring format: either Sphinx, Google or numpy/scipy style.

**Comment by MichaelClerx** [comment]
Prioritising: Should be easily done

**Comment by MichaelClerx** [comment]
Overlaps with #923

**Comment by MichaelClerx** [comment]
Turns out the nice bits are from sphinx extensions (specifically `napoleon`, so am trying that)

**Comment by MichaelClerx** [comment]
Fxied in #944
