### ISSUE TITLE
Have a think about multi-level and -fidelty MC

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#851]
Would require model interface that allows different fidelities of logposterior eval.
Could be cool to combine with emulator stuff

**Comment by MichaelClerx** [comment]
We could also think of models that can do a good simulation and a superfast bad simulation (e.g. with a simpler model?)

**Comment by mirams** [comment]
I think some scope limitation might be needed for pints!

**Comment by MichaelClerx** [comment]
I'm actually quite uncertain about this one. It sounded cool but I'm not sure we have any low-fidelity models that take the same inputs as high-fidelity ones. Emulators are an obvious choice, but their training data is probably more expensive than an MCMC run. So this could be a very short think... Still, it's good to know reasons for not doing stuff
