### ISSUE TITLE
Worry about stochastic ODE integrators?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#854]
Or don't?

used in inference, e.g. https://papers.nips.cc/paper/7955-implicit-probabilistic-integrators-for-odes

**Comment by mirams** [comment]
Hmmm, these break the nice separation between pints and a simulator, but on the other hand we will probably need simulators that can use them to do a few different fancy things. I would probably propose that the simulators have to implement a common pints interface to do SDE solves, but that doesn't get done within Pints itself...

**Comment by martinjrobins** [comment]
yea, agree that doing the forward model is outside PINTS' jurisdiction. If these probabilistic integrators do become popular, I think they would be better implemented within an integration package ala Sundials.

**Comment by MichaelClerx** [comment]
OK. Closing this now!
