### ISSUE TITLE
Plot/diagnose MCMC as it run?

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#857]
Just came to my mine, not sure if it is a good idea or not...

Maybe we can add an option to MCMCController that we can "plot as it runs"? So similar to the `log_chain_filename` method, but plot it using some of our `pints.plot` methods and then save it to somewhere, so somthing like `log_chain_diagnostic_filename`?

**Comment by MichaelClerx** [comment]
Feel free to experiment with it, but this kind of visualisation is exactly what the ask-tell interface is for.

Very common, easy-to-use stuff: MCMCController
More complicated, but also incredibly useful stuff: Ask-and-tell interface

The idea is that we keep the high-level interface clean and understandable. But provide power users with a lower-level interface that can do anything they need

**Comment by chonlei** [comment]
Yeah, just not sure if this is something that would be commonly useful for everyone to have it included in MCMCController. Or it is something that no one else in the world would need it except me fantasising about it; in this case, yeah, then I should go away and implement it with Ask-and-tell... I don't know.

**Comment by MichaelClerx** [comment]
Definitely something to do outside of the MCMC controller!

**Comment by MichaelClerx** [comment]
One thing we could do to make this easier, is to add the option of a callback method to be called after every iteration. E.g.

```
def print_mu(controller):
    print(controller.optimiser()._mu)
opt = pints.OptimisationController(...)
opt.set_callback(print_mu)
opt.run()
```

But would this be mixing paradigms / asking for trouble?

Thoughts @martinjrobins ?

**Comment by martinjrobins** [comment]
it is definitely mixing paradigms, we'd only want to do this if we feel that the ask-tell interface is insufficient. Surely ask-tell is ok for this?

**Comment by MichaelClerx** [comment]
That's true! Wondering if there's some way we can have the best of both worlds though :D

**Comment by MichaelClerx** [comment]
Probably would just confuse everything. OK. Closing this!
