### ISSUE TITLE
Dead link in CMAES

### ISSUE THREAD

**Issue by naunauyoh** [pints-team/pints#858]
https://github.com/pints-team/pints/blob/5adf1b2d5e743cedd27828fa1ebae4c5eaa2e7d3/pints/_optimisers/_cmaes.py#L26

Maybe we can use the ArXiv tutorial written by Hansen : https://arxiv.org/pdf/1604.00772.pdf

**Comment by MichaelClerx** [comment]
Thanks Arnaud, that looks good to me.

Could you please (1) make a branch called e.g. `858-cmaes-link`, (2) commit the change, and then (3) create a PR?
