### ISSUE TITLE
Model comparison - add functionality to capture log-posterior for each data point to PINTS

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#87]
Model comparison by WAIC (widely-acknowledged or Watanabe-Akaike information criterion) takes account of the uncertainty in the parameters, and the fit, to allow for more adequate model selection. 

To estimate this quantity, all we need to do is record the log-posterior at each sample to PINTS. After that, it's straightforward to calculate WAIC.

**Comment by MichaelClerx** [comment]
Please hold this off until #132 is done

And maybe add a separate ticket for the WAIC criterion (and mention it depends on this one!)

**Comment by MichaelClerx** [comment]
This can now be done via the ask-and-tell interface.

So to do WAIC, you could set up an inference routine based on the code in [MCMCSampling], specifically, by adding some storage methods here [https://github.com/pints-team/pints/blob/master/pints/_mcmc/__init__.py] (by which I mean adding them to the WAIC code, not by changing the MCMCSampling code!)
