### ISSUE TITLE
Create a wish list container for all prospective sampling / optimisation methods 

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#886]
Much more useful than creating an issue for each new method would be to put it into a useful container, which can be visualised to make sense of the work that will be done.

I am thinking it would be displayed on our main Github landing page or elsewhere; ideally as a sort of (collapsable) tree diagram where it is shown how each method relates to others. It would also have clickable links that direct users / developers to the original papers that created the methods. We could colour each node according to whether the method is implemented, in progress, or in the future.

Perhaps, this could be coded in JSON?

**Comment by MichaelClerx** [comment]
That does sound nice, but would require quite a bit of work and upkeep!

Not saying we shouldn't, but just to point out some possible snags:
- A lot of the feature issues are things we stumble on, so would require a bit of work to figure out where they go. We'd end up needing another place to post "todo: look at method x" issues then
- We'd still need an issue if/when we started implementing each method
- Figuring out the tree structure for optimisation is still an open issue (see #684)

Perhaps a simpler issue would be to just stick them all in a single issue per class?

**Comment by MichaelClerx** [comment]
> implemented, in progress, or in the future.

We might also want "out of scope" and a politer version of "not interested" ?

**Comment by ben18785** [comment]
Haha, yep! That's a good idea.

**Comment by MichaelClerx** [comment]
Can we consider this one done now, @ben18785 ?

**Comment by ben18785** [comment]
Yep!
