### ISSUE TITLE
Stochastic toy problems for ABC

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#890]
- [x] Stochastic degradation
- [x] Logistic model (see Ruth's paper [here](https://www.biorxiv.org/content/10.1101/533182v1.abstract)) as there are many choices)
- [ ] Production and degradation from [here](https://people.maths.ox.ac.uk/erban/Education/StochReacDiff.pdf)
- [ ] Lotka-Volterra. I've got a feeling that analytic results exist here
- [ ] Diffusion equation

**Comment by MichaelClerx** [comment]
Hey @ben18785 , can we tick box two now after #1025 ?

**Comment by MichaelClerx** [comment]
(Also worth considering if we need all 5, or splitting into 3-4 tickets?)

**Comment by ben18785** [comment]
@MichaelClerx Hmm, yes, I am happy to close this and just open a ticket for the Lotka-Volterra. (To be honest, a wider reform is needed and already sitting in PR #1067 -- this would allow us to input stochastic models much more easily.)
