### ISSUE TITLE
Rename BayesianLogLikelihood as LogPosterior

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#90]
As suggested by @ben18785 and @sanmitraghosh in #88 

> Can we perhaps rename the 'BayesianLogLikelihood' function in PINTS? I think it is confusing as people don't really use this terminology -- a log likelihood is not inherently Bayesian although I know you mean this as the likelihood * prior. How about 'LogPosterior'?

It's a bit odd to me, because we don't know the posterior yet!

**Comment by ben18785** [comment]
@MichaelClerx We know the unnormalised log posterior (this is just the likelihood * prior). It's common parlance to omit the 'unnormalised' part because its implicit -- if we knew the normalisation constant we wouldn't need to do sampling in the first place.
