### ISSUE TITLE
Stick Ben's GIST/BLOCKS thing in Github pages?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#908]
Think it should be possible to create a pints-team github.io, and then a project for the visualisation, and then link to that from README.md ?

Only advantage over gist is that it's editable by all pints members

**Comment by MichaelClerx** [comment]
Code: https://gist.github.com/ben18785/e02fc628d049a1e6b667245c331889a2 

 Vis: http://bl.ocks.org/ben18785/raw/e02fc628d049a1e6b667245c331889a2/

**Comment by MichaelClerx** [comment]
OK. We can now also use these:

View: https://pints-team.github.io/pints-methods-overview/

Edit: https://github.com/pints-team/pints-methods-overview

@ben18785 do you mind if we use these instead of gist? I'll make sure you have push access :D

**Comment by ben18785** [comment]
Perfect Michael! That's awesome -- a much better solution. Thanks very
much. Yeah, if you could give me push access, that'd be dandy.

Can we put a link to the vis on the PINTS main Github page too?

**Comment by MichaelClerx** [comment]
> Yeah, if you could give me push access, that'd be dandy.

Done! Want to give it a go?

**Comment by MichaelClerx** [comment]
And https://github.com/pints-team/pints/pull/910

**Comment by ben18785** [comment]
I've pushed and all looks good. Does it automatically update the viz?

**Comment by MichaelClerx** [comment]
Yup! There's an "environment" page that shows you when it's updated: https://github.com/pints-team/pints-methods-overview/deployments
