### ISSUE TITLE
Add badge with doi in it?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#912]
Hi all!

Was just thinking to add a badge at the top of the README with the DOI or the JORS paper. Good idea?

In the long run, should we have a list of PINTS-related papers somewhere on this website? I'm guessing we'll want to update which is the "main" PINTS paper from time to time, e.g. once its out it'll probably be the comp-bio paper?

Happy to hear your thoughts @ben18785 @martinjrobins and @everyone!

**Comment by ben18785** [comment]
That's a great idea! Think a list of all papers using PINTS is a good idea
- at the very least, it means we can keep track of them.

**Comment by MichaelClerx** [comment]
> Was just thinking to add a badge at the top of the README with the DOI or the JORS paper. Good idea?

Have noticed some people using that badge to point to a DOI for the _code_, so maybe this would be confusing?

**Comment by MichaelClerx** [comment]
> That's a great idea! Think a list of all papers using PINTS is a good idea
> - at the very least, it means we can keep track of them.

OK I'll make a separate issue for that :D

**Comment by MichaelClerx** [comment]
> Have noticed some people using that badge to point to a DOI for the code, so maybe this would be confusing?

OK. I now don't know what a doi badge should point at, exactly, so closing this!
Have made the citation more prominent in the README in #913
