### ISSUE TITLE
List of papers using PINTS?

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#914]
@ben18785 said:

> Think a list of all papers using PINTS is a good idea - at the very least, it means we can keep track of them.

It's a slight duplication of effort (e.g. google scholar, web of science, etc. should more or less do this already?)

What do we think?

**Comment by MichaelClerx** [comment]
Thoughts @martinjrobins @ben18785 ?

**Comment by martinjrobins** [comment]
I think this is good to have, as well as something in the README.md requesting everyone that use PINTS send us their papers to add to this list.

**Comment by fcooper8472** [comment]
How about actually keeping a nicely-formatted bib-file of papers using PINTS in the PINTS repo?

Would have been **very** useful on Chaste when we were putting together the JOSS paper!

**Comment by MichaelClerx** [comment]
Good plan!

Could we do a human-readable _and_ a bibtex one? Like this: https://github.com/pints-team/pints/blob/master/CITATION ?

**Comment by MichaelClerx** [comment]
https://www.cell.com/biophysj/fulltext/S0006-3495(19)30666-6
https://www.cell.com/biophysj/fulltext/S0006-3495(19)30597-1
https://www.cell.com/biophysj/fulltext/S0006-3495(19)30598-3

**Comment by MichaelClerx** [comment]
@martinjrobins have you used/mentioned PINTS so far?

**Comment by MichaelClerx** [comment]
https://onlinelibrary.wiley.com/doi/full/10.1002/celc.201800950

**Comment by MichaelClerx** [comment]
https://pubs.acs.org/doi/abs/10.1021/acs.analchem.8b04238
