### ISSUE TITLE
Add simple gradient descent optimiser

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#930]
See also #893 

Only for models with sensitivities

**Comment by MichaelClerx** [comment]
Prioritising: Should be easily done

**Comment by ben18785** [comment]
This would be very good to have as, at the moment, we are missing this, whereas Stan has it. I suggest all we do is wrap Scipy's optimisation functions. Sound ok?

**Comment by MichaelClerx** [comment]
No. wrapping scipy's optimisers is a separate issue. Gradient descent should be added from scratch, using ask and tell
