### ISSUE TITLE
Add a "before you begin" notebook

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#939]
Some chapter 0 to the PINTS story, that doesn't explain things, but links to our favourite resources on:

- Python (see also contributing.md)
- Something about modelling ?
- Pages that explain inference (Ben's book and videos?)
- Points people towards CONTRIBUTING.md for everything else?

**Comment by MichaelClerx** [comment]
@simonmarchant I guess your notebook goes somewhere between this one and the "first examples" ones?

**Comment by simonmarchant** [comment]
@MichaelClerx right now it does, but I'm happy to add this stuff if you'd like? I do an ultra-short explanation of Bayes' rule so could add links for further reading there, could add a section at the start with links to python resources, and a bit at the end for "where next?". Or if you'd prefer that "before you begin" is entirely separate from any explanations then I'm happy to do it as a separate markdown file - shouldn't take long.

**Comment by MichaelClerx** [comment]
I'm not sure! I was hoping we could just link to stuff for the basic basic introduction...
(e.g. Ben has done quite a bit of work explaining bayesian inference already, elsewhere)
Probably best to have a chat about this at some point, with. e.g. @ben18785 and @martinjrobins

**Comment by MichaelClerx** [comment]
@ben18785 wrote

> @MichaelClerx I like this idea -- how about if we put these tutorials in a separate repo?

Not sure why we'd need to move it?

I would very much like to have stuff like this in the PINTS repo, but not sure about the best way to structure it, and how much detail we need to provide VS where we should link to external resources!

**Comment by MichaelClerx** [comment]
If that means a separate repo where the goal is explaining stats instead of showing how PINTS works, that's fine by me too :D

We could do a version of your book with PINTS examples ;-)

**Comment by MichaelClerx** [comment]
Done in  #1159
