### ISSUE TITLE
Add ABC routine

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#96]
Like @sanmitraghosh 's matlab or @adaly 's python

**Comment by chonlei** [comment]
We might want to compare this alongside as well(?): [ABC-SysBio](http://www.theosysbio.bio.ic.ac.uk/resources/abc-sysbio/) #56

**Comment by MichaelClerx** [comment]
See also #56 Interface for likelihood-free problems

**Comment by MichaelClerx** [comment]
Been having a look at this. Should be pretty easy to have basic ABC rejection using any error measure or log likelihood, so no big changes needed?

**Comment by MichaelClerx** [comment]
Seems like this is roughly how it would work:

This code would live inside an `ABCController` (or `ABCAcceptRejectController`?)
```
sampler.set_n_draw(some parameter the user can configure)
samples = []
while len(samples) < n_target
    xs = sampler.draw()
    fs = evaluator.evaluate(xs)
    samples.extend(xs.tell())
```

inside the `ABCSampler` (or similar):
```
def ask():
    sample n_draw from prior and return
def tell(fs):
    accept or reject xs based on fs, return only those which are accepted
```

**Comment by MichaelClerx** [comment]
Closed in https://github.com/pints-team/pints/pull/1442
