### ISSUE TITLE
Organise examples folder into subfolders

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#965]
The examples directory has so many example notebooks (great!) that it is now quite hard to navigate. Can we instead put these into folders? I'd suggest just using the names that appear in the file names to do this. So, sampling, optimisation and so on.

**Comment by MichaelClerx** [comment]
Feel free!

**Comment by ben18785** [comment]
I'm thinking about moving to a simple folder structure like:

- optimisation
- sampling
- other-functionality

I'd rather keep it simple, so things aren't miscategorised.

If we rearrange into folders, do we still want the prefix names? I'm guessing not. So, for example, we would have ``dream-mcmc`` rather than ``sampling-dream-mcmc`` as the named example.

What do people think?

**Comment by MichaelClerx** [comment]
Sounds good!

**Comment by MichaelClerx** [comment]
Closed in #1037
