### ISSUE TITLE
Tidy up / redesign functional testing framework

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#979]
Current code isn't well organised, needs a bit of tidying

**Comment by ben18785** [comment]
@MichaelClerx I'd really like to add more functional tests if we can sort out changepoint detection. (@abhidg -- would you be able to have a look at the changepoint detection? When we spoke, I was suggesting that we make some methods run on proportion passing rather than the raw scores.)

**Comment by MichaelClerx** [comment]
There's already tickets for those issues @ben18785 !

- Determine whether a test has passed/failed #780 
- Change metric for optimiser changepoints to number of passes #906
- Other test ideas #843 #574 

This issue is about tidying up the code

**Comment by abhidg** [comment]
@ben18785 I'll take a look at it this week
