### ISSUE TITLE
Add simple harmonic oscillator ODE model

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#983]
Stan uses this for their examples, so think we should too.

**Comment by MichaelClerx** [comment]
Maybe more something for performance comparison? We've got much nicer ODEs already :-)

**Comment by MichaelClerx** [comment]
Cool! Don't forget these guys though: https://github.com/pints-team/pints/projects/8 :D

**Comment by MichaelClerx** [comment]
Closed in #984
