### ISSUE TITLE
End of __init__ method not clear in documentation

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#99]
![image](https://user-images.githubusercontent.com/26725646/33403883-066de36c-d55a-11e7-90b7-e97a14379f82.png)

Can we somehow add a line or indentation or any other thing to separate the class `__init__` arguments and the first class method? (i.e. separate `values` and `dimension()`.) It took me awhile to realise one is an argument and the other is a method (I guess even harder for the user!).

**Comment by MichaelClerx** [comment]
I agree, but think that would mean customising the css, so very low priority!

**Comment by MichaelClerx** [comment]
https://github.com/guzzle/guzzle_sphinx_theme/issues/30#issuecomment-406206923

We can fix it with a bit of custom CSS!

**Comment by MichaelClerx** [comment]
See #849

**Comment by MichaelClerx** [comment]
This should be fixed if we start using Numpy style parameter lists & literature references

**Comment by MichaelClerx** [comment]
Fixed in #944
